// Copyright 2024 The go-exactonline AUTHORS. All rights reserved.
//
// Use of this source code is governed by a MIT
// license that can be found in the LICENSE file.
// Code generated by gen-services.go; DO NOT EDIT.
package activities

import (
	"context"
	"encoding/json"

	"github.com/mcnijman/go-exactonline/api"
	"github.com/mcnijman/go-exactonline/types"
)

// EventsEndpoint is responsible for communicating with
// the Events endpoint of the Activities service.
type EventsEndpoint service

// Events:
// Service: Activities
// Entity: Events
// URL: /api/v1/{division}/activities/Events
// HasWebhook: false
// IsInBeta: false
// Methods: GET POST
// Endpoint docs: https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=ActivitiesEvents
type Events struct {
	MetaData *api.MetaData `json:"__metadata,omitempty"`
	// ID: Edm.Guid
	ID *types.GUID `json:"ID,omitempty"`

	// Account: Edm.Guid
	Account *types.GUID `json:"Account,omitempty"`

	// AccountName: Edm.String
	AccountName *string `json:"AccountName,omitempty"`

	// Attachments: RequestAttachments
	Attachments *json.RawMessage `json:"Attachments,omitempty"`

	// Campaign: Edm.Guid
	Campaign *types.GUID `json:"Campaign,omitempty"`

	// CampaignDescription: Edm.String
	CampaignDescription *string `json:"CampaignDescription,omitempty"`

	// Contact: Edm.Guid
	Contact *types.GUID `json:"Contact,omitempty"`

	// ContactFullName: Edm.String
	ContactFullName *string `json:"ContactFullName,omitempty"`

	// Created: Edm.DateTime
	Created *types.Date `json:"Created,omitempty"`

	// Creator: Edm.Guid
	Creator *types.GUID `json:"Creator,omitempty"`

	// CreatorFullName: Edm.String
	CreatorFullName *string `json:"CreatorFullName,omitempty"`

	// Description: Edm.String
	Description *string `json:"Description,omitempty"`

	// Division: Edm.Int32
	Division *int `json:"Division,omitempty"`

	// Document: Edm.Guid
	Document *types.GUID `json:"Document,omitempty"`

	// DocumentSubject: Edm.String
	DocumentSubject *string `json:"DocumentSubject,omitempty"`

	// EndDate: Edm.DateTime
	EndDate *types.Date `json:"EndDate,omitempty"`

	// HID: Edm.Int32
	HID *int `json:"HID,omitempty"`

	// Modified: Edm.DateTime
	Modified *types.Date `json:"Modified,omitempty"`

	// Modifier: Edm.Guid
	Modifier *types.GUID `json:"Modifier,omitempty"`

	// ModifierFullName: Edm.String
	ModifierFullName *string `json:"ModifierFullName,omitempty"`

	// Notes: Edm.String
	Notes *string `json:"Notes,omitempty"`

	// Opportunity: Edm.Guid
	Opportunity *types.GUID `json:"Opportunity,omitempty"`

	// OpportunityName: Edm.String
	OpportunityName *string `json:"OpportunityName,omitempty"`

	// Project: Edm.Guid
	Project *types.GUID `json:"Project,omitempty"`

	// ProjectDescription: Edm.String
	ProjectDescription *string `json:"ProjectDescription,omitempty"`

	// StartDate: Edm.DateTime
	StartDate *types.Date `json:"StartDate,omitempty"`

	// Status: Edm.Int32
	Status *int `json:"Status,omitempty"`

	// StatusDescription: Edm.String
	StatusDescription *string `json:"StatusDescription,omitempty"`

	// User: Edm.Guid
	User *types.GUID `json:"User,omitempty"`

	// UserFullName: Edm.String
	UserFullName *string `json:"UserFullName,omitempty"`
}

func (e *Events) GetPrimary() *types.GUID {
	return e.ID
}

func (s *EventsEndpoint) UserHasRights(ctx context.Context, division int, method string) (bool, error) {
	return s.client.UserHasRights(ctx, division, "activities/Events", method)
}

// List the Events entities in the provided division.
// If all is true, all the paginated results are fetched; if false, list the first page.
func (s *EventsEndpoint) List(ctx context.Context, division int, all bool, o *api.ListOptions) ([]*Events, error) {
	var entities []*Events
	u, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/activities/Events", division) // #nosec
	api.AddListOptionsToURL(u, o)

	if all {
		err := s.client.ListRequestAndDoAll(ctx, u.String(), &entities)
		return entities, err
	}
	_, _, err := s.client.NewRequestAndDo(ctx, "GET", u.String(), nil, &entities)
	return entities, err
}

// Get the Events entitiy in the provided division.
func (s *EventsEndpoint) Get(ctx context.Context, division int, id *types.GUID) (*Events, error) {
	b, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/activities/Events", division) // #nosec
	u, err := api.AddOdataKeyToURL(b, id)
	if err != nil {
		return nil, err
	}

	e := &Events{}
	_, _, requestError := s.client.NewRequestAndDo(ctx, "GET", u.String(), nil, e)
	return e, requestError
}

// New returns an empty Events entity
func (s *EventsEndpoint) New() *Events {
	return &Events{}
}

// Create the Events entity in the provided division.
func (s *EventsEndpoint) Create(ctx context.Context, division int, entity *Events) (*Events, error) {
	u, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/activities/Events", division) // #nosec
	e := &Events{}
	_, _, err := s.client.NewRequestAndDo(ctx, "POST", u.String(), entity, e)
	if err != nil {
		return nil, err
	}
	return e, nil
}
