sudo: false
language: go
go:
  - "1.11.x"
  - "1.10.x"
  - "1.9.x"
  - tip
env:
  global:
    - GO111MODULE=on
matrix:
  allow_failures:
    - go: tip
  fast_finish: true
install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
script:
  - go get -t -v ./...
  - diff -u <(echo -n) <(gofmt -d -s .)
  - go generate -x ./... && git diff --exit-code; code=$?; git checkout -- .; (exit $code)
  - go tool vet .
  - go test -v -race ./...
  - go test -v -covermode=count -coverprofile=coverage.out ./exactonline
  - $GOPATH/bin/goveralls -service=travis-ci
