// Copyright 2024 The go-exactonline AUTHORS. All rights reserved.
//
// Use of this source code is governed by a MIT
// license that can be found in the LICENSE file.
// Code generated by gen-services.go; DO NOT EDIT.
package bulk

import (
	"context"

	"github.com/mcnijman/go-exactonline/api"
	"github.com/mcnijman/go-exactonline/types"
)

// FinancialTransactionLinesEndpoint is responsible for communicating with
// the FinancialTransactionLines endpoint of the Bulk service.
type FinancialTransactionLinesEndpoint service

// FinancialTransactionLines:
// Service: Bulk
// Entity: FinancialTransactionLines
// URL: /api/v1/{division}/bulk/Financial/TransactionLines
// HasWebhook: false
// IsInBeta: false
// Methods: GET
// Endpoint docs: https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=BulkFinancialTransactionLines
type FinancialTransactionLines struct {
	MetaData *api.MetaData `json:"__metadata,omitempty"`
	// ID: Edm.Guid
	ID *types.GUID `json:"ID,omitempty"`

	// Account: Edm.Guid
	Account *types.GUID `json:"Account,omitempty"`

	// AccountCode: Edm.String
	AccountCode *string `json:"AccountCode,omitempty"`

	// AccountName: Edm.String
	AccountName *string `json:"AccountName,omitempty"`

	// AmountDC: Edm.Double
	AmountDC *float64 `json:"AmountDC,omitempty"`

	// AmountFC: Edm.Double
	AmountFC *float64 `json:"AmountFC,omitempty"`

	// AmountVATBaseFC: Edm.Double
	AmountVATBaseFC *float64 `json:"AmountVATBaseFC,omitempty"`

	// AmountVATFC: Edm.Double
	AmountVATFC *float64 `json:"AmountVATFC,omitempty"`

	// Asset: Edm.Guid
	Asset *types.GUID `json:"Asset,omitempty"`

	// AssetCode: Edm.String
	AssetCode *string `json:"AssetCode,omitempty"`

	// AssetDescription: Edm.String
	AssetDescription *string `json:"AssetDescription,omitempty"`

	// CostCenter: Edm.String
	CostCenter *string `json:"CostCenter,omitempty"`

	// CostCenterDescription: Edm.String
	CostCenterDescription *string `json:"CostCenterDescription,omitempty"`

	// CostUnit: Edm.String
	CostUnit *string `json:"CostUnit,omitempty"`

	// CostUnitDescription: Edm.String
	CostUnitDescription *string `json:"CostUnitDescription,omitempty"`

	// Created: Edm.DateTime
	Created *types.Date `json:"Created,omitempty"`

	// Creator: Edm.Guid
	Creator *types.GUID `json:"Creator,omitempty"`

	// CreatorFullName: Edm.String
	CreatorFullName *string `json:"CreatorFullName,omitempty"`

	// Currency: Edm.String
	Currency *string `json:"Currency,omitempty"`

	// CustomField: Edm.String
	CustomField *string `json:"CustomField,omitempty"`

	// Date: Edm.DateTime
	Date *types.Date `json:"Date,omitempty"`

	// Description: Edm.String
	Description *string `json:"Description,omitempty"`

	// Division: Edm.Int32
	Division *int `json:"Division,omitempty"`

	// Document: Edm.Guid
	Document *types.GUID `json:"Document,omitempty"`

	// DocumentNumber: Edm.Int32
	DocumentNumber *int `json:"DocumentNumber,omitempty"`

	// DocumentSubject: Edm.String
	DocumentSubject *string `json:"DocumentSubject,omitempty"`

	// DueDate: Edm.DateTime
	DueDate *types.Date `json:"DueDate,omitempty"`

	// EntryID: Edm.Guid
	EntryID *types.GUID `json:"EntryID,omitempty"`

	// EntryNumber: Edm.Int32
	EntryNumber *int `json:"EntryNumber,omitempty"`

	// ExchangeRate: Edm.Double
	ExchangeRate *float64 `json:"ExchangeRate,omitempty"`

	// ExternalLinkDescription: Edm.String
	ExternalLinkDescription *string `json:"ExternalLinkDescription,omitempty"`

	// ExternalLinkReference: Edm.String
	ExternalLinkReference *string `json:"ExternalLinkReference,omitempty"`

	// ExtraDutyAmountFC: Edm.Double
	ExtraDutyAmountFC *float64 `json:"ExtraDutyAmountFC,omitempty"`

	// ExtraDutyPercentage: Edm.Double
	ExtraDutyPercentage *float64 `json:"ExtraDutyPercentage,omitempty"`

	// FinancialPeriod: Edm.Int16
	FinancialPeriod *int `json:"FinancialPeriod,omitempty"`

	// FinancialYear: Edm.Int16
	FinancialYear *int `json:"FinancialYear,omitempty"`

	// GLAccount: Edm.Guid
	GLAccount *types.GUID `json:"GLAccount,omitempty"`

	// GLAccountCode: Edm.String
	GLAccountCode *string `json:"GLAccountCode,omitempty"`

	// GLAccountDescription: Edm.String
	GLAccountDescription *string `json:"GLAccountDescription,omitempty"`

	// InvoiceNumber: Edm.Int32
	InvoiceNumber *int `json:"InvoiceNumber,omitempty"`

	// Item: Edm.Guid
	Item *types.GUID `json:"Item,omitempty"`

	// ItemCode: Edm.String
	ItemCode *string `json:"ItemCode,omitempty"`

	// ItemDescription: Edm.String
	ItemDescription *string `json:"ItemDescription,omitempty"`

	// JournalCode: Edm.String
	JournalCode *string `json:"JournalCode,omitempty"`

	// JournalDescription: Edm.String
	JournalDescription *string `json:"JournalDescription,omitempty"`

	// LineNumber: Edm.Int32
	LineNumber *int `json:"LineNumber,omitempty"`

	// LineType: Edm.Int16
	LineType *int `json:"LineType,omitempty"`

	// Modified: Edm.DateTime
	Modified *types.Date `json:"Modified,omitempty"`

	// Modifier: Edm.Guid
	Modifier *types.GUID `json:"Modifier,omitempty"`

	// ModifierFullName: Edm.String
	ModifierFullName *string `json:"ModifierFullName,omitempty"`

	// Notes: Edm.String
	Notes *string `json:"Notes,omitempty"`

	// OffsetID: Edm.Guid
	OffsetID *types.GUID `json:"OffsetID,omitempty"`

	// OrderNumber: Edm.Int32
	OrderNumber *int `json:"OrderNumber,omitempty"`

	// PaymentDiscountAmount: Edm.Double
	PaymentDiscountAmount *float64 `json:"PaymentDiscountAmount,omitempty"`

	// PaymentReference: Edm.String
	PaymentReference *string `json:"PaymentReference,omitempty"`

	// Project: Edm.Guid
	Project *types.GUID `json:"Project,omitempty"`

	// ProjectCode: Edm.String
	ProjectCode *string `json:"ProjectCode,omitempty"`

	// ProjectDescription: Edm.String
	ProjectDescription *string `json:"ProjectDescription,omitempty"`

	// Quantity: Edm.Double
	Quantity *float64 `json:"Quantity,omitempty"`

	// SerialNumber: Edm.String
	SerialNumber *string `json:"SerialNumber,omitempty"`

	// ShopOrder: Edm.Guid
	ShopOrder *types.GUID `json:"ShopOrder,omitempty"`

	// Status: Edm.Int16
	Status *int `json:"Status,omitempty"`

	// Subscription: Edm.Guid
	Subscription *types.GUID `json:"Subscription,omitempty"`

	// SubscriptionDescription: Edm.String
	SubscriptionDescription *string `json:"SubscriptionDescription,omitempty"`

	// TrackingNumber: Edm.String
	TrackingNumber *string `json:"TrackingNumber,omitempty"`

	// TrackingNumberDescription: Edm.String
	TrackingNumberDescription *string `json:"TrackingNumberDescription,omitempty"`

	// Type: Edm.Int32
	Type *int `json:"Type,omitempty"`

	// VATCode: Edm.String
	VATCode *string `json:"VATCode,omitempty"`

	// VATCodeDescription: Edm.String
	VATCodeDescription *string `json:"VATCodeDescription,omitempty"`

	// VATPercentage: Edm.Double
	VATPercentage *float64 `json:"VATPercentage,omitempty"`

	// VATType: Edm.String
	VATType *string `json:"VATType,omitempty"`

	// YourRef: Edm.String
	YourRef *string `json:"YourRef,omitempty"`
}

func (e *FinancialTransactionLines) GetPrimary() *types.GUID {
	return e.ID
}

func (s *FinancialTransactionLinesEndpoint) UserHasRights(ctx context.Context, division int, method string) (bool, error) {
	return s.client.UserHasRights(ctx, division, "Financial/TransactionLines", method)
}

// List the FinancialTransactionLines entities in the provided division.
// If all is true, all the paginated results are fetched; if false, list the first page.
func (s *FinancialTransactionLinesEndpoint) List(ctx context.Context, division int, all bool, o *api.ListOptions) ([]*FinancialTransactionLines, error) {
	var entities []*FinancialTransactionLines
	u, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/bulk/Financial/TransactionLines", division) // #nosec
	api.AddListOptionsToURL(u, o)

	if all {
		err := s.client.ListRequestAndDoAll(ctx, u.String(), &entities)
		return entities, err
	}
	_, _, err := s.client.NewRequestAndDo(ctx, "GET", u.String(), nil, &entities)
	return entities, err
}

// Get the FinancialTransactionLines entitiy in the provided division.
func (s *FinancialTransactionLinesEndpoint) Get(ctx context.Context, division int, id *types.GUID) (*FinancialTransactionLines, error) {
	b, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/bulk/Financial/TransactionLines", division) // #nosec
	u, err := api.AddOdataKeyToURL(b, id)
	if err != nil {
		return nil, err
	}

	e := &FinancialTransactionLines{}
	_, _, requestError := s.client.NewRequestAndDo(ctx, "GET", u.String(), nil, e)
	return e, requestError
}
