// Copyright 2024 The go-exactonline AUTHORS. All rights reserved.
//
// Use of this source code is governed by a MIT
// license that can be found in the LICENSE file.
// Code generated by gen-services.go; DO NOT EDIT.
package bulk

import (
	"context"

	"github.com/mcnijman/go-exactonline/api"
	"github.com/mcnijman/go-exactonline/types"
)

// FinancialGLClassificationsEndpoint is responsible for communicating with
// the FinancialGLClassifications endpoint of the Bulk service.
type FinancialGLClassificationsEndpoint service

// FinancialGLClassifications:
// Service: Bulk
// Entity: FinancialGLClassifications
// URL: /api/v1/{division}/bulk/Financial/GLClassifications
// HasWebhook: false
// IsInBeta: false
// Methods: GET
// Endpoint docs: https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=BulkFinancialGLClassifications
type FinancialGLClassifications struct {
	MetaData *api.MetaData `json:"__metadata,omitempty"`
	// ID: Edm.Guid
	ID *types.GUID `json:"ID,omitempty"`

	// Abstract: Edm.Boolean
	Abstract *bool `json:"Abstract,omitempty"`

	// Balance: Edm.String
	Balance *string `json:"Balance,omitempty"`

	// Code: Edm.String
	Code *string `json:"Code,omitempty"`

	// Created: Edm.DateTime
	Created *types.Date `json:"Created,omitempty"`

	// Creator: Edm.Guid
	Creator *types.GUID `json:"Creator,omitempty"`

	// CreatorFullName: Edm.String
	CreatorFullName *string `json:"CreatorFullName,omitempty"`

	// Description: Edm.String
	Description *string `json:"Description,omitempty"`

	// Division: Edm.Int32
	Division *int `json:"Division,omitempty"`

	// IsTupleSubElement: Edm.Boolean
	IsTupleSubElement *bool `json:"IsTupleSubElement,omitempty"`

	// Modified: Edm.DateTime
	Modified *types.Date `json:"Modified,omitempty"`

	// Modifier: Edm.Guid
	Modifier *types.GUID `json:"Modifier,omitempty"`

	// ModifierFullName: Edm.String
	ModifierFullName *string `json:"ModifierFullName,omitempty"`

	// Name: Edm.String
	Name *string `json:"Name,omitempty"`

	// Nillable: Edm.Boolean
	Nillable *bool `json:"Nillable,omitempty"`

	// Parent: Edm.Guid
	Parent *types.GUID `json:"Parent,omitempty"`

	// PeriodType: Edm.String
	PeriodType *string `json:"PeriodType,omitempty"`

	// SubstitutionGroup: Edm.String
	SubstitutionGroup *string `json:"SubstitutionGroup,omitempty"`

	// TaxonomyNamespace: Edm.Guid
	TaxonomyNamespace *types.GUID `json:"TaxonomyNamespace,omitempty"`

	// TaxonomyNamespaceDescription: Edm.String
	TaxonomyNamespaceDescription *string `json:"TaxonomyNamespaceDescription,omitempty"`

	// Type: Edm.Guid
	Type *types.GUID `json:"Type,omitempty"`
}

func (e *FinancialGLClassifications) GetPrimary() *types.GUID {
	return e.ID
}

func (s *FinancialGLClassificationsEndpoint) UserHasRights(ctx context.Context, division int, method string) (bool, error) {
	return s.client.UserHasRights(ctx, division, "Financial/GLClassifications", method)
}

// List the FinancialGLClassifications entities in the provided division.
// If all is true, all the paginated results are fetched; if false, list the first page.
func (s *FinancialGLClassificationsEndpoint) List(ctx context.Context, division int, all bool, o *api.ListOptions) ([]*FinancialGLClassifications, error) {
	var entities []*FinancialGLClassifications
	u, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/bulk/Financial/GLClassifications", division) // #nosec
	api.AddListOptionsToURL(u, o)

	if all {
		err := s.client.ListRequestAndDoAll(ctx, u.String(), &entities)
		return entities, err
	}
	_, _, err := s.client.NewRequestAndDo(ctx, "GET", u.String(), nil, &entities)
	return entities, err
}

// Get the FinancialGLClassifications entitiy in the provided division.
func (s *FinancialGLClassificationsEndpoint) Get(ctx context.Context, division int, id *types.GUID) (*FinancialGLClassifications, error) {
	b, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/bulk/Financial/GLClassifications", division) // #nosec
	u, err := api.AddOdataKeyToURL(b, id)
	if err != nil {
		return nil, err
	}

	e := &FinancialGLClassifications{}
	_, _, requestError := s.client.NewRequestAndDo(ctx, "GET", u.String(), nil, e)
	return e, requestError
}
