// Copyright 2024 The go-exactonline AUTHORS. All rights reserved.
//
// Use of this source code is governed by a MIT
// license that can be found in the LICENSE file.
// Code generated by gen-services.go; DO NOT EDIT.
package subscription

import (
	"context"

	"github.com/mcnijman/go-exactonline/api"
	"github.com/mcnijman/go-exactonline/types"
)

// SubscriptionTypesEndpoint is responsible for communicating with
// the SubscriptionTypes endpoint of the Subscription service.
type SubscriptionTypesEndpoint service

// SubscriptionTypes:
// Service: Subscription
// Entity: SubscriptionTypes
// URL: /api/v1/{division}/subscription/SubscriptionTypes
// HasWebhook: false
// IsInBeta: false
// Methods: GET
// Endpoint docs: https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=SubscriptionSubscriptionTypes
type SubscriptionTypes struct {
	MetaData *api.MetaData `json:"__metadata,omitempty"`
	// ID: Edm.Guid
	ID *types.GUID `json:"ID,omitempty"`

	// AutomaticGenerateInvoiceDays: Edm.Int16
	AutomaticGenerateInvoiceDays *int `json:"AutomaticGenerateInvoiceDays,omitempty"`

	// AutomaticGenerateInvoiceDescription: Edm.String
	AutomaticGenerateInvoiceDescription *string `json:"AutomaticGenerateInvoiceDescription,omitempty"`

	// AutomaticGenerateInvoiceType: Edm.Int16
	AutomaticGenerateInvoiceType *int `json:"AutomaticGenerateInvoiceType,omitempty"`

	// AutomaticSendInvoiceDays: Edm.Int16
	AutomaticSendInvoiceDays *int `json:"AutomaticSendInvoiceDays,omitempty"`

	// AutomaticSendInvoiceMethod: Edm.Int16
	AutomaticSendInvoiceMethod *int `json:"AutomaticSendInvoiceMethod,omitempty"`

	// AutomaticSendInvoiceSender: Edm.Int16
	AutomaticSendInvoiceSender *int `json:"AutomaticSendInvoiceSender,omitempty"`

	// AutomaticSendInvoiceSenderMailbox: Edm.Guid
	AutomaticSendInvoiceSenderMailbox *types.GUID `json:"AutomaticSendInvoiceSenderMailbox,omitempty"`

	// AutomaticSendInvoiceType: Edm.Int16
	AutomaticSendInvoiceType *int `json:"AutomaticSendInvoiceType,omitempty"`

	// CancellationPeriod: Edm.Int16
	CancellationPeriod *int `json:"CancellationPeriod,omitempty"`

	// CancellationPeriodUnit: Edm.String
	CancellationPeriodUnit *string `json:"CancellationPeriodUnit,omitempty"`

	// Code: Edm.String
	Code *string `json:"Code,omitempty"`

	// Created: Edm.DateTime
	Created *types.Date `json:"Created,omitempty"`

	// Creator: Edm.Guid
	Creator *types.GUID `json:"Creator,omitempty"`

	// CreatorFullName: Edm.String
	CreatorFullName *string `json:"CreatorFullName,omitempty"`

	// CustomField: Edm.String
	CustomField *string `json:"CustomField,omitempty"`

	// Description: Edm.String
	Description *string `json:"Description,omitempty"`

	// Division: Edm.Int32
	Division *int `json:"Division,omitempty"`

	// EnablePaymentLink: Edm.Int16
	EnablePaymentLink *int `json:"EnablePaymentLink,omitempty"`

	// InvoiceCorrectionMethod: Edm.Int16
	InvoiceCorrectionMethod *int `json:"InvoiceCorrectionMethod,omitempty"`

	// InvoicePeriod: Edm.Int16
	InvoicePeriod *int `json:"InvoicePeriod,omitempty"`

	// InvoicePeriodUnit: Edm.String
	InvoicePeriodUnit *string `json:"InvoicePeriodUnit,omitempty"`

	// ManualRenewalMethod: Edm.Int16
	ManualRenewalMethod *int `json:"ManualRenewalMethod,omitempty"`

	// Modified: Edm.DateTime
	Modified *types.Date `json:"Modified,omitempty"`

	// Modifier: Edm.Guid
	Modifier *types.GUID `json:"Modifier,omitempty"`

	// ModifierFullName: Edm.String
	ModifierFullName *string `json:"ModifierFullName,omitempty"`

	// Notes: Edm.String
	Notes *string `json:"Notes,omitempty"`

	// ProlongationType: Edm.Byte
	ProlongationType *byte `json:"ProlongationType,omitempty"`

	// RenewalCancellationPeriod: Edm.Int16
	RenewalCancellationPeriod *int `json:"RenewalCancellationPeriod,omitempty"`

	// RenewalCancellationPeriodUnit: Edm.String
	RenewalCancellationPeriodUnit *string `json:"RenewalCancellationPeriodUnit,omitempty"`

	// RenewalPeriod: Edm.Int16
	RenewalPeriod *int `json:"RenewalPeriod,omitempty"`

	// RenewalPeriodUnit: Edm.String
	RenewalPeriodUnit *string `json:"RenewalPeriodUnit,omitempty"`

	// SubscriptionPeriod: Edm.Int16
	SubscriptionPeriod *int `json:"SubscriptionPeriod,omitempty"`

	// SubscriptionPeriodUnit: Edm.String
	SubscriptionPeriodUnit *string `json:"SubscriptionPeriodUnit,omitempty"`
}

func (e *SubscriptionTypes) GetPrimary() *types.GUID {
	return e.ID
}

func (s *SubscriptionTypesEndpoint) UserHasRights(ctx context.Context, division int, method string) (bool, error) {
	return s.client.UserHasRights(ctx, division, "subscription/SubscriptionTypes", method)
}

// List the SubscriptionTypes entities in the provided division.
// If all is true, all the paginated results are fetched; if false, list the first page.
func (s *SubscriptionTypesEndpoint) List(ctx context.Context, division int, all bool, o *api.ListOptions) ([]*SubscriptionTypes, error) {
	var entities []*SubscriptionTypes
	u, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/subscription/SubscriptionTypes", division) // #nosec
	api.AddListOptionsToURL(u, o)

	if all {
		err := s.client.ListRequestAndDoAll(ctx, u.String(), &entities)
		return entities, err
	}
	_, _, err := s.client.NewRequestAndDo(ctx, "GET", u.String(), nil, &entities)
	return entities, err
}

// Get the SubscriptionTypes entitiy in the provided division.
func (s *SubscriptionTypesEndpoint) Get(ctx context.Context, division int, id *types.GUID) (*SubscriptionTypes, error) {
	b, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/subscription/SubscriptionTypes", division) // #nosec
	u, err := api.AddOdataKeyToURL(b, id)
	if err != nil {
		return nil, err
	}

	e := &SubscriptionTypes{}
	_, _, requestError := s.client.NewRequestAndDo(ctx, "GET", u.String(), nil, e)
	return e, requestError
}
