// Copyright 2024 The go-exactonline AUTHORS. All rights reserved.
//
// Use of this source code is governed by a MIT
// license that can be found in the LICENSE file.
// Code generated by gen-services.go; DO NOT EDIT.
package general

import (
	"context"

	"github.com/mcnijman/go-exactonline/api"
	"github.com/mcnijman/go-exactonline/types"
)

// LayoutsEndpoint is responsible for communicating with
// the Layouts endpoint of the General service.
type LayoutsEndpoint service

// Layouts:
// Service: General
// Entity: Layouts
// URL: /api/v1/{division}/general/Layouts
// HasWebhook: false
// IsInBeta: false
// Methods: GET
// Endpoint docs: https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=GeneralLayouts
type Layouts struct {
	MetaData *api.MetaData `json:"__metadata,omitempty"`
	// ID: Edm.Guid
	ID *types.GUID `json:"ID,omitempty"`

	// Category: Edm.Int32
	Category *int `json:"Category,omitempty"`

	// CategoryName: Edm.String
	CategoryName *string `json:"CategoryName,omitempty"`

	// Created: Edm.DateTime
	Created *types.Date `json:"Created,omitempty"`

	// Creator: Edm.Guid
	Creator *types.GUID `json:"Creator,omitempty"`

	// CreatorFullName: Edm.String
	CreatorFullName *string `json:"CreatorFullName,omitempty"`

	// DDView: Edm.Guid
	DDView *types.GUID `json:"DDView,omitempty"`

	// Division: Edm.Int32
	Division *int `json:"Division,omitempty"`

	// Language: Edm.String
	Language *string `json:"Language,omitempty"`

	// Modified: Edm.DateTime
	Modified *types.Date `json:"Modified,omitempty"`

	// Modifier: Edm.Guid
	Modifier *types.GUID `json:"Modifier,omitempty"`

	// ModifierFullName: Edm.String
	ModifierFullName *string `json:"ModifierFullName,omitempty"`

	// Status: Edm.Int16
	Status *int `json:"Status,omitempty"`

	// Subject: Edm.String
	Subject *string `json:"Subject,omitempty"`

	// Type: Edm.Int16
	Type *int `json:"Type,omitempty"`
}

func (e *Layouts) GetPrimary() *types.GUID {
	return e.ID
}

func (s *LayoutsEndpoint) UserHasRights(ctx context.Context, division int, method string) (bool, error) {
	return s.client.UserHasRights(ctx, division, "general/Layouts", method)
}

// List the Layouts entities in the provided division.
// If all is true, all the paginated results are fetched; if false, list the first page.
func (s *LayoutsEndpoint) List(ctx context.Context, division int, all bool, o *api.ListOptions) ([]*Layouts, error) {
	var entities []*Layouts
	u, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/general/Layouts", division) // #nosec
	api.AddListOptionsToURL(u, o)

	if all {
		err := s.client.ListRequestAndDoAll(ctx, u.String(), &entities)
		return entities, err
	}
	_, _, err := s.client.NewRequestAndDo(ctx, "GET", u.String(), nil, &entities)
	return entities, err
}

// Get the Layouts entitiy in the provided division.
func (s *LayoutsEndpoint) Get(ctx context.Context, division int, id *types.GUID) (*Layouts, error) {
	b, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/general/Layouts", division) // #nosec
	u, err := api.AddOdataKeyToURL(b, id)
	if err != nil {
		return nil, err
	}

	e := &Layouts{}
	_, _, requestError := s.client.NewRequestAndDo(ctx, "GET", u.String(), nil, e)
	return e, requestError
}
