// Copyright 2024 The go-exactonline AUTHORS. All rights reserved.
//
// Use of this source code is governed by a MIT
// license that can be found in the LICENSE file.
// Code generated by gen-services.go; DO NOT EDIT.
package sync

import (
	"context"

	"github.com/mcnijman/go-exactonline/api"
	"github.com/mcnijman/go-exactonline/types"
)

// DeletedEndpoint is responsible for communicating with
// the Deleted endpoint of the Sync service.
type DeletedEndpoint service

// Deleted:
// Service: Sync
// Entity: Deleted
// URL: /api/v1/{division}/sync/Deleted
// HasWebhook: false
// IsInBeta: false
// Methods: GET
// Endpoint docs: https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=SyncDeleted
type Deleted struct {
	MetaData *api.MetaData `json:"__metadata,omitempty"`
	// Timestamp: Edm.Int64
	Timestamp *int64 `json:"Timestamp,omitempty"`

	// DeletedBy: Edm.Guid
	DeletedBy *types.GUID `json:"DeletedBy,omitempty"`

	// DeletedDate: Edm.DateTime
	DeletedDate *types.Date `json:"DeletedDate,omitempty"`

	// Division: Edm.Int32
	Division *int `json:"Division,omitempty"`

	// EntityKey: Edm.Guid
	EntityKey *types.GUID `json:"EntityKey,omitempty"`

	// EntityType: Edm.Int32
	EntityType *int `json:"EntityType,omitempty"`

	// ID: Edm.Guid
	ID *types.GUID `json:"ID,omitempty"`
}

func (e *Deleted) GetPrimary() *int64 {
	return e.Timestamp
}

func (s *DeletedEndpoint) UserHasRights(ctx context.Context, division int, method string) (bool, error) {
	return s.client.UserHasRights(ctx, division, "sync/Deleted", method)
}

// List the Deleted entities in the provided division.
// If all is true, all the paginated results are fetched; if false, list the first page.
func (s *DeletedEndpoint) List(ctx context.Context, division int, all bool, o *api.ListOptions) ([]*Deleted, error) {
	var entities []*Deleted
	u, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/sync/Deleted", division) // #nosec
	api.AddListOptionsToURL(u, o)

	if all {
		err := s.client.ListRequestAndDoAll(ctx, u.String(), &entities)
		return entities, err
	}
	_, _, err := s.client.NewRequestAndDo(ctx, "GET", u.String(), nil, &entities)
	return entities, err
}

// Get the Deleted entitiy in the provided division.
func (s *DeletedEndpoint) Get(ctx context.Context, division int, id *int64) (*Deleted, error) {
	b, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/sync/Deleted", division) // #nosec
	u, err := api.AddOdataKeyToURL(b, id)
	if err != nil {
		return nil, err
	}

	e := &Deleted{}
	_, _, requestError := s.client.NewRequestAndDo(ctx, "GET", u.String(), nil, e)
	return e, requestError
}
