// Copyright 2024 The go-exactonline AUTHORS. All rights reserved.
//
// Use of this source code is governed by a MIT
// license that can be found in the LICENSE file.
// Code generated by gen-services.go; DO NOT EDIT.
package sync

import (
	"context"

	"github.com/mcnijman/go-exactonline/api"
	"github.com/mcnijman/go-exactonline/types"
)

// InventoryItemStorageLocationsEndpoint is responsible for communicating with
// the InventoryItemStorageLocations endpoint of the Sync service.
type InventoryItemStorageLocationsEndpoint service

// InventoryItemStorageLocations:
// Service: Sync
// Entity: InventoryItemStorageLocations
// URL: /api/v1/{division}/sync/Inventory/ItemStorageLocations
// HasWebhook: false
// IsInBeta: false
// Methods: GET
// Endpoint docs: https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=SyncInventoryItemStorageLocations
type InventoryItemStorageLocations struct {
	MetaData *api.MetaData `json:"__metadata,omitempty"`
	// Timestamp: Edm.Int64
	Timestamp *int64 `json:"Timestamp,omitempty"`

	// Created: Edm.DateTime
	Created *types.Date `json:"Created,omitempty"`

	// Creator: Edm.Guid
	Creator *types.GUID `json:"Creator,omitempty"`

	// CreatorFullName: Edm.String
	CreatorFullName *string `json:"CreatorFullName,omitempty"`

	// Division: Edm.Int32
	Division *int `json:"Division,omitempty"`

	// ID: Edm.Guid
	ID *types.GUID `json:"ID,omitempty"`

	// Item: Edm.Guid
	Item *types.GUID `json:"Item,omitempty"`

	// ItemCode: Edm.String
	ItemCode *string `json:"ItemCode,omitempty"`

	// ItemDescription: Edm.String
	ItemDescription *string `json:"ItemDescription,omitempty"`

	// MaximumStock: Edm.Double
	MaximumStock *float64 `json:"MaximumStock,omitempty"`

	// MinimumStock: Edm.Double
	MinimumStock *float64 `json:"MinimumStock,omitempty"`

	// Modified: Edm.DateTime
	Modified *types.Date `json:"Modified,omitempty"`

	// Modifier: Edm.Guid
	Modifier *types.GUID `json:"Modifier,omitempty"`

	// ModifierFullName: Edm.String
	ModifierFullName *string `json:"ModifierFullName,omitempty"`

	// StorageLocation: Edm.Guid
	StorageLocation *types.GUID `json:"StorageLocation,omitempty"`

	// StorageLocationCode: Edm.String
	StorageLocationCode *string `json:"StorageLocationCode,omitempty"`

	// StorageLocationDescription: Edm.String
	StorageLocationDescription *string `json:"StorageLocationDescription,omitempty"`

	// Type: Edm.Int16
	Type *int `json:"Type,omitempty"`

	// Warehouse: Edm.Guid
	Warehouse *types.GUID `json:"Warehouse,omitempty"`

	// WarehouseCode: Edm.String
	WarehouseCode *string `json:"WarehouseCode,omitempty"`

	// WarehouseDescription: Edm.String
	WarehouseDescription *string `json:"WarehouseDescription,omitempty"`
}

func (e *InventoryItemStorageLocations) GetPrimary() *int64 {
	return e.Timestamp
}

func (s *InventoryItemStorageLocationsEndpoint) UserHasRights(ctx context.Context, division int, method string) (bool, error) {
	return s.client.UserHasRights(ctx, division, "Inventory/ItemStorageLocations", method)
}

// List the InventoryItemStorageLocations entities in the provided division.
// If all is true, all the paginated results are fetched; if false, list the first page.
func (s *InventoryItemStorageLocationsEndpoint) List(ctx context.Context, division int, all bool, o *api.ListOptions) ([]*InventoryItemStorageLocations, error) {
	var entities []*InventoryItemStorageLocations
	u, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/sync/Inventory/ItemStorageLocations", division) // #nosec
	api.AddListOptionsToURL(u, o)

	if all {
		err := s.client.ListRequestAndDoAll(ctx, u.String(), &entities)
		return entities, err
	}
	_, _, err := s.client.NewRequestAndDo(ctx, "GET", u.String(), nil, &entities)
	return entities, err
}

// Get the InventoryItemStorageLocations entitiy in the provided division.
func (s *InventoryItemStorageLocationsEndpoint) Get(ctx context.Context, division int, id *int64) (*InventoryItemStorageLocations, error) {
	b, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/sync/Inventory/ItemStorageLocations", division) // #nosec
	u, err := api.AddOdataKeyToURL(b, id)
	if err != nil {
		return nil, err
	}

	e := &InventoryItemStorageLocations{}
	_, _, requestError := s.client.NewRequestAndDo(ctx, "GET", u.String(), nil, e)
	return e, requestError
}
