// Copyright 2024 The go-exactonline AUTHORS. All rights reserved.
//
// Use of this source code is governed by a MIT
// license that can be found in the LICENSE file.
// Code generated by gen-services.go; DO NOT EDIT.
package sync

import (
	"context"

	"github.com/mcnijman/go-exactonline/api"
	"github.com/mcnijman/go-exactonline/types"
)

// InventoryStockPositionsEndpoint is responsible for communicating with
// the InventoryStockPositions endpoint of the Sync service.
type InventoryStockPositionsEndpoint service

// InventoryStockPositions:
// Service: Sync
// Entity: InventoryStockPositions
// URL: /api/v1/{division}/sync/Inventory/StockPositions
// HasWebhook: false
// IsInBeta: false
// Methods: GET
// Endpoint docs: https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=SyncInventoryStockPositions
type InventoryStockPositions struct {
	MetaData *api.MetaData `json:"__metadata,omitempty"`
	// Timestamp: Edm.Int64
	Timestamp *int64 `json:"Timestamp,omitempty"`

	// CurrentStock: Edm.Double
	CurrentStock *float64 `json:"CurrentStock,omitempty"`

	// Division: Edm.Int32
	Division *int `json:"Division,omitempty"`

	// FreeStock: Edm.Double
	FreeStock *float64 `json:"FreeStock,omitempty"`

	// ID: Edm.Guid
	ID *types.GUID `json:"ID,omitempty"`

	// ItemCode: Edm.String
	ItemCode *string `json:"ItemCode,omitempty"`

	// ItemDescription: Edm.String
	ItemDescription *string `json:"ItemDescription,omitempty"`

	// ItemId: Edm.Guid
	ItemId *types.GUID `json:"ItemId,omitempty"`

	// PlanningIn: Edm.Double
	PlanningIn *float64 `json:"PlanningIn,omitempty"`

	// PlanningOut: Edm.Double
	PlanningOut *float64 `json:"PlanningOut,omitempty"`

	// ProjectedStock: Edm.Double
	ProjectedStock *float64 `json:"ProjectedStock,omitempty"`

	// ReorderPoint: Edm.Double
	ReorderPoint *float64 `json:"ReorderPoint,omitempty"`

	// ReservedStock: Edm.Double
	ReservedStock *float64 `json:"ReservedStock,omitempty"`

	// UnitCode: Edm.String
	UnitCode *string `json:"UnitCode,omitempty"`

	// UnitDescription: Edm.String
	UnitDescription *string `json:"UnitDescription,omitempty"`

	// Warehouse: Edm.Guid
	Warehouse *types.GUID `json:"Warehouse,omitempty"`

	// WarehouseCode: Edm.String
	WarehouseCode *string `json:"WarehouseCode,omitempty"`

	// WarehouseDescription: Edm.String
	WarehouseDescription *string `json:"WarehouseDescription,omitempty"`
}

func (e *InventoryStockPositions) GetPrimary() *int64 {
	return e.Timestamp
}

func (s *InventoryStockPositionsEndpoint) UserHasRights(ctx context.Context, division int, method string) (bool, error) {
	return s.client.UserHasRights(ctx, division, "Inventory/StockPositions", method)
}

// List the InventoryStockPositions entities in the provided division.
// If all is true, all the paginated results are fetched; if false, list the first page.
func (s *InventoryStockPositionsEndpoint) List(ctx context.Context, division int, all bool, o *api.ListOptions) ([]*InventoryStockPositions, error) {
	var entities []*InventoryStockPositions
	u, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/sync/Inventory/StockPositions", division) // #nosec
	api.AddListOptionsToURL(u, o)

	if all {
		err := s.client.ListRequestAndDoAll(ctx, u.String(), &entities)
		return entities, err
	}
	_, _, err := s.client.NewRequestAndDo(ctx, "GET", u.String(), nil, &entities)
	return entities, err
}

// Get the InventoryStockPositions entitiy in the provided division.
func (s *InventoryStockPositionsEndpoint) Get(ctx context.Context, division int, id *int64) (*InventoryStockPositions, error) {
	b, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/sync/Inventory/StockPositions", division) // #nosec
	u, err := api.AddOdataKeyToURL(b, id)
	if err != nil {
		return nil, err
	}

	e := &InventoryStockPositions{}
	_, _, requestError := s.client.NewRequestAndDo(ctx, "GET", u.String(), nil, e)
	return e, requestError
}
