// Copyright 2024 The go-exactonline AUTHORS. All rights reserved.
//
// Use of this source code is governed by a MIT
// license that can be found in the LICENSE file.
// Code generated by gen-services.go; DO NOT EDIT.
package sync

import (
	"context"

	"github.com/mcnijman/go-exactonline/api"
	"github.com/mcnijman/go-exactonline/types"
)

// LogisticsSupplierItemEndpoint is responsible for communicating with
// the LogisticsSupplierItem endpoint of the Sync service.
type LogisticsSupplierItemEndpoint service

// LogisticsSupplierItem:
// Service: Sync
// Entity: LogisticsSupplierItem
// URL: /api/v1/{division}/sync/Logistics/SupplierItem
// HasWebhook: false
// IsInBeta: false
// Methods: GET
// Endpoint docs: https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=SyncLogisticsSupplierItem
type LogisticsSupplierItem struct {
	MetaData *api.MetaData `json:"__metadata,omitempty"`
	// Timestamp: Edm.Int64
	Timestamp *int64 `json:"Timestamp,omitempty"`

	// CopyRemarks: Edm.Byte
	CopyRemarks *byte `json:"CopyRemarks,omitempty"`

	// CountryOfOrigin: Edm.String
	CountryOfOrigin *string `json:"CountryOfOrigin,omitempty"`

	// CountryOfOriginDescription: Edm.String
	CountryOfOriginDescription *string `json:"CountryOfOriginDescription,omitempty"`

	// Created: Edm.DateTime
	Created *types.Date `json:"Created,omitempty"`

	// Creator: Edm.Guid
	Creator *types.GUID `json:"Creator,omitempty"`

	// CreatorFullName: Edm.String
	CreatorFullName *string `json:"CreatorFullName,omitempty"`

	// Currency: Edm.String
	Currency *string `json:"Currency,omitempty"`

	// CurrencyDescription: Edm.String
	CurrencyDescription *string `json:"CurrencyDescription,omitempty"`

	// Division: Edm.Int32
	Division *int `json:"Division,omitempty"`

	// DropShipment: Edm.Byte
	DropShipment *byte `json:"DropShipment,omitempty"`

	// EndDate: Edm.DateTime
	EndDate *types.Date `json:"EndDate,omitempty"`

	// ID: Edm.Guid
	ID *types.GUID `json:"ID,omitempty"`

	// Item: Edm.Guid
	Item *types.GUID `json:"Item,omitempty"`

	// ItemCode: Edm.String
	ItemCode *string `json:"ItemCode,omitempty"`

	// ItemDescription: Edm.String
	ItemDescription *string `json:"ItemDescription,omitempty"`

	// ItemUnit: Edm.Guid
	ItemUnit *types.GUID `json:"ItemUnit,omitempty"`

	// ItemUnitCode: Edm.String
	ItemUnitCode *string `json:"ItemUnitCode,omitempty"`

	// ItemUnitDescription: Edm.String
	ItemUnitDescription *string `json:"ItemUnitDescription,omitempty"`

	// MainSupplier: Edm.Boolean
	MainSupplier *bool `json:"MainSupplier,omitempty"`

	// MinimumQuantity: Edm.Double
	MinimumQuantity *float64 `json:"MinimumQuantity,omitempty"`

	// Modified: Edm.DateTime
	Modified *types.Date `json:"Modified,omitempty"`

	// Modifier: Edm.Guid
	Modifier *types.GUID `json:"Modifier,omitempty"`

	// ModifierFullName: Edm.String
	ModifierFullName *string `json:"ModifierFullName,omitempty"`

	// Notes: Edm.String
	Notes *string `json:"Notes,omitempty"`

	// PurchaseLeadTime: Edm.Int32
	PurchaseLeadTime *int `json:"PurchaseLeadTime,omitempty"`

	// PurchaseLotSize: Edm.Int32
	PurchaseLotSize *int `json:"PurchaseLotSize,omitempty"`

	// PurchasePrice: Edm.Double
	PurchasePrice *float64 `json:"PurchasePrice,omitempty"`

	// PurchaseUnit: Edm.String
	PurchaseUnit *string `json:"PurchaseUnit,omitempty"`

	// PurchaseUnitDescription: Edm.String
	PurchaseUnitDescription *string `json:"PurchaseUnitDescription,omitempty"`

	// PurchaseUnitFactor: Edm.Double
	PurchaseUnitFactor *float64 `json:"PurchaseUnitFactor,omitempty"`

	// PurchaseVATCode: Edm.String
	PurchaseVATCode *string `json:"PurchaseVATCode,omitempty"`

	// PurchaseVATCodeDescription: Edm.String
	PurchaseVATCodeDescription *string `json:"PurchaseVATCodeDescription,omitempty"`

	// StartDate: Edm.DateTime
	StartDate *types.Date `json:"StartDate,omitempty"`

	// Supplier: Edm.Guid
	Supplier *types.GUID `json:"Supplier,omitempty"`

	// SupplierCode: Edm.String
	SupplierCode *string `json:"SupplierCode,omitempty"`

	// SupplierDescription: Edm.String
	SupplierDescription *string `json:"SupplierDescription,omitempty"`

	// SupplierItemCode: Edm.String
	SupplierItemCode *string `json:"SupplierItemCode,omitempty"`
}

func (e *LogisticsSupplierItem) GetPrimary() *int64 {
	return e.Timestamp
}

func (s *LogisticsSupplierItemEndpoint) UserHasRights(ctx context.Context, division int, method string) (bool, error) {
	return s.client.UserHasRights(ctx, division, "Logistics/SupplierItem", method)
}

// List the LogisticsSupplierItem entities in the provided division.
// If all is true, all the paginated results are fetched; if false, list the first page.
func (s *LogisticsSupplierItemEndpoint) List(ctx context.Context, division int, all bool, o *api.ListOptions) ([]*LogisticsSupplierItem, error) {
	var entities []*LogisticsSupplierItem
	u, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/sync/Logistics/SupplierItem", division) // #nosec
	api.AddListOptionsToURL(u, o)

	if all {
		err := s.client.ListRequestAndDoAll(ctx, u.String(), &entities)
		return entities, err
	}
	_, _, err := s.client.NewRequestAndDo(ctx, "GET", u.String(), nil, &entities)
	return entities, err
}

// Get the LogisticsSupplierItem entitiy in the provided division.
func (s *LogisticsSupplierItemEndpoint) Get(ctx context.Context, division int, id *int64) (*LogisticsSupplierItem, error) {
	b, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/sync/Logistics/SupplierItem", division) // #nosec
	u, err := api.AddOdataKeyToURL(b, id)
	if err != nil {
		return nil, err
	}

	e := &LogisticsSupplierItem{}
	_, _, requestError := s.client.NewRequestAndDo(ctx, "GET", u.String(), nil, e)
	return e, requestError
}
