// Copyright 2024 The go-exactonline AUTHORS. All rights reserved.
//
// Use of this source code is governed by a MIT
// license that can be found in the LICENSE file.
// Code generated by gen-services.go; DO NOT EDIT.
package sync

import (
	"context"

	"github.com/mcnijman/go-exactonline/api"
	"github.com/mcnijman/go-exactonline/types"
)

// ManufacturingShopOrderMaterialPlansEndpoint is responsible for communicating with
// the ManufacturingShopOrderMaterialPlans endpoint of the Sync service.
type ManufacturingShopOrderMaterialPlansEndpoint service

// ManufacturingShopOrderMaterialPlans:
// Service: Sync
// Entity: ManufacturingShopOrderMaterialPlans
// URL: /api/v1/{division}/sync/Manufacturing/ShopOrderMaterialPlans
// HasWebhook: false
// IsInBeta: false
// Methods: GET
// Endpoint docs: https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=SyncManufacturingShopOrderMaterialPlans
type ManufacturingShopOrderMaterialPlans struct {
	MetaData *api.MetaData `json:"__metadata,omitempty"`
	// Timestamp: Edm.Int64
	Timestamp *int64 `json:"Timestamp,omitempty"`

	// Backflush: Edm.Byte
	Backflush *byte `json:"Backflush,omitempty"`

	// CalculatorType: Edm.Int32
	CalculatorType *int `json:"CalculatorType,omitempty"`

	// Created: Edm.DateTime
	Created *types.Date `json:"Created,omitempty"`

	// Creator: Edm.Guid
	Creator *types.GUID `json:"Creator,omitempty"`

	// CreatorFullName: Edm.String
	CreatorFullName *string `json:"CreatorFullName,omitempty"`

	// Description: Edm.String
	Description *string `json:"Description,omitempty"`

	// DetailDrawing: Edm.String
	DetailDrawing *string `json:"DetailDrawing,omitempty"`

	// Division: Edm.Int32
	Division *int `json:"Division,omitempty"`

	// ID: Edm.Guid
	ID *types.GUID `json:"ID,omitempty"`

	// Item: Edm.Guid
	Item *types.GUID `json:"Item,omitempty"`

	// ItemCode: Edm.String
	ItemCode *string `json:"ItemCode,omitempty"`

	// ItemDescription: Edm.String
	ItemDescription *string `json:"ItemDescription,omitempty"`

	// ItemMaterial: Edm.Guid
	ItemMaterial *types.GUID `json:"ItemMaterial,omitempty"`

	// ItemPictureUrl: Edm.String
	ItemPictureUrl *string `json:"ItemPictureUrl,omitempty"`

	// LineNumber: Edm.Int32
	LineNumber *int `json:"LineNumber,omitempty"`

	// Modified: Edm.DateTime
	Modified *types.Date `json:"Modified,omitempty"`

	// Modifier: Edm.Guid
	Modifier *types.GUID `json:"Modifier,omitempty"`

	// ModifierFullName: Edm.String
	ModifierFullName *string `json:"ModifierFullName,omitempty"`

	// Notes: Edm.String
	Notes *string `json:"Notes,omitempty"`

	// PlannedAmountFC: Edm.Double
	PlannedAmountFC *float64 `json:"PlannedAmountFC,omitempty"`

	// PlannedDate: Edm.DateTime
	PlannedDate *types.Date `json:"PlannedDate,omitempty"`

	// PlannedPriceFC: Edm.Double
	PlannedPriceFC *float64 `json:"PlannedPriceFC,omitempty"`

	// PlannedQuantity: Edm.Double
	PlannedQuantity *float64 `json:"PlannedQuantity,omitempty"`

	// PlannedQuantityFactor: Edm.Double
	PlannedQuantityFactor *float64 `json:"PlannedQuantityFactor,omitempty"`

	// RoutingStepID: Edm.Guid
	RoutingStepID *types.GUID `json:"RoutingStepID,omitempty"`

	// ShopOrder: Edm.Guid
	ShopOrder *types.GUID `json:"ShopOrder,omitempty"`

	// Status: Edm.Int32
	Status *int `json:"Status,omitempty"`

	// StatusDescription: Edm.String
	StatusDescription *string `json:"StatusDescription,omitempty"`

	// Type: Edm.Int32
	Type *int `json:"Type,omitempty"`

	// Unit: Edm.String
	Unit *string `json:"Unit,omitempty"`

	// UnitDescription: Edm.String
	UnitDescription *string `json:"UnitDescription,omitempty"`

	// WastePercentage: Edm.Double
	WastePercentage *float64 `json:"WastePercentage,omitempty"`
}

func (e *ManufacturingShopOrderMaterialPlans) GetPrimary() *int64 {
	return e.Timestamp
}

func (s *ManufacturingShopOrderMaterialPlansEndpoint) UserHasRights(ctx context.Context, division int, method string) (bool, error) {
	return s.client.UserHasRights(ctx, division, "Manufacturing/ShopOrderMaterialPlans", method)
}

// List the ManufacturingShopOrderMaterialPlans entities in the provided division.
// If all is true, all the paginated results are fetched; if false, list the first page.
func (s *ManufacturingShopOrderMaterialPlansEndpoint) List(ctx context.Context, division int, all bool, o *api.ListOptions) ([]*ManufacturingShopOrderMaterialPlans, error) {
	var entities []*ManufacturingShopOrderMaterialPlans
	u, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/sync/Manufacturing/ShopOrderMaterialPlans", division) // #nosec
	api.AddListOptionsToURL(u, o)

	if all {
		err := s.client.ListRequestAndDoAll(ctx, u.String(), &entities)
		return entities, err
	}
	_, _, err := s.client.NewRequestAndDo(ctx, "GET", u.String(), nil, &entities)
	return entities, err
}

// Get the ManufacturingShopOrderMaterialPlans entitiy in the provided division.
func (s *ManufacturingShopOrderMaterialPlansEndpoint) Get(ctx context.Context, division int, id *int64) (*ManufacturingShopOrderMaterialPlans, error) {
	b, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/sync/Manufacturing/ShopOrderMaterialPlans", division) // #nosec
	u, err := api.AddOdataKeyToURL(b, id)
	if err != nil {
		return nil, err
	}

	e := &ManufacturingShopOrderMaterialPlans{}
	_, _, requestError := s.client.NewRequestAndDo(ctx, "GET", u.String(), nil, e)
	return e, requestError
}
