// Copyright 2024 The go-exactonline AUTHORS. All rights reserved.
//
// Use of this source code is governed by a MIT
// license that can be found in the LICENSE file.
// Code generated by gen-services.go; DO NOT EDIT.
package sync

import (
	"context"

	"github.com/mcnijman/go-exactonline/api"
	"github.com/mcnijman/go-exactonline/types"
)

// ProjectTimeCostTransactionsEndpoint is responsible for communicating with
// the ProjectTimeCostTransactions endpoint of the Sync service.
type ProjectTimeCostTransactionsEndpoint service

// ProjectTimeCostTransactions:
// Service: Sync
// Entity: ProjectTimeCostTransactions
// URL: /api/v1/{division}/sync/Project/TimeCostTransactions
// HasWebhook: false
// IsInBeta: false
// Methods: GET
// Endpoint docs: https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=SyncProjectTimeCostTransactions
type ProjectTimeCostTransactions struct {
	MetaData *api.MetaData `json:"__metadata,omitempty"`
	// Timestamp: Edm.Int64
	Timestamp *int64 `json:"Timestamp,omitempty"`

	// Account: Edm.Guid
	Account *types.GUID `json:"Account,omitempty"`

	// AccountName: Edm.String
	AccountName *string `json:"AccountName,omitempty"`

	// AmountFC: Edm.Double
	AmountFC *float64 `json:"AmountFC,omitempty"`

	// Attachment: Edm.Guid
	Attachment *types.GUID `json:"Attachment,omitempty"`

	// Created: Edm.DateTime
	Created *types.Date `json:"Created,omitempty"`

	// Creator: Edm.Guid
	Creator *types.GUID `json:"Creator,omitempty"`

	// CreatorFullName: Edm.String
	CreatorFullName *string `json:"CreatorFullName,omitempty"`

	// Currency: Edm.String
	Currency *string `json:"Currency,omitempty"`

	// CustomField: Edm.String
	CustomField *string `json:"CustomField,omitempty"`

	// Date: Edm.DateTime
	Date *types.Date `json:"Date,omitempty"`

	// Division: Edm.Int32
	Division *int `json:"Division,omitempty"`

	// DivisionDescription: Edm.String
	DivisionDescription *string `json:"DivisionDescription,omitempty"`

	// Employee: Edm.Guid
	Employee *types.GUID `json:"Employee,omitempty"`

	// EndTime: Edm.DateTime
	EndTime *types.Date `json:"EndTime,omitempty"`

	// EntryNumber: Edm.Int32
	EntryNumber *int `json:"EntryNumber,omitempty"`

	// ErrorText: Edm.String
	ErrorText *string `json:"ErrorText,omitempty"`

	// HourStatus: Edm.Int16
	HourStatus *int `json:"HourStatus,omitempty"`

	// ID: Edm.Guid
	ID *types.GUID `json:"ID,omitempty"`

	// Item: Edm.Guid
	Item *types.GUID `json:"Item,omitempty"`

	// ItemDescription: Edm.String
	ItemDescription *string `json:"ItemDescription,omitempty"`

	// ItemDivisable: Edm.Boolean
	ItemDivisable *bool `json:"ItemDivisable,omitempty"`

	// Modified: Edm.DateTime
	Modified *types.Date `json:"Modified,omitempty"`

	// Modifier: Edm.Guid
	Modifier *types.GUID `json:"Modifier,omitempty"`

	// ModifierFullName: Edm.String
	ModifierFullName *string `json:"ModifierFullName,omitempty"`

	// Notes: Edm.String
	Notes *string `json:"Notes,omitempty"`

	// PriceFC: Edm.Double
	PriceFC *float64 `json:"PriceFC,omitempty"`

	// Project: Edm.Guid
	Project *types.GUID `json:"Project,omitempty"`

	// ProjectAccount: Edm.Guid
	ProjectAccount *types.GUID `json:"ProjectAccount,omitempty"`

	// ProjectAccountCode: Edm.String
	ProjectAccountCode *string `json:"ProjectAccountCode,omitempty"`

	// ProjectAccountName: Edm.String
	ProjectAccountName *string `json:"ProjectAccountName,omitempty"`

	// ProjectCode: Edm.String
	ProjectCode *string `json:"ProjectCode,omitempty"`

	// ProjectDescription: Edm.String
	ProjectDescription *string `json:"ProjectDescription,omitempty"`

	// Quantity: Edm.Double
	Quantity *float64 `json:"Quantity,omitempty"`

	// StartTime: Edm.DateTime
	StartTime *types.Date `json:"StartTime,omitempty"`

	// Subscription: Edm.Guid
	Subscription *types.GUID `json:"Subscription,omitempty"`

	// SubscriptionAccount: Edm.Guid
	SubscriptionAccount *types.GUID `json:"SubscriptionAccount,omitempty"`

	// SubscriptionAccountCode: Edm.String
	SubscriptionAccountCode *string `json:"SubscriptionAccountCode,omitempty"`

	// SubscriptionAccountName: Edm.String
	SubscriptionAccountName *string `json:"SubscriptionAccountName,omitempty"`

	// SubscriptionDescription: Edm.String
	SubscriptionDescription *string `json:"SubscriptionDescription,omitempty"`

	// SubscriptionNumber: Edm.Int32
	SubscriptionNumber *int `json:"SubscriptionNumber,omitempty"`

	// Type: Edm.Int16
	Type *int `json:"Type,omitempty"`

	// WBS: Edm.Guid
	WBS *types.GUID `json:"WBS,omitempty"`

	// WBSDescription: Edm.String
	WBSDescription *string `json:"WBSDescription,omitempty"`
}

func (e *ProjectTimeCostTransactions) GetPrimary() *int64 {
	return e.Timestamp
}

func (s *ProjectTimeCostTransactionsEndpoint) UserHasRights(ctx context.Context, division int, method string) (bool, error) {
	return s.client.UserHasRights(ctx, division, "Project/TimeCostTransactions", method)
}

// List the ProjectTimeCostTransactions entities in the provided division.
// If all is true, all the paginated results are fetched; if false, list the first page.
func (s *ProjectTimeCostTransactionsEndpoint) List(ctx context.Context, division int, all bool, o *api.ListOptions) ([]*ProjectTimeCostTransactions, error) {
	var entities []*ProjectTimeCostTransactions
	u, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/sync/Project/TimeCostTransactions", division) // #nosec
	api.AddListOptionsToURL(u, o)

	if all {
		err := s.client.ListRequestAndDoAll(ctx, u.String(), &entities)
		return entities, err
	}
	_, _, err := s.client.NewRequestAndDo(ctx, "GET", u.String(), nil, &entities)
	return entities, err
}

// Get the ProjectTimeCostTransactions entitiy in the provided division.
func (s *ProjectTimeCostTransactionsEndpoint) Get(ctx context.Context, division int, id *int64) (*ProjectTimeCostTransactions, error) {
	b, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/sync/Project/TimeCostTransactions", division) // #nosec
	u, err := api.AddOdataKeyToURL(b, id)
	if err != nil {
		return nil, err
	}

	e := &ProjectTimeCostTransactions{}
	_, _, requestError := s.client.NewRequestAndDo(ctx, "GET", u.String(), nil, e)
	return e, requestError
}
