// Copyright 2024 The go-exactonline AUTHORS. All rights reserved.
//
// Use of this source code is governed by a MIT
// license that can be found in the LICENSE file.
// Code generated by gen-services.go; DO NOT EDIT.
package sync

import (
	"context"

	"github.com/mcnijman/go-exactonline/api"
	"github.com/mcnijman/go-exactonline/types"
)

// SalesSalesPriceListVolumeDiscountsEndpoint is responsible for communicating with
// the SalesSalesPriceListVolumeDiscounts endpoint of the Sync service.
type SalesSalesPriceListVolumeDiscountsEndpoint service

// SalesSalesPriceListVolumeDiscounts:
// Service: Sync
// Entity: SalesSalesPriceListVolumeDiscounts
// URL: /api/v1/{division}/sync/Sales/SalesPriceListVolumeDiscounts
// HasWebhook: false
// IsInBeta: false
// Methods: GET
// Endpoint docs: https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=SyncSalesSalesPriceListVolumeDiscounts
type SalesSalesPriceListVolumeDiscounts struct {
	MetaData *api.MetaData `json:"__metadata,omitempty"`
	// Timestamp: Edm.Int64
	Timestamp *int64 `json:"Timestamp,omitempty"`

	// BasePrice: Edm.Guid
	BasePrice *types.GUID `json:"BasePrice,omitempty"`

	// BasePriceAmount: Edm.Double
	BasePriceAmount *float64 `json:"BasePriceAmount,omitempty"`

	// Created: Edm.DateTime
	Created *types.Date `json:"Created,omitempty"`

	// Creator: Edm.Guid
	Creator *types.GUID `json:"Creator,omitempty"`

	// CreatorFullName: Edm.String
	CreatorFullName *string `json:"CreatorFullName,omitempty"`

	// Discount: Edm.Double
	Discount *float64 `json:"Discount,omitempty"`

	// Division: Edm.Int32
	Division *int `json:"Division,omitempty"`

	// EntryMethod: Edm.Int32
	EntryMethod *int `json:"EntryMethod,omitempty"`

	// ID: Edm.Guid
	ID *types.GUID `json:"ID,omitempty"`

	// Item: Edm.Guid
	Item *types.GUID `json:"Item,omitempty"`

	// ItemCode: Edm.String
	ItemCode *string `json:"ItemCode,omitempty"`

	// ItemDescription: Edm.String
	ItemDescription *string `json:"ItemDescription,omitempty"`

	// ItemGroup: Edm.Guid
	ItemGroup *types.GUID `json:"ItemGroup,omitempty"`

	// ItemGroupCode: Edm.String
	ItemGroupCode *string `json:"ItemGroupCode,omitempty"`

	// ItemGroupDescription: Edm.String
	ItemGroupDescription *string `json:"ItemGroupDescription,omitempty"`

	// Modified: Edm.DateTime
	Modified *types.Date `json:"Modified,omitempty"`

	// Modifier: Edm.Guid
	Modifier *types.GUID `json:"Modifier,omitempty"`

	// ModifierFullName: Edm.String
	ModifierFullName *string `json:"ModifierFullName,omitempty"`

	// NewPrice: Edm.Double
	NewPrice *float64 `json:"NewPrice,omitempty"`

	// NumberOfItemsPerUnit: Edm.Double
	NumberOfItemsPerUnit *float64 `json:"NumberOfItemsPerUnit,omitempty"`

	// PriceListCode: Edm.String
	PriceListCode *string `json:"PriceListCode,omitempty"`

	// PriceListDescription: Edm.String
	PriceListDescription *string `json:"PriceListDescription,omitempty"`

	// PriceListPeriod: Edm.Guid
	PriceListPeriod *types.GUID `json:"PriceListPeriod,omitempty"`

	// Quantity: Edm.Double
	Quantity *float64 `json:"Quantity,omitempty"`

	// Unit: Edm.String
	Unit *string `json:"Unit,omitempty"`

	// UnitDescription: Edm.String
	UnitDescription *string `json:"UnitDescription,omitempty"`
}

func (e *SalesSalesPriceListVolumeDiscounts) GetPrimary() *int64 {
	return e.Timestamp
}

func (s *SalesSalesPriceListVolumeDiscountsEndpoint) UserHasRights(ctx context.Context, division int, method string) (bool, error) {
	return s.client.UserHasRights(ctx, division, "Sales/SalesPriceListVolumeDiscounts", method)
}

// List the SalesSalesPriceListVolumeDiscounts entities in the provided division.
// If all is true, all the paginated results are fetched; if false, list the first page.
func (s *SalesSalesPriceListVolumeDiscountsEndpoint) List(ctx context.Context, division int, all bool, o *api.ListOptions) ([]*SalesSalesPriceListVolumeDiscounts, error) {
	var entities []*SalesSalesPriceListVolumeDiscounts
	u, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/sync/Sales/SalesPriceListVolumeDiscounts", division) // #nosec
	api.AddListOptionsToURL(u, o)

	if all {
		err := s.client.ListRequestAndDoAll(ctx, u.String(), &entities)
		return entities, err
	}
	_, _, err := s.client.NewRequestAndDo(ctx, "GET", u.String(), nil, &entities)
	return entities, err
}

// Get the SalesSalesPriceListVolumeDiscounts entitiy in the provided division.
func (s *SalesSalesPriceListVolumeDiscountsEndpoint) Get(ctx context.Context, division int, id *int64) (*SalesSalesPriceListVolumeDiscounts, error) {
	b, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/sync/Sales/SalesPriceListVolumeDiscounts", division) // #nosec
	u, err := api.AddOdataKeyToURL(b, id)
	if err != nil {
		return nil, err
	}

	e := &SalesSalesPriceListVolumeDiscounts{}
	_, _, requestError := s.client.NewRequestAndDo(ctx, "GET", u.String(), nil, e)
	return e, requestError
}
