// Copyright 2024 The go-exactonline AUTHORS. All rights reserved.
//
// Use of this source code is governed by a MIT
// license that can be found in the LICENSE file.
// Code generated by gen-services.go; DO NOT EDIT.
package sync

import (
	"context"

	"github.com/mcnijman/go-exactonline/api"
	"github.com/mcnijman/go-exactonline/types"
)

// SubscriptionSubscriptionLinesEndpoint is responsible for communicating with
// the SubscriptionSubscriptionLines endpoint of the Sync service.
type SubscriptionSubscriptionLinesEndpoint service

// SubscriptionSubscriptionLines:
// Service: Sync
// Entity: SubscriptionSubscriptionLines
// URL: /api/v1/{division}/sync/Subscription/SubscriptionLines
// HasWebhook: false
// IsInBeta: false
// Methods: GET
// Endpoint docs: https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=SyncSubscriptionSubscriptionLines
type SubscriptionSubscriptionLines struct {
	MetaData *api.MetaData `json:"__metadata,omitempty"`
	// Timestamp: Edm.Int64
	Timestamp *int64 `json:"Timestamp,omitempty"`

	// AmountDC: Edm.Double
	AmountDC *float64 `json:"AmountDC,omitempty"`

	// AmountFC: Edm.Double
	AmountFC *float64 `json:"AmountFC,omitempty"`

	// Costcenter: Edm.String
	Costcenter *string `json:"Costcenter,omitempty"`

	// Costunit: Edm.String
	Costunit *string `json:"Costunit,omitempty"`

	// CustomField: Edm.String
	CustomField *string `json:"CustomField,omitempty"`

	// Description: Edm.String
	Description *string `json:"Description,omitempty"`

	// Discount: Edm.Double
	Discount *float64 `json:"Discount,omitempty"`

	// Division: Edm.Int32
	Division *int `json:"Division,omitempty"`

	// EntryID: Edm.Guid
	EntryID *types.GUID `json:"EntryID,omitempty"`

	// FromDate: Edm.DateTime
	FromDate *types.Date `json:"FromDate,omitempty"`

	// ID: Edm.Guid
	ID *types.GUID `json:"ID,omitempty"`

	// Item: Edm.Guid
	Item *types.GUID `json:"Item,omitempty"`

	// ItemDescription: Edm.String
	ItemDescription *string `json:"ItemDescription,omitempty"`

	// LineNumber: Edm.Int32
	LineNumber *int `json:"LineNumber,omitempty"`

	// LineType: Edm.Int16
	LineType *int `json:"LineType,omitempty"`

	// LineTypeDescription: Edm.String
	LineTypeDescription *string `json:"LineTypeDescription,omitempty"`

	// Modified: Edm.DateTime
	Modified *types.Date `json:"Modified,omitempty"`

	// NetPrice: Edm.Double
	NetPrice *float64 `json:"NetPrice,omitempty"`

	// Notes: Edm.String
	Notes *string `json:"Notes,omitempty"`

	// Quantity: Edm.Double
	Quantity *float64 `json:"Quantity,omitempty"`

	// SubscriptionNumber: Edm.Int32
	SubscriptionNumber *int `json:"SubscriptionNumber,omitempty"`

	// ToDate: Edm.DateTime
	ToDate *types.Date `json:"ToDate,omitempty"`

	// UnitCode: Edm.String
	UnitCode *string `json:"UnitCode,omitempty"`

	// UnitDescription: Edm.String
	UnitDescription *string `json:"UnitDescription,omitempty"`

	// UnitPrice: Edm.Double
	UnitPrice *float64 `json:"UnitPrice,omitempty"`

	// VATAmountFC: Edm.Double
	VATAmountFC *float64 `json:"VATAmountFC,omitempty"`

	// VATCode: Edm.String
	VATCode *string `json:"VATCode,omitempty"`

	// VATCodeDescription: Edm.String
	VATCodeDescription *string `json:"VATCodeDescription,omitempty"`
}

func (e *SubscriptionSubscriptionLines) GetPrimary() *int64 {
	return e.Timestamp
}

func (s *SubscriptionSubscriptionLinesEndpoint) UserHasRights(ctx context.Context, division int, method string) (bool, error) {
	return s.client.UserHasRights(ctx, division, "Subscription/SubscriptionLines", method)
}

// List the SubscriptionSubscriptionLines entities in the provided division.
// If all is true, all the paginated results are fetched; if false, list the first page.
func (s *SubscriptionSubscriptionLinesEndpoint) List(ctx context.Context, division int, all bool, o *api.ListOptions) ([]*SubscriptionSubscriptionLines, error) {
	var entities []*SubscriptionSubscriptionLines
	u, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/sync/Subscription/SubscriptionLines", division) // #nosec
	api.AddListOptionsToURL(u, o)

	if all {
		err := s.client.ListRequestAndDoAll(ctx, u.String(), &entities)
		return entities, err
	}
	_, _, err := s.client.NewRequestAndDo(ctx, "GET", u.String(), nil, &entities)
	return entities, err
}

// Get the SubscriptionSubscriptionLines entitiy in the provided division.
func (s *SubscriptionSubscriptionLinesEndpoint) Get(ctx context.Context, division int, id *int64) (*SubscriptionSubscriptionLines, error) {
	b, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/sync/Subscription/SubscriptionLines", division) // #nosec
	u, err := api.AddOdataKeyToURL(b, id)
	if err != nil {
		return nil, err
	}

	e := &SubscriptionSubscriptionLines{}
	_, _, requestError := s.client.NewRequestAndDo(ctx, "GET", u.String(), nil, e)
	return e, requestError
}
