// Copyright 2024 The go-exactonline AUTHORS. All rights reserved.
//
// Use of this source code is governed by a MIT
// license that can be found in the LICENSE file.
// Code generated by gen-services.go; DO NOT EDIT.
package cashflow

import (
	"context"
	"fmt"
	"io/ioutil"
	"net/http"

	"github.com/mcnijman/go-exactonline/api"
	"github.com/mcnijman/go-exactonline/types"
)

// DirectDebitMandatesEndpoint is responsible for communicating with
// the DirectDebitMandates endpoint of the Cashflow service.
type DirectDebitMandatesEndpoint service

// DirectDebitMandates:
// Service: Cashflow
// Entity: DirectDebitMandates
// URL: /api/v1/{division}/cashflow/DirectDebitMandates
// HasWebhook: false
// IsInBeta: false
// Methods: GET POST PUT DELETE
// Endpoint docs: https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=CashflowDirectDebitMandates
type DirectDebitMandates struct {
	MetaData *api.MetaData `json:"__metadata,omitempty"`
	// ID: Edm.Guid
	ID *types.GUID `json:"ID,omitempty"`

	// Account: Edm.Guid
	Account *types.GUID `json:"Account,omitempty"`

	// BankAccount: Edm.Guid
	BankAccount *types.GUID `json:"BankAccount,omitempty"`

	// CancellationDate: Edm.DateTime
	CancellationDate *types.Date `json:"CancellationDate,omitempty"`

	// Created: Edm.DateTime
	Created *types.Date `json:"Created,omitempty"`

	// Creator: Edm.Guid
	Creator *types.GUID `json:"Creator,omitempty"`

	// CreatorFullName: Edm.String
	CreatorFullName *string `json:"CreatorFullName,omitempty"`

	// Description: Edm.String
	Description *string `json:"Description,omitempty"`

	// Division: Edm.Int32
	Division *int `json:"Division,omitempty"`

	// FirstSend: Edm.Byte
	FirstSend *byte `json:"FirstSend,omitempty"`

	// Main: Edm.Byte
	Main *byte `json:"Main,omitempty"`

	// Modified: Edm.DateTime
	Modified *types.Date `json:"Modified,omitempty"`

	// Modifier: Edm.Guid
	Modifier *types.GUID `json:"Modifier,omitempty"`

	// ModifierFullName: Edm.String
	ModifierFullName *string `json:"ModifierFullName,omitempty"`

	// PaymentType: Edm.Int16
	PaymentType *int `json:"PaymentType,omitempty"`

	// Reference: Edm.String
	Reference *string `json:"Reference,omitempty"`

	// SignatureDate: Edm.DateTime
	SignatureDate *types.Date `json:"SignatureDate,omitempty"`

	// Type: Edm.Int16
	Type *int `json:"Type,omitempty"`
}

func (e *DirectDebitMandates) GetPrimary() *types.GUID {
	return e.ID
}

func (s *DirectDebitMandatesEndpoint) UserHasRights(ctx context.Context, division int, method string) (bool, error) {
	return s.client.UserHasRights(ctx, division, "cashflow/DirectDebitMandates", method)
}

// List the DirectDebitMandates entities in the provided division.
// If all is true, all the paginated results are fetched; if false, list the first page.
func (s *DirectDebitMandatesEndpoint) List(ctx context.Context, division int, all bool, o *api.ListOptions) ([]*DirectDebitMandates, error) {
	var entities []*DirectDebitMandates
	u, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/cashflow/DirectDebitMandates", division) // #nosec
	api.AddListOptionsToURL(u, o)

	if all {
		err := s.client.ListRequestAndDoAll(ctx, u.String(), &entities)
		return entities, err
	}
	_, _, err := s.client.NewRequestAndDo(ctx, "GET", u.String(), nil, &entities)
	return entities, err
}

// Get the DirectDebitMandates entitiy in the provided division.
func (s *DirectDebitMandatesEndpoint) Get(ctx context.Context, division int, id *types.GUID) (*DirectDebitMandates, error) {
	b, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/cashflow/DirectDebitMandates", division) // #nosec
	u, err := api.AddOdataKeyToURL(b, id)
	if err != nil {
		return nil, err
	}

	e := &DirectDebitMandates{}
	_, _, requestError := s.client.NewRequestAndDo(ctx, "GET", u.String(), nil, e)
	return e, requestError
}

// New returns an empty DirectDebitMandates entity
func (s *DirectDebitMandatesEndpoint) New() *DirectDebitMandates {
	return &DirectDebitMandates{}
}

// Create the DirectDebitMandates entity in the provided division.
func (s *DirectDebitMandatesEndpoint) Create(ctx context.Context, division int, entity *DirectDebitMandates) (*DirectDebitMandates, error) {
	u, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/cashflow/DirectDebitMandates", division) // #nosec
	e := &DirectDebitMandates{}
	_, _, err := s.client.NewRequestAndDo(ctx, "POST", u.String(), entity, e)
	if err != nil {
		return nil, err
	}
	return e, nil
}

// Update the DirectDebitMandates entity in the provided division.
func (s *DirectDebitMandatesEndpoint) Update(ctx context.Context, division int, entity *DirectDebitMandates) (*DirectDebitMandates, error) {
	b, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/cashflow/DirectDebitMandates", division) // #nosec
	u, err := api.AddOdataKeyToURL(b, entity.GetPrimary())
	if err != nil {
		return nil, err
	}

	e := &DirectDebitMandates{}
	_, _, requestError := s.client.NewRequestAndDo(ctx, "PUT", u.String(), entity, e)
	return e, requestError
}

// Delete the DirectDebitMandates entity in the provided division.
func (s *DirectDebitMandatesEndpoint) Delete(ctx context.Context, division int, id *types.GUID) error {
	b, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/cashflow/DirectDebitMandates", division) // #nosec
	u, err := api.AddOdataKeyToURL(b, id)
	if err != nil {
		return err
	}

	_, r, requestError := s.client.NewRequestAndDo(ctx, "DELETE", u.String(), nil, nil)
	if requestError != nil {
		return requestError
	}

	if r.StatusCode != http.StatusNoContent {
		body, _ := ioutil.ReadAll(r.Body) // #nosec
		return fmt.Errorf("Failed with status %v and body %v", r.StatusCode, body)
	}

	return nil
}
