// Copyright 2024 The go-exactonline AUTHORS. All rights reserved.
//
// Use of this source code is governed by a MIT
// license that can be found in the LICENSE file.
// Code generated by gen-services.go; DO NOT EDIT.
package financial

import (
	"context"

	"github.com/mcnijman/go-exactonline/api"
	"github.com/mcnijman/go-exactonline/types"
)

// AgingReceivablesListEndpoint is responsible for communicating with
// the AgingReceivablesList endpoint of the Financial service.
type AgingReceivablesListEndpoint service

// AgingReceivablesList:
// Service: Financial
// Entity: AgingReceivablesList
// URL: /api/v1/{division}/read/financial/AgingReceivablesList
// HasWebhook: false
// IsInBeta: false
// Methods: GET
// Endpoint docs: https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=ReadFinancialAgingReceivablesList
type AgingReceivablesList struct {
	MetaData *api.MetaData `json:"__metadata,omitempty"`
	// AccountId: Edm.Guid
	AccountId *types.GUID `json:"AccountId,omitempty"`

	// AccountCode: Edm.String
	AccountCode *string `json:"AccountCode,omitempty"`

	// AccountName: Edm.String
	AccountName *string `json:"AccountName,omitempty"`

	// AgeGroup1: Edm.Int32
	AgeGroup1 *int `json:"AgeGroup1,omitempty"`

	// AgeGroup1Amount: Edm.Double
	AgeGroup1Amount *float64 `json:"AgeGroup1Amount,omitempty"`

	// AgeGroup1Description: Edm.String
	AgeGroup1Description *string `json:"AgeGroup1Description,omitempty"`

	// AgeGroup2: Edm.Int32
	AgeGroup2 *int `json:"AgeGroup2,omitempty"`

	// AgeGroup2Amount: Edm.Double
	AgeGroup2Amount *float64 `json:"AgeGroup2Amount,omitempty"`

	// AgeGroup2Description: Edm.String
	AgeGroup2Description *string `json:"AgeGroup2Description,omitempty"`

	// AgeGroup3: Edm.Int32
	AgeGroup3 *int `json:"AgeGroup3,omitempty"`

	// AgeGroup3Amount: Edm.Double
	AgeGroup3Amount *float64 `json:"AgeGroup3Amount,omitempty"`

	// AgeGroup3Description: Edm.String
	AgeGroup3Description *string `json:"AgeGroup3Description,omitempty"`

	// AgeGroup4: Edm.Int32
	AgeGroup4 *int `json:"AgeGroup4,omitempty"`

	// AgeGroup4Amount: Edm.Double
	AgeGroup4Amount *float64 `json:"AgeGroup4Amount,omitempty"`

	// AgeGroup4Description: Edm.String
	AgeGroup4Description *string `json:"AgeGroup4Description,omitempty"`

	// CurrencyCode: Edm.String
	CurrencyCode *string `json:"CurrencyCode,omitempty"`

	// TotalAmount: Edm.Double
	TotalAmount *float64 `json:"TotalAmount,omitempty"`
}

func (e *AgingReceivablesList) GetPrimary() *types.GUID {
	return e.AccountId
}

func (s *AgingReceivablesListEndpoint) UserHasRights(ctx context.Context, division int, method string) (bool, error) {
	return s.client.UserHasRights(ctx, division, "financial/AgingReceivablesList", method)
}

// List the AgingReceivablesList entities in the provided division.
// If all is true, all the paginated results are fetched; if false, list the first page.
func (s *AgingReceivablesListEndpoint) List(ctx context.Context, division int, all bool, o *api.ListOptions) ([]*AgingReceivablesList, error) {
	var entities []*AgingReceivablesList
	u, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/read/financial/AgingReceivablesList", division) // #nosec
	api.AddListOptionsToURL(u, o)

	if all {
		err := s.client.ListRequestAndDoAll(ctx, u.String(), &entities)
		return entities, err
	}
	_, _, err := s.client.NewRequestAndDo(ctx, "GET", u.String(), nil, &entities)
	return entities, err
}

// Get the AgingReceivablesList entitiy in the provided division.
func (s *AgingReceivablesListEndpoint) Get(ctx context.Context, division int, id *types.GUID) (*AgingReceivablesList, error) {
	b, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/read/financial/AgingReceivablesList", division) // #nosec
	u, err := api.AddOdataKeyToURL(b, id)
	if err != nil {
		return nil, err
	}

	e := &AgingReceivablesList{}
	_, _, requestError := s.client.NewRequestAndDo(ctx, "GET", u.String(), nil, e)
	return e, requestError
}
