// Copyright 2024 The go-exactonline AUTHORS. All rights reserved.
//
// Use of this source code is governed by a MIT
// license that can be found in the LICENSE file.
// Code generated by gen-services.go; DO NOT EDIT.
package financial

import (
	"context"
	"encoding/json"

	"github.com/mcnijman/go-exactonline/api"
	"github.com/mcnijman/go-exactonline/types"
)

// ReceivablesListByAccountAndAgeGroupEndpoint is responsible for communicating with
// the ReceivablesListByAccountAndAgeGroup endpoint of the Financial service.
type ReceivablesListByAccountAndAgeGroupEndpoint service

// ReceivablesListByAccountAndAgeGroup:
// Service: Financial
// Entity: ReceivablesListByAccountAndAgeGroup
// URL: /api/v1/{division}/read/financial/ReceivablesListByAccountAndAgeGroup
// HasWebhook: false
// IsInBeta: false
// Methods: GET
// Endpoint docs: https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=ReadFinancialReceivablesListByAccountAndAgeGroup
type ReceivablesListByAccountAndAgeGroup struct {
	MetaData *api.MetaData `json:"__metadata,omitempty"`
	// HID: Edm.Int64
	HID *int64 `json:"HID,omitempty"`

	// AccountCode: Edm.String
	AccountCode *string `json:"AccountCode,omitempty"`

	// AccountId: Edm.Guid
	AccountId *types.GUID `json:"AccountId,omitempty"`

	// AccountName: Edm.String
	AccountName *string `json:"AccountName,omitempty"`

	// Amount: Edm.Double
	Amount *float64 `json:"Amount,omitempty"`

	// AmountInTransit: Edm.Double
	AmountInTransit *float64 `json:"AmountInTransit,omitempty"`

	// CurrencyCode: Edm.String
	CurrencyCode *string `json:"CurrencyCode,omitempty"`

	// Description: Edm.String
	Description *string `json:"Description,omitempty"`

	// DueDate: Edm.DateTime
	DueDate *types.Date `json:"DueDate,omitempty"`

	// EntryNumber: Edm.Int32
	EntryNumber *int `json:"EntryNumber,omitempty"`

	// Id: Edm.Guid
	Id *types.GUID `json:"Id,omitempty"`

	// InvoiceDate: Edm.DateTime
	InvoiceDate *types.Date `json:"InvoiceDate,omitempty"`

	// InvoiceNumber: Edm.Int32
	InvoiceNumber *int `json:"InvoiceNumber,omitempty"`

	// JournalCode: Edm.String
	JournalCode *string `json:"JournalCode,omitempty"`

	// JournalDescription: Edm.String
	JournalDescription *string `json:"JournalDescription,omitempty"`

	// Notes: Notes
	Notes *json.RawMessage `json:"Notes,omitempty"`

	// YourRef: Edm.String
	YourRef *string `json:"YourRef,omitempty"`
}

func (e *ReceivablesListByAccountAndAgeGroup) GetPrimary() *int64 {
	return e.HID
}

func (s *ReceivablesListByAccountAndAgeGroupEndpoint) UserHasRights(ctx context.Context, division int, method string) (bool, error) {
	return s.client.UserHasRights(ctx, division, "financial/ReceivablesListByAccountAndAgeGroup", method)
}

// List the ReceivablesListByAccountAndAgeGroup entities in the provided division.
// If all is true, all the paginated results are fetched; if false, list the first page.
func (s *ReceivablesListByAccountAndAgeGroupEndpoint) List(ctx context.Context, division int, all bool, o *api.ListOptions) ([]*ReceivablesListByAccountAndAgeGroup, error) {
	var entities []*ReceivablesListByAccountAndAgeGroup
	u, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/read/financial/ReceivablesListByAccountAndAgeGroup", division) // #nosec
	api.AddListOptionsToURL(u, o)

	if all {
		err := s.client.ListRequestAndDoAll(ctx, u.String(), &entities)
		return entities, err
	}
	_, _, err := s.client.NewRequestAndDo(ctx, "GET", u.String(), nil, &entities)
	return entities, err
}

// Get the ReceivablesListByAccountAndAgeGroup entitiy in the provided division.
func (s *ReceivablesListByAccountAndAgeGroupEndpoint) Get(ctx context.Context, division int, id *int64) (*ReceivablesListByAccountAndAgeGroup, error) {
	b, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/read/financial/ReceivablesListByAccountAndAgeGroup", division) // #nosec
	u, err := api.AddOdataKeyToURL(b, id)
	if err != nil {
		return nil, err
	}

	e := &ReceivablesListByAccountAndAgeGroup{}
	_, _, requestError := s.client.NewRequestAndDo(ctx, "GET", u.String(), nil, e)
	return e, requestError
}
