// Copyright 2024 The go-exactonline AUTHORS. All rights reserved.
//
// Use of this source code is governed by a MIT
// license that can be found in the LICENSE file.
// Code generated by gen-services.go; DO NOT EDIT.
package system

import (
	"context"

	"github.com/mcnijman/go-exactonline/api"
	"github.com/mcnijman/go-exactonline/types"
)

// AccountantInfoEndpoint is responsible for communicating with
// the AccountantInfo endpoint of the System service.
type AccountantInfoEndpoint service

// AccountantInfo:
// Service: System
// Entity: AccountantInfo
// URL: /api/v1/{division}/system/AccountantInfo
// HasWebhook: false
// IsInBeta: false
// Methods: GET
// Endpoint docs: https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=SystemSystemAccountantInfo
type AccountantInfo struct {
	MetaData *api.MetaData `json:"__metadata,omitempty"`
	// ID: Edm.Guid
	ID *types.GUID `json:"ID,omitempty"`

	// AddressLine1: Edm.String
	AddressLine1 *string `json:"AddressLine1,omitempty"`

	// AddressLine2: Edm.String
	AddressLine2 *string `json:"AddressLine2,omitempty"`

	// AddressLine3: Edm.String
	AddressLine3 *string `json:"AddressLine3,omitempty"`

	// City: Edm.String
	City *string `json:"City,omitempty"`

	// Email: Edm.String
	Email *string `json:"Email,omitempty"`

	// IsAccountant: Edm.Boolean
	IsAccountant *bool `json:"IsAccountant,omitempty"`

	// Logo: Edm.Binary
	Logo *[]byte `json:"Logo,omitempty"`

	// MenuLogoUrl: Edm.String
	MenuLogoUrl *string `json:"MenuLogoUrl,omitempty"`

	// Name: Edm.String
	Name *string `json:"Name,omitempty"`

	// Phone: Edm.String
	Phone *string `json:"Phone,omitempty"`

	// Postcode: Edm.String
	Postcode *string `json:"Postcode,omitempty"`

	// Website: Edm.String
	Website *string `json:"Website,omitempty"`
}

func (e *AccountantInfo) GetPrimary() *types.GUID {
	return e.ID
}

func (s *AccountantInfoEndpoint) UserHasRights(ctx context.Context, division int, method string) (bool, error) {
	return s.client.UserHasRights(ctx, division, "system/AccountantInfo", method)
}

// List the AccountantInfo entities in the provided division.
// If all is true, all the paginated results are fetched; if false, list the first page.
func (s *AccountantInfoEndpoint) List(ctx context.Context, division int, all bool, o *api.ListOptions) ([]*AccountantInfo, error) {
	var entities []*AccountantInfo
	u, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/system/AccountantInfo", division) // #nosec
	api.AddListOptionsToURL(u, o)

	if all {
		err := s.client.ListRequestAndDoAll(ctx, u.String(), &entities)
		return entities, err
	}
	_, _, err := s.client.NewRequestAndDo(ctx, "GET", u.String(), nil, &entities)
	return entities, err
}

// Get the AccountantInfo entitiy in the provided division.
func (s *AccountantInfoEndpoint) Get(ctx context.Context, division int, id *types.GUID) (*AccountantInfo, error) {
	b, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/system/AccountantInfo", division) // #nosec
	u, err := api.AddOdataKeyToURL(b, id)
	if err != nil {
		return nil, err
	}

	e := &AccountantInfo{}
	_, _, requestError := s.client.NewRequestAndDo(ctx, "GET", u.String(), nil, e)
	return e, requestError
}
