// Copyright 2024 The go-exactonline AUTHORS. All rights reserved.
//
// Use of this source code is governed by a MIT
// license that can be found in the LICENSE file.
// Code generated by gen-services.go; DO NOT EDIT.
package system

import (
	"context"

	"github.com/mcnijman/go-exactonline/api"
	"github.com/mcnijman/go-exactonline/types"
)

// MeEndpoint is responsible for communicating with
// the Me endpoint of the System service.
type MeEndpoint service

// Me:
// Service: System
// Entity: Me
// URL: /api/v1/current/Me
// HasWebhook: false
// IsInBeta: false
// Methods: GET
// Endpoint docs: https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=SystemSystemMe
type Me struct {
	MetaData *api.MetaData `json:"__metadata,omitempty"`
	// UserID: Edm.Guid
	UserID *types.GUID `json:"UserID,omitempty"`

	// AccountingDivision: Edm.Int32
	AccountingDivision *int `json:"AccountingDivision,omitempty"`

	// CurrentDivision: Edm.Int32
	CurrentDivision *int `json:"CurrentDivision,omitempty"`

	// CustomerCode: Edm.String
	CustomerCode *string `json:"CustomerCode,omitempty"`

	// DivisionCustomer: Edm.Guid
	DivisionCustomer *types.GUID `json:"DivisionCustomer,omitempty"`

	// DivisionCustomerCode: Edm.String
	DivisionCustomerCode *string `json:"DivisionCustomerCode,omitempty"`

	// DivisionCustomerName: Edm.String
	DivisionCustomerName *string `json:"DivisionCustomerName,omitempty"`

	// DivisionCustomerSiretNumber: Edm.String
	DivisionCustomerSiretNumber *string `json:"DivisionCustomerSiretNumber,omitempty"`

	// DivisionCustomerVatNumber: Edm.String
	DivisionCustomerVatNumber *string `json:"DivisionCustomerVatNumber,omitempty"`

	// DossierDivision: Edm.Int32
	DossierDivision *int `json:"DossierDivision,omitempty"`

	// Email: Edm.String
	Email *string `json:"Email,omitempty"`

	// EmployeeID: Edm.Guid
	EmployeeID *types.GUID `json:"EmployeeID,omitempty"`

	// FirstName: Edm.String
	FirstName *string `json:"FirstName,omitempty"`

	// FullName: Edm.String
	FullName *string `json:"FullName,omitempty"`

	// Gender: Edm.String
	Gender *string `json:"Gender,omitempty"`

	// Initials: Edm.String
	Initials *string `json:"Initials,omitempty"`

	// IsClientUser: Edm.Boolean
	IsClientUser *bool `json:"IsClientUser,omitempty"`

	// IsEmployeeSelfServiceUser: Edm.Boolean
	IsEmployeeSelfServiceUser *bool `json:"IsEmployeeSelfServiceUser,omitempty"`

	// IsMyFirmLiteUser: Edm.Boolean
	IsMyFirmLiteUser *bool `json:"IsMyFirmLiteUser,omitempty"`

	// IsMyFirmPortalUser: Edm.Boolean
	IsMyFirmPortalUser *bool `json:"IsMyFirmPortalUser,omitempty"`

	// IsStarterUser: Edm.Boolean
	IsStarterUser *bool `json:"IsStarterUser,omitempty"`

	// Language: Edm.String
	Language *string `json:"Language,omitempty"`

	// LanguageCode: Edm.String
	LanguageCode *string `json:"LanguageCode,omitempty"`

	// LastName: Edm.String
	LastName *string `json:"LastName,omitempty"`

	// Legislation: Edm.Int64
	Legislation *int64 `json:"Legislation,string,omitempty"`

	// MiddleName: Edm.String
	MiddleName *string `json:"MiddleName,omitempty"`

	// Mobile: Edm.String
	Mobile *string `json:"Mobile,omitempty"`

	// Nationality: Edm.String
	Nationality *string `json:"Nationality,omitempty"`

	// PackageCode: Edm.String
	PackageCode *string `json:"PackageCode,omitempty"`

	// Phone: Edm.String
	Phone *string `json:"Phone,omitempty"`

	// PhoneExtension: Edm.String
	PhoneExtension *string `json:"PhoneExtension,omitempty"`

	// PictureUrl: Edm.String
	PictureUrl *string `json:"PictureUrl,omitempty"`

	// ServerTime: Edm.String
	ServerTime *string `json:"ServerTime,omitempty"`

	// ServerUtcOffset: Edm.Double
	ServerUtcOffset *float64 `json:"ServerUtcOffset,omitempty"`

	// ThumbnailPicture: Edm.Binary
	ThumbnailPicture *[]byte `json:"ThumbnailPicture,omitempty"`

	// ThumbnailPictureFormat: Edm.String
	ThumbnailPictureFormat *string `json:"ThumbnailPictureFormat,omitempty"`

	// Title: Edm.String
	Title *string `json:"Title,omitempty"`

	// UserName: Edm.String
	UserName *string `json:"UserName,omitempty"`
}

func (e *Me) GetPrimary() *types.GUID {
	return e.UserID
}

func (s *MeEndpoint) UserHasRights(ctx context.Context, division int, method string) (bool, error) {
	return s.client.UserHasRights(ctx, division, "current/Me", method)
}

// List the Me entities.
// If all is true, all the paginated results are fetched; if false, list the first page.
func (s *MeEndpoint) List(ctx context.Context, all bool, o *api.ListOptions) ([]*Me, error) {
	var entities []*Me
	u, _ := s.client.ResolveURL("/api/v1/current/Me") // #nosec
	api.AddListOptionsToURL(u, o)

	if all {
		err := s.client.ListRequestAndDoAll(ctx, u.String(), &entities)
		return entities, err
	}
	_, _, err := s.client.NewRequestAndDo(ctx, "GET", u.String(), nil, &entities)
	return entities, err
}

// Get the Me entitiy.
func (s *MeEndpoint) Get(ctx context.Context, id *types.GUID) (*Me, error) {
	b, _ := s.client.ResolveURL("/api/v1/current/Me") // #nosec
	u, err := api.AddOdataKeyToURL(b, id)
	if err != nil {
		return nil, err
	}

	e := &Me{}
	_, _, requestError := s.client.NewRequestAndDo(ctx, "GET", u.String(), nil, e)
	return e, requestError
}
