// Copyright 2024 The go-exactonline AUTHORS. All rights reserved.
//
// Use of this source code is governed by a MIT
// license that can be found in the LICENSE file.
// Code generated by gen-services.go; DO NOT EDIT.
package accountancy

import (
	"context"
	"fmt"
	"io/ioutil"
	"net/http"

	"github.com/mcnijman/go-exactonline/api"
	"github.com/mcnijman/go-exactonline/types"
)

// InvolvedUsersEndpoint is responsible for communicating with
// the InvolvedUsers endpoint of the Accountancy service.
type InvolvedUsersEndpoint service

// InvolvedUsers:
// Service: Accountancy
// Entity: InvolvedUsers
// URL: /api/v1/{division}/accountancy/InvolvedUsers
// HasWebhook: false
// IsInBeta: false
// Methods: GET POST PUT DELETE
// Endpoint docs: https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=AccountancyInvolvedUsers
type InvolvedUsers struct {
	MetaData *api.MetaData `json:"__metadata,omitempty"`
	// ID: Edm.Guid
	ID *types.GUID `json:"ID,omitempty"`

	// Account: Edm.Guid
	Account *types.GUID `json:"Account,omitempty"`

	// AccountCity: Edm.String
	AccountCity *string `json:"AccountCity,omitempty"`

	// AccountCode: Edm.String
	AccountCode *string `json:"AccountCode,omitempty"`

	// AccountIsSupplier: Edm.Boolean
	AccountIsSupplier *bool `json:"AccountIsSupplier,omitempty"`

	// AccountLogoThumbnailUrl: Edm.String
	AccountLogoThumbnailUrl *string `json:"AccountLogoThumbnailUrl,omitempty"`

	// AccountName: Edm.String
	AccountName *string `json:"AccountName,omitempty"`

	// AccountStatus: Edm.String
	AccountStatus *string `json:"AccountStatus,omitempty"`

	// Created: Edm.DateTime
	Created *types.Date `json:"Created,omitempty"`

	// Creator: Edm.Guid
	Creator *types.GUID `json:"Creator,omitempty"`

	// CreatorFullName: Edm.String
	CreatorFullName *string `json:"CreatorFullName,omitempty"`

	// Division: Edm.Int32
	Division *int `json:"Division,omitempty"`

	// InvolvedUserRole: Edm.Guid
	InvolvedUserRole *types.GUID `json:"InvolvedUserRole,omitempty"`

	// InvolvedUserRoleDescription: Edm.String
	InvolvedUserRoleDescription *string `json:"InvolvedUserRoleDescription,omitempty"`

	// IsMainContact: Edm.Boolean
	IsMainContact *bool `json:"IsMainContact,omitempty"`

	// Modified: Edm.DateTime
	Modified *types.Date `json:"Modified,omitempty"`

	// Modifier: Edm.Guid
	Modifier *types.GUID `json:"Modifier,omitempty"`

	// ModifierFullName: Edm.String
	ModifierFullName *string `json:"ModifierFullName,omitempty"`

	// PersonEmail: Edm.String
	PersonEmail *string `json:"PersonEmail,omitempty"`

	// PersonPhone: Edm.String
	PersonPhone *string `json:"PersonPhone,omitempty"`

	// PersonPhoneExtension: Edm.String
	PersonPhoneExtension *string `json:"PersonPhoneExtension,omitempty"`

	// PersonPictureThumbnailUrl: Edm.String
	PersonPictureThumbnailUrl *string `json:"PersonPictureThumbnailUrl,omitempty"`

	// User: Edm.Guid
	User *types.GUID `json:"User,omitempty"`

	// UserFullName: Edm.String
	UserFullName *string `json:"UserFullName,omitempty"`
}

func (e *InvolvedUsers) GetPrimary() *types.GUID {
	return e.ID
}

func (s *InvolvedUsersEndpoint) UserHasRights(ctx context.Context, division int, method string) (bool, error) {
	return s.client.UserHasRights(ctx, division, "accountancy/InvolvedUsers", method)
}

// List the InvolvedUsers entities in the provided division.
// If all is true, all the paginated results are fetched; if false, list the first page.
func (s *InvolvedUsersEndpoint) List(ctx context.Context, division int, all bool, o *api.ListOptions) ([]*InvolvedUsers, error) {
	var entities []*InvolvedUsers
	u, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/accountancy/InvolvedUsers", division) // #nosec
	api.AddListOptionsToURL(u, o)

	if all {
		err := s.client.ListRequestAndDoAll(ctx, u.String(), &entities)
		return entities, err
	}
	_, _, err := s.client.NewRequestAndDo(ctx, "GET", u.String(), nil, &entities)
	return entities, err
}

// Get the InvolvedUsers entitiy in the provided division.
func (s *InvolvedUsersEndpoint) Get(ctx context.Context, division int, id *types.GUID) (*InvolvedUsers, error) {
	b, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/accountancy/InvolvedUsers", division) // #nosec
	u, err := api.AddOdataKeyToURL(b, id)
	if err != nil {
		return nil, err
	}

	e := &InvolvedUsers{}
	_, _, requestError := s.client.NewRequestAndDo(ctx, "GET", u.String(), nil, e)
	return e, requestError
}

// New returns an empty InvolvedUsers entity
func (s *InvolvedUsersEndpoint) New() *InvolvedUsers {
	return &InvolvedUsers{}
}

// Create the InvolvedUsers entity in the provided division.
func (s *InvolvedUsersEndpoint) Create(ctx context.Context, division int, entity *InvolvedUsers) (*InvolvedUsers, error) {
	u, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/accountancy/InvolvedUsers", division) // #nosec
	e := &InvolvedUsers{}
	_, _, err := s.client.NewRequestAndDo(ctx, "POST", u.String(), entity, e)
	if err != nil {
		return nil, err
	}
	return e, nil
}

// Update the InvolvedUsers entity in the provided division.
func (s *InvolvedUsersEndpoint) Update(ctx context.Context, division int, entity *InvolvedUsers) (*InvolvedUsers, error) {
	b, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/accountancy/InvolvedUsers", division) // #nosec
	u, err := api.AddOdataKeyToURL(b, entity.GetPrimary())
	if err != nil {
		return nil, err
	}

	e := &InvolvedUsers{}
	_, _, requestError := s.client.NewRequestAndDo(ctx, "PUT", u.String(), entity, e)
	return e, requestError
}

// Delete the InvolvedUsers entity in the provided division.
func (s *InvolvedUsersEndpoint) Delete(ctx context.Context, division int, id *types.GUID) error {
	b, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/accountancy/InvolvedUsers", division) // #nosec
	u, err := api.AddOdataKeyToURL(b, id)
	if err != nil {
		return err
	}

	_, r, requestError := s.client.NewRequestAndDo(ctx, "DELETE", u.String(), nil, nil)
	if requestError != nil {
		return requestError
	}

	if r.StatusCode != http.StatusNoContent {
		body, _ := ioutil.ReadAll(r.Body) // #nosec
		return fmt.Errorf("Failed with status %v and body %v", r.StatusCode, body)
	}

	return nil
}
