// Copyright 2024 The go-exactonline AUTHORS. All rights reserved.
//
// Use of this source code is governed by a MIT
// license that can be found in the LICENSE file.
// Code generated by gen-services.go; DO NOT EDIT.
package payroll

import (
	"context"

	"github.com/mcnijman/go-exactonline/api"
	"github.com/mcnijman/go-exactonline/types"
)

// EmploymentTaxAuthoritiesGeneralEndpoint is responsible for communicating with
// the EmploymentTaxAuthoritiesGeneral endpoint of the Payroll service.
type EmploymentTaxAuthoritiesGeneralEndpoint service

// EmploymentTaxAuthoritiesGeneral:
// Service: Payroll
// Entity: EmploymentTaxAuthoritiesGeneral
// URL: /api/v1/{division}/payroll/EmploymentTaxAuthoritiesGeneral
// HasWebhook: false
// IsInBeta: false
// Methods: GET
// Endpoint docs: https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=PayrollEmploymentTaxAuthoritiesGeneral
type EmploymentTaxAuthoritiesGeneral struct {
	MetaData *api.MetaData `json:"__metadata,omitempty"`
	// ID: Edm.Guid
	ID *types.GUID `json:"ID,omitempty"`

	// Account: Edm.Guid
	Account *types.GUID `json:"Account,omitempty"`

	// Created: Edm.DateTime
	Created *types.Date `json:"Created,omitempty"`

	// Creator: Edm.Guid
	Creator *types.GUID `json:"Creator,omitempty"`

	// CreatorFullName: Edm.String
	CreatorFullName *string `json:"CreatorFullName,omitempty"`

	// Division: Edm.Int32
	Division *int `json:"Division,omitempty"`

	// Employee: Edm.Guid
	Employee *types.GUID `json:"Employee,omitempty"`

	// EmployeeFullName: Edm.String
	EmployeeFullName *string `json:"EmployeeFullName,omitempty"`

	// EmployeeHID: Edm.Int32
	EmployeeHID *int `json:"EmployeeHID,omitempty"`

	// Employment: Edm.Guid
	Employment *types.GUID `json:"Employment,omitempty"`

	// EmploymentHID: Edm.Int32
	EmploymentHID *int `json:"EmploymentHID,omitempty"`

	// EndDate: Edm.DateTime
	EndDate *types.Date `json:"EndDate,omitempty"`

	// InfluenceInsuranceObligation: Edm.String
	InfluenceInsuranceObligation *string `json:"InfluenceInsuranceObligation,omitempty"`

	// InfluenceInsuranceObligationDescription: Edm.String
	InfluenceInsuranceObligationDescription *string `json:"InfluenceInsuranceObligationDescription,omitempty"`

	// Modified: Edm.DateTime
	Modified *types.Date `json:"Modified,omitempty"`

	// Modifier: Edm.Guid
	Modifier *types.GUID `json:"Modifier,omitempty"`

	// ModifierFullName: Edm.String
	ModifierFullName *string `json:"ModifierFullName,omitempty"`

	// NatureOfWorkRelationship: Edm.String
	NatureOfWorkRelationship *string `json:"NatureOfWorkRelationship,omitempty"`

	// NatureOfWorkRelationshipDescription: Edm.String
	NatureOfWorkRelationshipDescription *string `json:"NatureOfWorkRelationshipDescription,omitempty"`

	// PayrollTaxesNumber: Edm.String
	PayrollTaxesNumber *string `json:"PayrollTaxesNumber,omitempty"`

	// StartDate: Edm.DateTime
	StartDate *types.Date `json:"StartDate,omitempty"`

	// TypeOfIncome: Edm.String
	TypeOfIncome *string `json:"TypeOfIncome,omitempty"`

	// TypeOfIncomeDescription: Edm.String
	TypeOfIncomeDescription *string `json:"TypeOfIncomeDescription,omitempty"`
}

func (e *EmploymentTaxAuthoritiesGeneral) GetPrimary() *types.GUID {
	return e.ID
}

func (s *EmploymentTaxAuthoritiesGeneralEndpoint) UserHasRights(ctx context.Context, division int, method string) (bool, error) {
	return s.client.UserHasRights(ctx, division, "payroll/EmploymentTaxAuthoritiesGeneral", method)
}

// List the EmploymentTaxAuthoritiesGeneral entities in the provided division.
// If all is true, all the paginated results are fetched; if false, list the first page.
func (s *EmploymentTaxAuthoritiesGeneralEndpoint) List(ctx context.Context, division int, all bool, o *api.ListOptions) ([]*EmploymentTaxAuthoritiesGeneral, error) {
	var entities []*EmploymentTaxAuthoritiesGeneral
	u, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/payroll/EmploymentTaxAuthoritiesGeneral", division) // #nosec
	api.AddListOptionsToURL(u, o)

	if all {
		err := s.client.ListRequestAndDoAll(ctx, u.String(), &entities)
		return entities, err
	}
	_, _, err := s.client.NewRequestAndDo(ctx, "GET", u.String(), nil, &entities)
	return entities, err
}

// Get the EmploymentTaxAuthoritiesGeneral entitiy in the provided division.
func (s *EmploymentTaxAuthoritiesGeneralEndpoint) Get(ctx context.Context, division int, id *types.GUID) (*EmploymentTaxAuthoritiesGeneral, error) {
	b, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/payroll/EmploymentTaxAuthoritiesGeneral", division) // #nosec
	u, err := api.AddOdataKeyToURL(b, id)
	if err != nil {
		return nil, err
	}

	e := &EmploymentTaxAuthoritiesGeneral{}
	_, _, requestError := s.client.NewRequestAndDo(ctx, "GET", u.String(), nil, e)
	return e, requestError
}
