// Copyright 2024 The go-exactonline AUTHORS. All rights reserved.
//
// Use of this source code is governed by a MIT
// license that can be found in the LICENSE file.
// Code generated by gen-services.go; DO NOT EDIT.
package payroll

import (
	"context"

	"github.com/mcnijman/go-exactonline/api"
	"github.com/mcnijman/go-exactonline/types"
)

// EmploymentOrganizationsEndpoint is responsible for communicating with
// the EmploymentOrganizations endpoint of the Payroll service.
type EmploymentOrganizationsEndpoint service

// EmploymentOrganizations:
// Service: Payroll
// Entity: EmploymentOrganizations
// URL: /api/v1/{division}/payroll/EmploymentOrganizations
// HasWebhook: false
// IsInBeta: false
// Methods: GET
// Endpoint docs: https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=PayrollEmploymentOrganizations
type EmploymentOrganizations struct {
	MetaData *api.MetaData `json:"__metadata,omitempty"`
	// ID: Edm.Guid
	ID *types.GUID `json:"ID,omitempty"`

	// CostCenter: Edm.String
	CostCenter *string `json:"CostCenter,omitempty"`

	// CostCenterDescription: Edm.String
	CostCenterDescription *string `json:"CostCenterDescription,omitempty"`

	// CostUnit: Edm.String
	CostUnit *string `json:"CostUnit,omitempty"`

	// CostUnitDescription: Edm.String
	CostUnitDescription *string `json:"CostUnitDescription,omitempty"`

	// Created: Edm.DateTime
	Created *types.Date `json:"Created,omitempty"`

	// Creator: Edm.Guid
	Creator *types.GUID `json:"Creator,omitempty"`

	// CreatorFullName: Edm.String
	CreatorFullName *string `json:"CreatorFullName,omitempty"`

	// Department: Edm.Guid
	Department *types.GUID `json:"Department,omitempty"`

	// DepartmentCode: Edm.String
	DepartmentCode *string `json:"DepartmentCode,omitempty"`

	// DepartmentDescription: Edm.String
	DepartmentDescription *string `json:"DepartmentDescription,omitempty"`

	// Division: Edm.Int32
	Division *int `json:"Division,omitempty"`

	// Employee: Edm.Guid
	Employee *types.GUID `json:"Employee,omitempty"`

	// EmployeeFullName: Edm.String
	EmployeeFullName *string `json:"EmployeeFullName,omitempty"`

	// EmployeeHID: Edm.Int32
	EmployeeHID *int `json:"EmployeeHID,omitempty"`

	// Employment: Edm.Guid
	Employment *types.GUID `json:"Employment,omitempty"`

	// EmploymentHID: Edm.Int32
	EmploymentHID *int `json:"EmploymentHID,omitempty"`

	// EndDate: Edm.DateTime
	EndDate *types.Date `json:"EndDate,omitempty"`

	// JobTitle: Edm.Guid
	JobTitle *types.GUID `json:"JobTitle,omitempty"`

	// JobTitleCode: Edm.String
	JobTitleCode *string `json:"JobTitleCode,omitempty"`

	// JobTitleDescription: Edm.String
	JobTitleDescription *string `json:"JobTitleDescription,omitempty"`

	// Modified: Edm.DateTime
	Modified *types.Date `json:"Modified,omitempty"`

	// Modifier: Edm.Guid
	Modifier *types.GUID `json:"Modifier,omitempty"`

	// ModifierFullName: Edm.String
	ModifierFullName *string `json:"ModifierFullName,omitempty"`

	// Notes: Edm.String
	Notes *string `json:"Notes,omitempty"`

	// StartDate: Edm.DateTime
	StartDate *types.Date `json:"StartDate,omitempty"`
}

func (e *EmploymentOrganizations) GetPrimary() *types.GUID {
	return e.ID
}

func (s *EmploymentOrganizationsEndpoint) UserHasRights(ctx context.Context, division int, method string) (bool, error) {
	return s.client.UserHasRights(ctx, division, "payroll/EmploymentOrganizations", method)
}

// List the EmploymentOrganizations entities in the provided division.
// If all is true, all the paginated results are fetched; if false, list the first page.
func (s *EmploymentOrganizationsEndpoint) List(ctx context.Context, division int, all bool, o *api.ListOptions) ([]*EmploymentOrganizations, error) {
	var entities []*EmploymentOrganizations
	u, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/payroll/EmploymentOrganizations", division) // #nosec
	api.AddListOptionsToURL(u, o)

	if all {
		err := s.client.ListRequestAndDoAll(ctx, u.String(), &entities)
		return entities, err
	}
	_, _, err := s.client.NewRequestAndDo(ctx, "GET", u.String(), nil, &entities)
	return entities, err
}

// Get the EmploymentOrganizations entitiy in the provided division.
func (s *EmploymentOrganizationsEndpoint) Get(ctx context.Context, division int, id *types.GUID) (*EmploymentOrganizations, error) {
	b, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/payroll/EmploymentOrganizations", division) // #nosec
	u, err := api.AddOdataKeyToURL(b, id)
	if err != nil {
		return nil, err
	}

	e := &EmploymentOrganizations{}
	_, _, requestError := s.client.NewRequestAndDo(ctx, "GET", u.String(), nil, e)
	return e, requestError
}
