// Copyright 2024 The go-exactonline AUTHORS. All rights reserved.
//
// Use of this source code is governed by a MIT
// license that can be found in the LICENSE file.
// Code generated by gen-services.go; DO NOT EDIT.
package payroll

import (
	"context"

	"github.com/mcnijman/go-exactonline/api"
	"github.com/mcnijman/go-exactonline/types"
)

// EmployeesEndpoint is responsible for communicating with
// the Employees endpoint of the Payroll service.
type EmployeesEndpoint service

// Employees:
// Service: Payroll
// Entity: Employees
// URL: /api/v1/{division}/payroll/Employees
// HasWebhook: false
// IsInBeta: false
// Methods: GET
// Endpoint docs: https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=PayrollEmployees
type Employees struct {
	MetaData *api.MetaData `json:"__metadata,omitempty"`
	// ID: Edm.Guid
	ID *types.GUID `json:"ID,omitempty"`

	// ActiveEmployment: Edm.Byte
	ActiveEmployment *byte `json:"ActiveEmployment,omitempty"`

	// AddressLine2: Edm.String
	AddressLine2 *string `json:"AddressLine2,omitempty"`

	// AddressLine3: Edm.String
	AddressLine3 *string `json:"AddressLine3,omitempty"`

	// AddressStreet: Edm.String
	AddressStreet *string `json:"AddressStreet,omitempty"`

	// AddressStreetNumber: Edm.String
	AddressStreetNumber *string `json:"AddressStreetNumber,omitempty"`

	// AddressStreetNumberSuffix: Edm.String
	AddressStreetNumberSuffix *string `json:"AddressStreetNumberSuffix,omitempty"`

	// BirthDate: Edm.DateTime
	BirthDate *types.Date `json:"BirthDate,omitempty"`

	// BirthName: Edm.String
	BirthName *string `json:"BirthName,omitempty"`

	// BirthNamePrefix: Edm.String
	BirthNamePrefix *string `json:"BirthNamePrefix,omitempty"`

	// BirthPlace: Edm.String
	BirthPlace *string `json:"BirthPlace,omitempty"`

	// BusinessEmail: Edm.String
	BusinessEmail *string `json:"BusinessEmail,omitempty"`

	// BusinessFax: Edm.String
	BusinessFax *string `json:"BusinessFax,omitempty"`

	// BusinessMobile: Edm.String
	BusinessMobile *string `json:"BusinessMobile,omitempty"`

	// BusinessPhone: Edm.String
	BusinessPhone *string `json:"BusinessPhone,omitempty"`

	// BusinessPhoneExtension: Edm.String
	BusinessPhoneExtension *string `json:"BusinessPhoneExtension,omitempty"`

	// CASONumber: Edm.String
	CASONumber *string `json:"CASONumber,omitempty"`

	// City: Edm.String
	City *string `json:"City,omitempty"`

	// Code: Edm.String
	Code *string `json:"Code,omitempty"`

	// Country: Edm.String
	Country *string `json:"Country,omitempty"`

	// Created: Edm.DateTime
	Created *types.Date `json:"Created,omitempty"`

	// Creator: Edm.Guid
	Creator *types.GUID `json:"Creator,omitempty"`

	// CreatorFullName: Edm.String
	CreatorFullName *string `json:"CreatorFullName,omitempty"`

	// Customer: Edm.Guid
	Customer *types.GUID `json:"Customer,omitempty"`

	// Division: Edm.Int32
	Division *int `json:"Division,omitempty"`

	// Email: Edm.String
	Email *string `json:"Email,omitempty"`

	// EmployeeHID: Edm.Int32
	EmployeeHID *int `json:"EmployeeHID,omitempty"`

	// EndDate: Edm.DateTime
	EndDate *types.Date `json:"EndDate,omitempty"`

	// FirstName: Edm.String
	FirstName *string `json:"FirstName,omitempty"`

	// FullName: Edm.String
	FullName *string `json:"FullName,omitempty"`

	// Gender: Edm.String
	Gender *string `json:"Gender,omitempty"`

	// HID: Edm.Int32
	HID *int `json:"HID,omitempty"`

	// Initials: Edm.String
	Initials *string `json:"Initials,omitempty"`

	// IsActive: Edm.Boolean
	IsActive *bool `json:"IsActive,omitempty"`

	// IsAnonymised: Edm.Byte
	IsAnonymised *byte `json:"IsAnonymised,omitempty"`

	// Language: Edm.String
	Language *string `json:"Language,omitempty"`

	// LastName: Edm.String
	LastName *string `json:"LastName,omitempty"`

	// LocationDescription: Edm.String
	LocationDescription *string `json:"LocationDescription,omitempty"`

	// Manager: Edm.Guid
	Manager *types.GUID `json:"Manager,omitempty"`

	// MaritalDate: Edm.DateTime
	MaritalDate *types.Date `json:"MaritalDate,omitempty"`

	// MaritalStatus: Edm.Int16
	MaritalStatus *int `json:"MaritalStatus,omitempty"`

	// MiddleName: Edm.String
	MiddleName *string `json:"MiddleName,omitempty"`

	// Mobile: Edm.String
	Mobile *string `json:"Mobile,omitempty"`

	// Modified: Edm.DateTime
	Modified *types.Date `json:"Modified,omitempty"`

	// Modifier: Edm.Guid
	Modifier *types.GUID `json:"Modifier,omitempty"`

	// ModifierFullName: Edm.String
	ModifierFullName *string `json:"ModifierFullName,omitempty"`

	// Municipality: Edm.String
	Municipality *string `json:"Municipality,omitempty"`

	// NameComposition: Edm.Int16
	NameComposition *int `json:"NameComposition,omitempty"`

	// Nationality: Edm.String
	Nationality *string `json:"Nationality,omitempty"`

	// NickName: Edm.String
	NickName *string `json:"NickName,omitempty"`

	// Notes: Edm.String
	Notes *string `json:"Notes,omitempty"`

	// PartnerName: Edm.String
	PartnerName *string `json:"PartnerName,omitempty"`

	// PartnerNamePrefix: Edm.String
	PartnerNamePrefix *string `json:"PartnerNamePrefix,omitempty"`

	// Person: Edm.Guid
	Person *types.GUID `json:"Person,omitempty"`

	// Phone: Edm.String
	Phone *string `json:"Phone,omitempty"`

	// PhoneExtension: Edm.String
	PhoneExtension *string `json:"PhoneExtension,omitempty"`

	// PictureFileName: Edm.String
	PictureFileName *string `json:"PictureFileName,omitempty"`

	// PictureUrl: Edm.String
	PictureUrl *string `json:"PictureUrl,omitempty"`

	// Postcode: Edm.String
	Postcode *string `json:"Postcode,omitempty"`

	// PrivateEmail: Edm.String
	PrivateEmail *string `json:"PrivateEmail,omitempty"`

	// SocialSecurityNumber: Edm.String
	SocialSecurityNumber *string `json:"SocialSecurityNumber,omitempty"`

	// StartDate: Edm.DateTime
	StartDate *types.Date `json:"StartDate,omitempty"`

	// State: Edm.String
	State *string `json:"State,omitempty"`

	// Title: Edm.String
	Title *string `json:"Title,omitempty"`

	// User: Edm.Guid
	User *types.GUID `json:"User,omitempty"`

	// UserFullName: Edm.String
	UserFullName *string `json:"UserFullName,omitempty"`
}

func (e *Employees) GetPrimary() *types.GUID {
	return e.ID
}

func (s *EmployeesEndpoint) UserHasRights(ctx context.Context, division int, method string) (bool, error) {
	return s.client.UserHasRights(ctx, division, "payroll/Employees", method)
}

// List the Employees entities in the provided division.
// If all is true, all the paginated results are fetched; if false, list the first page.
func (s *EmployeesEndpoint) List(ctx context.Context, division int, all bool, o *api.ListOptions) ([]*Employees, error) {
	var entities []*Employees
	u, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/payroll/Employees", division) // #nosec
	api.AddListOptionsToURL(u, o)

	if all {
		err := s.client.ListRequestAndDoAll(ctx, u.String(), &entities)
		return entities, err
	}
	_, _, err := s.client.NewRequestAndDo(ctx, "GET", u.String(), nil, &entities)
	return entities, err
}

// Get the Employees entitiy in the provided division.
func (s *EmployeesEndpoint) Get(ctx context.Context, division int, id *types.GUID) (*Employees, error) {
	b, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/payroll/Employees", division) // #nosec
	u, err := api.AddOdataKeyToURL(b, id)
	if err != nil {
		return nil, err
	}

	e := &Employees{}
	_, _, requestError := s.client.NewRequestAndDo(ctx, "GET", u.String(), nil, e)
	return e, requestError
}
