// Copyright 2024 The go-exactonline AUTHORS. All rights reserved.
//
// Use of this source code is governed by a MIT
// license that can be found in the LICENSE file.
// Code generated by gen-services.go; DO NOT EDIT.
package payroll

import (
	"context"

	"github.com/mcnijman/go-exactonline/api"
	"github.com/mcnijman/go-exactonline/types"
)

// TaxEmploymentEndFlexCodesEndpoint is responsible for communicating with
// the TaxEmploymentEndFlexCodes endpoint of the Payroll service.
type TaxEmploymentEndFlexCodesEndpoint service

// TaxEmploymentEndFlexCodes:
// Service: Payroll
// Entity: TaxEmploymentEndFlexCodes
// URL: /api/v1/{division}/payroll/TaxEmploymentEndFlexCodes
// HasWebhook: false
// IsInBeta: false
// Methods: GET
// Endpoint docs: https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=PayrollTaxEmploymentEndFlexCodes
type TaxEmploymentEndFlexCodes struct {
	MetaData *api.MetaData `json:"__metadata,omitempty"`
	// ID: Edm.Guid
	ID *types.GUID `json:"ID,omitempty"`

	// Code: Edm.String
	Code *string `json:"Code,omitempty"`

	// Created: Edm.DateTime
	Created *types.Date `json:"Created,omitempty"`

	// Creator: Edm.Guid
	Creator *types.GUID `json:"Creator,omitempty"`

	// CreatorFullName: Edm.String
	CreatorFullName *string `json:"CreatorFullName,omitempty"`

	// Description: Edm.String
	Description *string `json:"Description,omitempty"`

	// EndDate: Edm.DateTime
	EndDate *types.Date `json:"EndDate,omitempty"`

	// Modified: Edm.DateTime
	Modified *types.Date `json:"Modified,omitempty"`

	// Modifier: Edm.Guid
	Modifier *types.GUID `json:"Modifier,omitempty"`

	// ModifierFullName: Edm.String
	ModifierFullName *string `json:"ModifierFullName,omitempty"`

	// StartDate: Edm.DateTime
	StartDate *types.Date `json:"StartDate,omitempty"`
}

func (e *TaxEmploymentEndFlexCodes) GetPrimary() *types.GUID {
	return e.ID
}

func (s *TaxEmploymentEndFlexCodesEndpoint) UserHasRights(ctx context.Context, division int, method string) (bool, error) {
	return s.client.UserHasRights(ctx, division, "payroll/TaxEmploymentEndFlexCodes", method)
}

// List the TaxEmploymentEndFlexCodes entities in the provided division.
// If all is true, all the paginated results are fetched; if false, list the first page.
func (s *TaxEmploymentEndFlexCodesEndpoint) List(ctx context.Context, division int, all bool, o *api.ListOptions) ([]*TaxEmploymentEndFlexCodes, error) {
	var entities []*TaxEmploymentEndFlexCodes
	u, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/payroll/TaxEmploymentEndFlexCodes", division) // #nosec
	api.AddListOptionsToURL(u, o)

	if all {
		err := s.client.ListRequestAndDoAll(ctx, u.String(), &entities)
		return entities, err
	}
	_, _, err := s.client.NewRequestAndDo(ctx, "GET", u.String(), nil, &entities)
	return entities, err
}

// Get the TaxEmploymentEndFlexCodes entitiy in the provided division.
func (s *TaxEmploymentEndFlexCodesEndpoint) Get(ctx context.Context, division int, id *types.GUID) (*TaxEmploymentEndFlexCodes, error) {
	b, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/payroll/TaxEmploymentEndFlexCodes", division) // #nosec
	u, err := api.AddOdataKeyToURL(b, id)
	if err != nil {
		return nil, err
	}

	e := &TaxEmploymentEndFlexCodes{}
	_, _, requestError := s.client.NewRequestAndDo(ctx, "GET", u.String(), nil, e)
	return e, requestError
}
