// Copyright 2024 The go-exactonline AUTHORS. All rights reserved.
//
// Use of this source code is governed by a MIT
// license that can be found in the LICENSE file.
// Code generated by gen-services.go; DO NOT EDIT.
package manufacturing

import (
	"context"

	"github.com/mcnijman/go-exactonline/api"
	"github.com/mcnijman/go-exactonline/types"
)

// ByProductReversalsEndpoint is responsible for communicating with
// the ByProductReversals endpoint of the Manufacturing service.
type ByProductReversalsEndpoint service

// ByProductReversals:
// Service: Manufacturing
// Entity: ByProductReversals
// URL: /api/v1/{division}/manufacturing/ByProductReversals
// HasWebhook: false
// IsInBeta: false
// Methods: GET POST
// Endpoint docs: https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=ManufacturingByProductReversals
type ByProductReversals struct {
	MetaData *api.MetaData `json:"__metadata,omitempty"`
	// ReversalStockTransactionId: Edm.Guid
	ReversalStockTransactionId *types.GUID `json:"ReversalStockTransactionId,omitempty"`

	// CreatedBy: Edm.Guid
	CreatedBy *types.GUID `json:"CreatedBy,omitempty"`

	// CreatedByFullName: Edm.String
	CreatedByFullName *string `json:"CreatedByFullName,omitempty"`

	// CreatedDate: Edm.DateTime
	CreatedDate *types.Date `json:"CreatedDate,omitempty"`

	// IsBackflush: Edm.Boolean
	IsBackflush *bool `json:"IsBackflush,omitempty"`

	// IsBatch: Edm.Byte
	IsBatch *byte `json:"IsBatch,omitempty"`

	// IsFractionAllowedItem: Edm.Byte
	IsFractionAllowedItem *byte `json:"IsFractionAllowedItem,omitempty"`

	// IsSerial: Edm.Byte
	IsSerial *byte `json:"IsSerial,omitempty"`

	// Item: Edm.Guid
	Item *types.GUID `json:"Item,omitempty"`

	// ItemCode: Edm.String
	ItemCode *string `json:"ItemCode,omitempty"`

	// ItemDescription: Edm.String
	ItemDescription *string `json:"ItemDescription,omitempty"`

	// ItemPictureUrl: Edm.String
	ItemPictureUrl *string `json:"ItemPictureUrl,omitempty"`

	// Note: Edm.String
	Note *string `json:"Note,omitempty"`

	// OriginalStockTransactionId: Edm.Guid
	OriginalStockTransactionId *types.GUID `json:"OriginalStockTransactionId,omitempty"`

	// Quantity: Edm.Double
	Quantity *float64 `json:"Quantity,omitempty"`

	// ShopOrder: Edm.Guid
	ShopOrder *types.GUID `json:"ShopOrder,omitempty"`

	// ShopOrderMaterialPlan: Edm.Guid
	ShopOrderMaterialPlan *types.GUID `json:"ShopOrderMaterialPlan,omitempty"`

	// ShopOrderNumber: Edm.Int32
	ShopOrderNumber *int `json:"ShopOrderNumber,omitempty"`

	// StorageLocation: Edm.Guid
	StorageLocation *types.GUID `json:"StorageLocation,omitempty"`

	// StorageLocationCode: Edm.String
	StorageLocationCode *string `json:"StorageLocationCode,omitempty"`

	// StorageLocationDescription: Edm.String
	StorageLocationDescription *string `json:"StorageLocationDescription,omitempty"`

	// TransactionDate: Edm.DateTime
	TransactionDate *types.Date `json:"TransactionDate,omitempty"`

	// Unit: Edm.String
	Unit *string `json:"Unit,omitempty"`

	// UnitDescription: Edm.String
	UnitDescription *string `json:"UnitDescription,omitempty"`

	// Warehouse: Edm.Guid
	Warehouse *types.GUID `json:"Warehouse,omitempty"`

	// WarehouseCode: Edm.String
	WarehouseCode *string `json:"WarehouseCode,omitempty"`

	// WarehouseDescription: Edm.String
	WarehouseDescription *string `json:"WarehouseDescription,omitempty"`
}

func (e *ByProductReversals) GetPrimary() *types.GUID {
	return e.ReversalStockTransactionId
}

func (s *ByProductReversalsEndpoint) UserHasRights(ctx context.Context, division int, method string) (bool, error) {
	return s.client.UserHasRights(ctx, division, "manufacturing/ByProductReversals", method)
}

// List the ByProductReversals entities in the provided division.
// If all is true, all the paginated results are fetched; if false, list the first page.
func (s *ByProductReversalsEndpoint) List(ctx context.Context, division int, all bool, o *api.ListOptions) ([]*ByProductReversals, error) {
	var entities []*ByProductReversals
	u, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/manufacturing/ByProductReversals", division) // #nosec
	api.AddListOptionsToURL(u, o)

	if all {
		err := s.client.ListRequestAndDoAll(ctx, u.String(), &entities)
		return entities, err
	}
	_, _, err := s.client.NewRequestAndDo(ctx, "GET", u.String(), nil, &entities)
	return entities, err
}

// Get the ByProductReversals entitiy in the provided division.
func (s *ByProductReversalsEndpoint) Get(ctx context.Context, division int, id *types.GUID) (*ByProductReversals, error) {
	b, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/manufacturing/ByProductReversals", division) // #nosec
	u, err := api.AddOdataKeyToURL(b, id)
	if err != nil {
		return nil, err
	}

	e := &ByProductReversals{}
	_, _, requestError := s.client.NewRequestAndDo(ctx, "GET", u.String(), nil, e)
	return e, requestError
}

// New returns an empty ByProductReversals entity
func (s *ByProductReversalsEndpoint) New() *ByProductReversals {
	return &ByProductReversals{}
}

// Create the ByProductReversals entity in the provided division.
func (s *ByProductReversalsEndpoint) Create(ctx context.Context, division int, entity *ByProductReversals) (*ByProductReversals, error) {
	u, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/manufacturing/ByProductReversals", division) // #nosec
	e := &ByProductReversals{}
	_, _, err := s.client.NewRequestAndDo(ctx, "POST", u.String(), entity, e)
	if err != nil {
		return nil, err
	}
	return e, nil
}
