// Copyright 2024 The go-exactonline AUTHORS. All rights reserved.
//
// Use of this source code is governed by a MIT
// license that can be found in the LICENSE file.
// Code generated by gen-services.go; DO NOT EDIT.
package manufacturing

import (
	"context"
	"fmt"
	"io/ioutil"
	"net/http"

	"github.com/mcnijman/go-exactonline/api"
	"github.com/mcnijman/go-exactonline/types"
)

// OperationsEndpoint is responsible for communicating with
// the Operations endpoint of the Manufacturing service.
type OperationsEndpoint service

// Operations:
// Service: Manufacturing
// Entity: Operations
// URL: /api/v1/{division}/manufacturing/Operations
// HasWebhook: false
// IsInBeta: false
// Methods: GET POST PUT DELETE
// Endpoint docs: https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=ManufacturingOperations
type Operations struct {
	MetaData *api.MetaData `json:"__metadata,omitempty"`
	// ID: Edm.Guid
	ID *types.GUID `json:"ID,omitempty"`

	// Code: Edm.String
	Code *string `json:"Code,omitempty"`

	// Created: Edm.DateTime
	Created *types.Date `json:"Created,omitempty"`

	// Creator: Edm.Guid
	Creator *types.GUID `json:"Creator,omitempty"`

	// CreatorFullName: Edm.String
	CreatorFullName *string `json:"CreatorFullName,omitempty"`

	// Description: Edm.String
	Description *string `json:"Description,omitempty"`

	// Division: Edm.Int32
	Division *int `json:"Division,omitempty"`

	// HasSuppliers: Edm.Byte
	HasSuppliers *byte `json:"HasSuppliers,omitempty"`

	// Item: Edm.Guid
	Item *types.GUID `json:"Item,omitempty"`

	// ItemDescription: Edm.String
	ItemDescription *string `json:"ItemDescription,omitempty"`

	// Modified: Edm.DateTime
	Modified *types.Date `json:"Modified,omitempty"`

	// Modifier: Edm.Guid
	Modifier *types.GUID `json:"Modifier,omitempty"`

	// ModifierFullName: Edm.String
	ModifierFullName *string `json:"ModifierFullName,omitempty"`

	// Notes: Edm.String
	Notes *string `json:"Notes,omitempty"`

	// Searchcode: Edm.String
	Searchcode *string `json:"Searchcode,omitempty"`

	// Status: Edm.Int32
	Status *int `json:"Status,omitempty"`
}

func (e *Operations) GetPrimary() *types.GUID {
	return e.ID
}

func (s *OperationsEndpoint) UserHasRights(ctx context.Context, division int, method string) (bool, error) {
	return s.client.UserHasRights(ctx, division, "manufacturing/Operations", method)
}

// List the Operations entities in the provided division.
// If all is true, all the paginated results are fetched; if false, list the first page.
func (s *OperationsEndpoint) List(ctx context.Context, division int, all bool, o *api.ListOptions) ([]*Operations, error) {
	var entities []*Operations
	u, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/manufacturing/Operations", division) // #nosec
	api.AddListOptionsToURL(u, o)

	if all {
		err := s.client.ListRequestAndDoAll(ctx, u.String(), &entities)
		return entities, err
	}
	_, _, err := s.client.NewRequestAndDo(ctx, "GET", u.String(), nil, &entities)
	return entities, err
}

// Get the Operations entitiy in the provided division.
func (s *OperationsEndpoint) Get(ctx context.Context, division int, id *types.GUID) (*Operations, error) {
	b, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/manufacturing/Operations", division) // #nosec
	u, err := api.AddOdataKeyToURL(b, id)
	if err != nil {
		return nil, err
	}

	e := &Operations{}
	_, _, requestError := s.client.NewRequestAndDo(ctx, "GET", u.String(), nil, e)
	return e, requestError
}

// New returns an empty Operations entity
func (s *OperationsEndpoint) New() *Operations {
	return &Operations{}
}

// Create the Operations entity in the provided division.
func (s *OperationsEndpoint) Create(ctx context.Context, division int, entity *Operations) (*Operations, error) {
	u, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/manufacturing/Operations", division) // #nosec
	e := &Operations{}
	_, _, err := s.client.NewRequestAndDo(ctx, "POST", u.String(), entity, e)
	if err != nil {
		return nil, err
	}
	return e, nil
}

// Update the Operations entity in the provided division.
func (s *OperationsEndpoint) Update(ctx context.Context, division int, entity *Operations) (*Operations, error) {
	b, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/manufacturing/Operations", division) // #nosec
	u, err := api.AddOdataKeyToURL(b, entity.GetPrimary())
	if err != nil {
		return nil, err
	}

	e := &Operations{}
	_, _, requestError := s.client.NewRequestAndDo(ctx, "PUT", u.String(), entity, e)
	return e, requestError
}

// Delete the Operations entity in the provided division.
func (s *OperationsEndpoint) Delete(ctx context.Context, division int, id *types.GUID) error {
	b, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/manufacturing/Operations", division) // #nosec
	u, err := api.AddOdataKeyToURL(b, id)
	if err != nil {
		return err
	}

	_, r, requestError := s.client.NewRequestAndDo(ctx, "DELETE", u.String(), nil, nil)
	if requestError != nil {
		return requestError
	}

	if r.StatusCode != http.StatusNoContent {
		body, _ := ioutil.ReadAll(r.Body) // #nosec
		return fmt.Errorf("Failed with status %v and body %v", r.StatusCode, body)
	}

	return nil
}
