// Copyright 2024 The go-exactonline AUTHORS. All rights reserved.
//
// Use of this source code is governed by a MIT
// license that can be found in the LICENSE file.
// Code generated by gen-services.go; DO NOT EDIT.
package manufacturing

import (
	"context"

	"github.com/mcnijman/go-exactonline/api"
	"github.com/mcnijman/go-exactonline/types"
)

// SubOrderReceiptsEndpoint is responsible for communicating with
// the SubOrderReceipts endpoint of the Manufacturing service.
type SubOrderReceiptsEndpoint service

// SubOrderReceipts:
// Service: Manufacturing
// Entity: SubOrderReceipts
// URL: /api/v1/{division}/manufacturing/SubOrderReceipts
// HasWebhook: false
// IsInBeta: false
// Methods: GET POST
// Endpoint docs: https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=ManufacturingSubOrderReceipts
type SubOrderReceipts struct {
	MetaData *api.MetaData `json:"__metadata,omitempty"`
	// ShopOrderReceiptStockTransactionId: Edm.Guid
	ShopOrderReceiptStockTransactionId *types.GUID `json:"ShopOrderReceiptStockTransactionId,omitempty"`

	// CreatedBy: Edm.Guid
	CreatedBy *types.GUID `json:"CreatedBy,omitempty"`

	// CreatedByFullName: Edm.String
	CreatedByFullName *string `json:"CreatedByFullName,omitempty"`

	// CreatedDate: Edm.DateTime
	CreatedDate *types.Date `json:"CreatedDate,omitempty"`

	// DraftStockTransactionID: Edm.Guid
	DraftStockTransactionID *types.GUID `json:"DraftStockTransactionID,omitempty"`

	// HasReversibleQuantity: Edm.Boolean
	HasReversibleQuantity *bool `json:"HasReversibleQuantity,omitempty"`

	// IsBatch: Edm.Byte
	IsBatch *byte `json:"IsBatch,omitempty"`

	// IsFractionAllowedItem: Edm.Byte
	IsFractionAllowedItem *byte `json:"IsFractionAllowedItem,omitempty"`

	// IsSerial: Edm.Byte
	IsSerial *byte `json:"IsSerial,omitempty"`

	// Item: Edm.Guid
	Item *types.GUID `json:"Item,omitempty"`

	// ItemCode: Edm.String
	ItemCode *string `json:"ItemCode,omitempty"`

	// ItemDescription: Edm.String
	ItemDescription *string `json:"ItemDescription,omitempty"`

	// ItemPictureUrl: Edm.String
	ItemPictureUrl *string `json:"ItemPictureUrl,omitempty"`

	// MaterialIssueStockTransactionId: Edm.Guid
	MaterialIssueStockTransactionId *types.GUID `json:"MaterialIssueStockTransactionId,omitempty"`

	// ParentShopOrder: Edm.Guid
	ParentShopOrder *types.GUID `json:"ParentShopOrder,omitempty"`

	// ParentShopOrderMaterialPlan: Edm.Guid
	ParentShopOrderMaterialPlan *types.GUID `json:"ParentShopOrderMaterialPlan,omitempty"`

	// ParentShopOrderNumber: Edm.Int32
	ParentShopOrderNumber *int `json:"ParentShopOrderNumber,omitempty"`

	// Quantity: Edm.Double
	Quantity *float64 `json:"Quantity,omitempty"`

	// SubShopOrder: Edm.Guid
	SubShopOrder *types.GUID `json:"SubShopOrder,omitempty"`

	// SubShopOrderNumber: Edm.Int32
	SubShopOrderNumber *int `json:"SubShopOrderNumber,omitempty"`

	// TransactionDate: Edm.DateTime
	TransactionDate *types.Date `json:"TransactionDate,omitempty"`

	// Unit: Edm.String
	Unit *string `json:"Unit,omitempty"`

	// UnitDescription: Edm.String
	UnitDescription *string `json:"UnitDescription,omitempty"`

	// Warehouse: Edm.Guid
	Warehouse *types.GUID `json:"Warehouse,omitempty"`

	// WarehouseCode: Edm.String
	WarehouseCode *string `json:"WarehouseCode,omitempty"`

	// WarehouseDescription: Edm.String
	WarehouseDescription *string `json:"WarehouseDescription,omitempty"`
}

func (e *SubOrderReceipts) GetPrimary() *types.GUID {
	return e.ShopOrderReceiptStockTransactionId
}

func (s *SubOrderReceiptsEndpoint) UserHasRights(ctx context.Context, division int, method string) (bool, error) {
	return s.client.UserHasRights(ctx, division, "manufacturing/SubOrderReceipts", method)
}

// List the SubOrderReceipts entities in the provided division.
// If all is true, all the paginated results are fetched; if false, list the first page.
func (s *SubOrderReceiptsEndpoint) List(ctx context.Context, division int, all bool, o *api.ListOptions) ([]*SubOrderReceipts, error) {
	var entities []*SubOrderReceipts
	u, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/manufacturing/SubOrderReceipts", division) // #nosec
	api.AddListOptionsToURL(u, o)

	if all {
		err := s.client.ListRequestAndDoAll(ctx, u.String(), &entities)
		return entities, err
	}
	_, _, err := s.client.NewRequestAndDo(ctx, "GET", u.String(), nil, &entities)
	return entities, err
}

// Get the SubOrderReceipts entitiy in the provided division.
func (s *SubOrderReceiptsEndpoint) Get(ctx context.Context, division int, id *types.GUID) (*SubOrderReceipts, error) {
	b, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/manufacturing/SubOrderReceipts", division) // #nosec
	u, err := api.AddOdataKeyToURL(b, id)
	if err != nil {
		return nil, err
	}

	e := &SubOrderReceipts{}
	_, _, requestError := s.client.NewRequestAndDo(ctx, "GET", u.String(), nil, e)
	return e, requestError
}

// New returns an empty SubOrderReceipts entity
func (s *SubOrderReceiptsEndpoint) New() *SubOrderReceipts {
	return &SubOrderReceipts{}
}

// Create the SubOrderReceipts entity in the provided division.
func (s *SubOrderReceiptsEndpoint) Create(ctx context.Context, division int, entity *SubOrderReceipts) (*SubOrderReceipts, error) {
	u, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/manufacturing/SubOrderReceipts", division) // #nosec
	e := &SubOrderReceipts{}
	_, _, err := s.client.NewRequestAndDo(ctx, "POST", u.String(), entity, e)
	if err != nil {
		return nil, err
	}
	return e, nil
}
