// Copyright 2024 The go-exactonline AUTHORS. All rights reserved.
//
// Use of this source code is governed by a MIT
// license that can be found in the LICENSE file.
// Code generated by gen-services.go; DO NOT EDIT.
package hrm

import (
	"context"

	"github.com/mcnijman/go-exactonline/api"
	"github.com/mcnijman/go-exactonline/types"
)

// DivisionClassesEndpoint is responsible for communicating with
// the DivisionClasses endpoint of the HRM service.
type DivisionClassesEndpoint service

// DivisionClasses:
// Service: HRM
// Entity: DivisionClasses
// URL: /api/v1/{division}/hrm/DivisionClasses
// HasWebhook: false
// IsInBeta: false
// Methods: GET
// Endpoint docs: https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=HRMDivisionClasses
type DivisionClasses struct {
	MetaData *api.MetaData `json:"__metadata,omitempty"`
	// ID: Edm.Guid
	ID *types.GUID `json:"ID,omitempty"`

	// ClassNameCustomer: Edm.Guid
	ClassNameCustomer *types.GUID `json:"ClassNameCustomer,omitempty"`

	// ClassNameDescription: Edm.String
	ClassNameDescription *string `json:"ClassNameDescription,omitempty"`

	// ClassNameID: Edm.Guid
	ClassNameID *types.GUID `json:"ClassNameID,omitempty"`

	// Code: Edm.String
	Code *string `json:"Code,omitempty"`

	// Created: Edm.DateTime
	Created *types.Date `json:"Created,omitempty"`

	// Creator: Edm.Guid
	Creator *types.GUID `json:"Creator,omitempty"`

	// CreatorFullName: Edm.String
	CreatorFullName *string `json:"CreatorFullName,omitempty"`

	// Description: Edm.String
	Description *string `json:"Description,omitempty"`

	// DescriptionTermID: Edm.Int32
	DescriptionTermID *int `json:"DescriptionTermID,omitempty"`

	// Modified: Edm.DateTime
	Modified *types.Date `json:"Modified,omitempty"`

	// Modifier: Edm.Guid
	Modifier *types.GUID `json:"Modifier,omitempty"`

	// ModifierFullName: Edm.String
	ModifierFullName *string `json:"ModifierFullName,omitempty"`

	// SequenceNr: Edm.Int32
	SequenceNr *int `json:"SequenceNr,omitempty"`
}

func (e *DivisionClasses) GetPrimary() *types.GUID {
	return e.ID
}

func (s *DivisionClassesEndpoint) UserHasRights(ctx context.Context, division int, method string) (bool, error) {
	return s.client.UserHasRights(ctx, division, "hrm/DivisionClasses", method)
}

// List the DivisionClasses entities in the provided division.
// If all is true, all the paginated results are fetched; if false, list the first page.
func (s *DivisionClassesEndpoint) List(ctx context.Context, division int, all bool, o *api.ListOptions) ([]*DivisionClasses, error) {
	var entities []*DivisionClasses
	u, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/hrm/DivisionClasses", division) // #nosec
	api.AddListOptionsToURL(u, o)

	if all {
		err := s.client.ListRequestAndDoAll(ctx, u.String(), &entities)
		return entities, err
	}
	_, _, err := s.client.NewRequestAndDo(ctx, "GET", u.String(), nil, &entities)
	return entities, err
}

// Get the DivisionClasses entitiy in the provided division.
func (s *DivisionClassesEndpoint) Get(ctx context.Context, division int, id *types.GUID) (*DivisionClasses, error) {
	b, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/hrm/DivisionClasses", division) // #nosec
	u, err := api.AddOdataKeyToURL(b, id)
	if err != nil {
		return nil, err
	}

	e := &DivisionClasses{}
	_, _, requestError := s.client.NewRequestAndDo(ctx, "GET", u.String(), nil, e)
	return e, requestError
}
