// Copyright 2024 The go-exactonline AUTHORS. All rights reserved.
//
// Use of this source code is governed by a MIT
// license that can be found in the LICENSE file.
// Code generated by gen-services.go; DO NOT EDIT.
package hrm

import (
	"context"

	"github.com/mcnijman/go-exactonline/api"
	"github.com/mcnijman/go-exactonline/types"
)

// JobTitlesEndpoint is responsible for communicating with
// the JobTitles endpoint of the HRM service.
type JobTitlesEndpoint service

// JobTitles:
// Service: HRM
// Entity: JobTitles
// URL: /api/v1/{division}/hrm/JobTitles
// HasWebhook: false
// IsInBeta: false
// Methods: GET
// Endpoint docs: https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=HRMJobTitles
type JobTitles struct {
	MetaData *api.MetaData `json:"__metadata,omitempty"`
	// ID: Edm.Guid
	ID *types.GUID `json:"ID,omitempty"`

	// Code: Edm.String
	Code *string `json:"Code,omitempty"`

	// Created: Edm.DateTime
	Created *types.Date `json:"Created,omitempty"`

	// Creator: Edm.Guid
	Creator *types.GUID `json:"Creator,omitempty"`

	// CreatorFullName: Edm.String
	CreatorFullName *string `json:"CreatorFullName,omitempty"`

	// Description: Edm.String
	Description *string `json:"Description,omitempty"`

	// Division: Edm.Int32
	Division *int `json:"Division,omitempty"`

	// JobCode: Edm.String
	JobCode *string `json:"JobCode,omitempty"`

	// JobGroup: Edm.Guid
	JobGroup *types.GUID `json:"JobGroup,omitempty"`

	// JobGroupCode: Edm.String
	JobGroupCode *string `json:"JobGroupCode,omitempty"`

	// JobGroupDescription: Edm.String
	JobGroupDescription *string `json:"JobGroupDescription,omitempty"`

	// JobLevelFrom: Edm.Int32
	JobLevelFrom *int `json:"JobLevelFrom,omitempty"`

	// JobLevelTo: Edm.Int32
	JobLevelTo *int `json:"JobLevelTo,omitempty"`

	// Modified: Edm.DateTime
	Modified *types.Date `json:"Modified,omitempty"`

	// Modifier: Edm.Guid
	Modifier *types.GUID `json:"Modifier,omitempty"`

	// ModifierFullName: Edm.String
	ModifierFullName *string `json:"ModifierFullName,omitempty"`

	// Notes: Edm.String
	Notes *string `json:"Notes,omitempty"`
}

func (e *JobTitles) GetPrimary() *types.GUID {
	return e.ID
}

func (s *JobTitlesEndpoint) UserHasRights(ctx context.Context, division int, method string) (bool, error) {
	return s.client.UserHasRights(ctx, division, "hrm/JobTitles", method)
}

// List the JobTitles entities in the provided division.
// If all is true, all the paginated results are fetched; if false, list the first page.
func (s *JobTitlesEndpoint) List(ctx context.Context, division int, all bool, o *api.ListOptions) ([]*JobTitles, error) {
	var entities []*JobTitles
	u, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/hrm/JobTitles", division) // #nosec
	api.AddListOptionsToURL(u, o)

	if all {
		err := s.client.ListRequestAndDoAll(ctx, u.String(), &entities)
		return entities, err
	}
	_, _, err := s.client.NewRequestAndDo(ctx, "GET", u.String(), nil, &entities)
	return entities, err
}

// Get the JobTitles entitiy in the provided division.
func (s *JobTitlesEndpoint) Get(ctx context.Context, division int, id *types.GUID) (*JobTitles, error) {
	b, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/hrm/JobTitles", division) // #nosec
	u, err := api.AddOdataKeyToURL(b, id)
	if err != nil {
		return nil, err
	}

	e := &JobTitles{}
	_, _, requestError := s.client.NewRequestAndDo(ctx, "GET", u.String(), nil, e)
	return e, requestError
}
