// Copyright 2024 The go-exactonline AUTHORS. All rights reserved.
//
// Use of this source code is governed by a MIT
// license that can be found in the LICENSE file.
// Code generated by gen-services.go; DO NOT EDIT.
package hrm

import (
	"context"

	"github.com/mcnijman/go-exactonline/api"
	"github.com/mcnijman/go-exactonline/types"
)

// JobGroupsEndpoint is responsible for communicating with
// the JobGroups endpoint of the HRM service.
type JobGroupsEndpoint service

// JobGroups:
// Service: HRM
// Entity: JobGroups
// URL: /api/v1/{division}/hrm/JobGroups
// HasWebhook: false
// IsInBeta: false
// Methods: GET
// Endpoint docs: https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=HRMJobGroups
type JobGroups struct {
	MetaData *api.MetaData `json:"__metadata,omitempty"`
	// ID: Edm.Guid
	ID *types.GUID `json:"ID,omitempty"`

	// Code: Edm.String
	Code *string `json:"Code,omitempty"`

	// Created: Edm.DateTime
	Created *types.Date `json:"Created,omitempty"`

	// Creator: Edm.Guid
	Creator *types.GUID `json:"Creator,omitempty"`

	// CreatorFullName: Edm.String
	CreatorFullName *string `json:"CreatorFullName,omitempty"`

	// Description: Edm.String
	Description *string `json:"Description,omitempty"`

	// Division: Edm.Int32
	Division *int `json:"Division,omitempty"`

	// Modified: Edm.DateTime
	Modified *types.Date `json:"Modified,omitempty"`

	// Modifier: Edm.Guid
	Modifier *types.GUID `json:"Modifier,omitempty"`

	// ModifierFullName: Edm.String
	ModifierFullName *string `json:"ModifierFullName,omitempty"`

	// Notes: Edm.String
	Notes *string `json:"Notes,omitempty"`
}

func (e *JobGroups) GetPrimary() *types.GUID {
	return e.ID
}

func (s *JobGroupsEndpoint) UserHasRights(ctx context.Context, division int, method string) (bool, error) {
	return s.client.UserHasRights(ctx, division, "hrm/JobGroups", method)
}

// List the JobGroups entities in the provided division.
// If all is true, all the paginated results are fetched; if false, list the first page.
func (s *JobGroupsEndpoint) List(ctx context.Context, division int, all bool, o *api.ListOptions) ([]*JobGroups, error) {
	var entities []*JobGroups
	u, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/hrm/JobGroups", division) // #nosec
	api.AddListOptionsToURL(u, o)

	if all {
		err := s.client.ListRequestAndDoAll(ctx, u.String(), &entities)
		return entities, err
	}
	_, _, err := s.client.NewRequestAndDo(ctx, "GET", u.String(), nil, &entities)
	return entities, err
}

// Get the JobGroups entitiy in the provided division.
func (s *JobGroupsEndpoint) Get(ctx context.Context, division int, id *types.GUID) (*JobGroups, error) {
	b, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/hrm/JobGroups", division) // #nosec
	u, err := api.AddOdataKeyToURL(b, id)
	if err != nil {
		return nil, err
	}

	e := &JobGroups{}
	_, _, requestError := s.client.NewRequestAndDo(ctx, "GET", u.String(), nil, e)
	return e, requestError
}
