// Copyright 2024 The go-exactonline AUTHORS. All rights reserved.
//
// Use of this source code is governed by a MIT
// license that can be found in the LICENSE file.
// Code generated by gen-services.go; DO NOT EDIT.
package hrm

import (
	"context"

	"github.com/mcnijman/go-exactonline/api"
	"github.com/mcnijman/go-exactonline/types"
)

// LeaveRegistrationsEndpoint is responsible for communicating with
// the LeaveRegistrations endpoint of the HRM service.
type LeaveRegistrationsEndpoint service

// LeaveRegistrations:
// Service: HRM
// Entity: LeaveRegistrations
// URL: /api/v1/{division}/hrm/LeaveRegistrations
// HasWebhook: false
// IsInBeta: false
// Methods: GET
// Endpoint docs: https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=HRMLeaveRegistrations
type LeaveRegistrations struct {
	MetaData *api.MetaData `json:"__metadata,omitempty"`
	// ID: Edm.Guid
	ID *types.GUID `json:"ID,omitempty"`

	// Created: Edm.DateTime
	Created *types.Date `json:"Created,omitempty"`

	// Creator: Edm.Guid
	Creator *types.GUID `json:"Creator,omitempty"`

	// CreatorFullName: Edm.String
	CreatorFullName *string `json:"CreatorFullName,omitempty"`

	// Description: Edm.String
	Description *string `json:"Description,omitempty"`

	// Division: Edm.Int32
	Division *int `json:"Division,omitempty"`

	// Employee: Edm.Guid
	Employee *types.GUID `json:"Employee,omitempty"`

	// EmployeeFullName: Edm.String
	EmployeeFullName *string `json:"EmployeeFullName,omitempty"`

	// EmployeeHID: Edm.Int32
	EmployeeHID *int `json:"EmployeeHID,omitempty"`

	// EndDate: Edm.DateTime
	EndDate *types.Date `json:"EndDate,omitempty"`

	// EndTime: Edm.DateTime
	EndTime *types.Date `json:"EndTime,omitempty"`

	// Hours: Edm.Double
	Hours *float64 `json:"Hours,omitempty"`

	// HoursFirstDay: Edm.Double
	HoursFirstDay *float64 `json:"HoursFirstDay,omitempty"`

	// HoursLastDay: Edm.Double
	HoursLastDay *float64 `json:"HoursLastDay,omitempty"`

	// LeaveType: Edm.Guid
	LeaveType *types.GUID `json:"LeaveType,omitempty"`

	// LeaveTypeCode: Edm.String
	LeaveTypeCode *string `json:"LeaveTypeCode,omitempty"`

	// LeaveTypeDescription: Edm.String
	LeaveTypeDescription *string `json:"LeaveTypeDescription,omitempty"`

	// Modified: Edm.DateTime
	Modified *types.Date `json:"Modified,omitempty"`

	// Modifier: Edm.Guid
	Modifier *types.GUID `json:"Modifier,omitempty"`

	// ModifierFullName: Edm.String
	ModifierFullName *string `json:"ModifierFullName,omitempty"`

	// Notes: Edm.String
	Notes *string `json:"Notes,omitempty"`

	// StartDate: Edm.DateTime
	StartDate *types.Date `json:"StartDate,omitempty"`

	// StartTime: Edm.DateTime
	StartTime *types.Date `json:"StartTime,omitempty"`

	// Status: Edm.Int16
	Status *int `json:"Status,omitempty"`
}

func (e *LeaveRegistrations) GetPrimary() *types.GUID {
	return e.ID
}

func (s *LeaveRegistrationsEndpoint) UserHasRights(ctx context.Context, division int, method string) (bool, error) {
	return s.client.UserHasRights(ctx, division, "hrm/LeaveRegistrations", method)
}

// List the LeaveRegistrations entities in the provided division.
// If all is true, all the paginated results are fetched; if false, list the first page.
func (s *LeaveRegistrationsEndpoint) List(ctx context.Context, division int, all bool, o *api.ListOptions) ([]*LeaveRegistrations, error) {
	var entities []*LeaveRegistrations
	u, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/hrm/LeaveRegistrations", division) // #nosec
	api.AddListOptionsToURL(u, o)

	if all {
		err := s.client.ListRequestAndDoAll(ctx, u.String(), &entities)
		return entities, err
	}
	_, _, err := s.client.NewRequestAndDo(ctx, "GET", u.String(), nil, &entities)
	return entities, err
}

// Get the LeaveRegistrations entitiy in the provided division.
func (s *LeaveRegistrationsEndpoint) Get(ctx context.Context, division int, id *types.GUID) (*LeaveRegistrations, error) {
	b, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/hrm/LeaveRegistrations", division) // #nosec
	u, err := api.AddOdataKeyToURL(b, id)
	if err != nil {
		return nil, err
	}

	e := &LeaveRegistrations{}
	_, _, requestError := s.client.NewRequestAndDo(ctx, "GET", u.String(), nil, e)
	return e, requestError
}
