// Copyright 2024 The go-exactonline AUTHORS. All rights reserved.
//
// Use of this source code is governed by a MIT
// license that can be found in the LICENSE file.
// Code generated by gen-services.go; DO NOT EDIT.
package logistics

import (
	"context"

	"github.com/mcnijman/go-exactonline/api"
	"github.com/mcnijman/go-exactonline/types"
)

// ItemVersionsEndpoint is responsible for communicating with
// the ItemVersions endpoint of the Logistics service.
type ItemVersionsEndpoint service

// ItemVersions:
// Service: Logistics
// Entity: ItemVersions
// URL: /api/v1/{division}/logistics/ItemVersions
// HasWebhook: false
// IsInBeta: false
// Methods: GET
// Endpoint docs: https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=LogisticsItemVersions
type ItemVersions struct {
	MetaData *api.MetaData `json:"__metadata,omitempty"`
	// ID: Edm.Guid
	ID *types.GUID `json:"ID,omitempty"`

	// BatchQuantity: Edm.Double
	BatchQuantity *float64 `json:"BatchQuantity,omitempty"`

	// CalculatedCostPrice: Edm.Double
	CalculatedCostPrice *float64 `json:"CalculatedCostPrice,omitempty"`

	// Created: Edm.DateTime
	Created *types.Date `json:"Created,omitempty"`

	// Creator: Edm.Guid
	Creator *types.GUID `json:"Creator,omitempty"`

	// CreatorFullName: Edm.String
	CreatorFullName *string `json:"CreatorFullName,omitempty"`

	// Description: Edm.String
	Description *string `json:"Description,omitempty"`

	// Division: Edm.Int32
	Division *int `json:"Division,omitempty"`

	// IsDefault: Edm.Byte
	IsDefault *byte `json:"IsDefault,omitempty"`

	// Item: Edm.Guid
	Item *types.GUID `json:"Item,omitempty"`

	// ItemDescription: Edm.String
	ItemDescription *string `json:"ItemDescription,omitempty"`

	// LeadTime: Edm.Int32
	LeadTime *int `json:"LeadTime,omitempty"`

	// Modified: Edm.DateTime
	Modified *types.Date `json:"Modified,omitempty"`

	// Modifier: Edm.Guid
	Modifier *types.GUID `json:"Modifier,omitempty"`

	// ModifierFullName: Edm.String
	ModifierFullName *string `json:"ModifierFullName,omitempty"`

	// Notes: Edm.String
	Notes *string `json:"Notes,omitempty"`

	// Status: Edm.Int16
	Status *int `json:"Status,omitempty"`

	// StatusDescription: Edm.String
	StatusDescription *string `json:"StatusDescription,omitempty"`

	// Type: Edm.Int16
	Type *int `json:"Type,omitempty"`

	// TypeDescription: Edm.String
	TypeDescription *string `json:"TypeDescription,omitempty"`

	// VersionDate: Edm.DateTime
	VersionDate *types.Date `json:"VersionDate,omitempty"`

	// VersionNumber: Edm.Int32
	VersionNumber *int `json:"VersionNumber,omitempty"`
}

func (e *ItemVersions) GetPrimary() *types.GUID {
	return e.ID
}

func (s *ItemVersionsEndpoint) UserHasRights(ctx context.Context, division int, method string) (bool, error) {
	return s.client.UserHasRights(ctx, division, "logistics/ItemVersions", method)
}

// List the ItemVersions entities in the provided division.
// If all is true, all the paginated results are fetched; if false, list the first page.
func (s *ItemVersionsEndpoint) List(ctx context.Context, division int, all bool, o *api.ListOptions) ([]*ItemVersions, error) {
	var entities []*ItemVersions
	u, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/logistics/ItemVersions", division) // #nosec
	api.AddListOptionsToURL(u, o)

	if all {
		err := s.client.ListRequestAndDoAll(ctx, u.String(), &entities)
		return entities, err
	}
	_, _, err := s.client.NewRequestAndDo(ctx, "GET", u.String(), nil, &entities)
	return entities, err
}

// Get the ItemVersions entitiy in the provided division.
func (s *ItemVersionsEndpoint) Get(ctx context.Context, division int, id *types.GUID) (*ItemVersions, error) {
	b, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/logistics/ItemVersions", division) // #nosec
	u, err := api.AddOdataKeyToURL(b, id)
	if err != nil {
		return nil, err
	}

	e := &ItemVersions{}
	_, _, requestError := s.client.NewRequestAndDo(ctx, "GET", u.String(), nil, e)
	return e, requestError
}
