// Copyright 2024 The go-exactonline AUTHORS. All rights reserved.
//
// Use of this source code is governed by a MIT
// license that can be found in the LICENSE file.
// Code generated by gen-services.go; DO NOT EDIT.
package salesorder

import (
	"context"
	"fmt"
	"io/ioutil"
	"net/http"

	"github.com/mcnijman/go-exactonline/api"
	"github.com/mcnijman/go-exactonline/types"
)

// SalesOrderLinesEndpoint is responsible for communicating with
// the SalesOrderLines endpoint of the SalesOrder service.
type SalesOrderLinesEndpoint service

// SalesOrderLines:
// Service: SalesOrder
// Entity: SalesOrderLines
// URL: /api/v1/{division}/salesorder/SalesOrderLines
// HasWebhook: true
// IsInBeta: false
// Methods: GET POST PUT DELETE
// Endpoint docs: https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=SalesOrderSalesOrderLines
type SalesOrderLines struct {
	MetaData *api.MetaData `json:"__metadata,omitempty"`
	// ID: Edm.Guid
	ID *types.GUID `json:"ID,omitempty"`

	// AmountDC: Edm.Double
	AmountDC *float64 `json:"AmountDC,omitempty"`

	// AmountFC: Edm.Double
	AmountFC *float64 `json:"AmountFC,omitempty"`

	// CostCenter: Edm.String
	CostCenter *string `json:"CostCenter,omitempty"`

	// CostCenterDescription: Edm.String
	CostCenterDescription *string `json:"CostCenterDescription,omitempty"`

	// CostPriceFC: Edm.Double
	CostPriceFC *float64 `json:"CostPriceFC,omitempty"`

	// CostUnit: Edm.String
	CostUnit *string `json:"CostUnit,omitempty"`

	// CostUnitDescription: Edm.String
	CostUnitDescription *string `json:"CostUnitDescription,omitempty"`

	// CustomerItemCode: Edm.String
	CustomerItemCode *string `json:"CustomerItemCode,omitempty"`

	// CustomField: Edm.String
	CustomField *string `json:"CustomField,omitempty"`

	// DeliveryDate: Edm.DateTime
	DeliveryDate *types.Date `json:"DeliveryDate,omitempty"`

	// DeliveryStatus: Edm.Int16
	DeliveryStatus *int `json:"DeliveryStatus,omitempty"`

	// Description: Edm.String
	Description *string `json:"Description,omitempty"`

	// Discount: Edm.Double
	Discount *float64 `json:"Discount,omitempty"`

	// Division: Edm.Int32
	Division *int `json:"Division,omitempty"`

	// InvoiceStatus: Edm.Int16
	InvoiceStatus *int `json:"InvoiceStatus,omitempty"`

	// Item: Edm.Guid
	Item *types.GUID `json:"Item,omitempty"`

	// ItemCode: Edm.String
	ItemCode *string `json:"ItemCode,omitempty"`

	// ItemDescription: Edm.String
	ItemDescription *string `json:"ItemDescription,omitempty"`

	// ItemVersion: Edm.Guid
	ItemVersion *types.GUID `json:"ItemVersion,omitempty"`

	// ItemVersionDescription: Edm.String
	ItemVersionDescription *string `json:"ItemVersionDescription,omitempty"`

	// LineNumber: Edm.Int32
	LineNumber *int `json:"LineNumber,omitempty"`

	// Margin: Edm.Double
	Margin *float64 `json:"Margin,omitempty"`

	// NetPrice: Edm.Double
	NetPrice *float64 `json:"NetPrice,omitempty"`

	// Notes: Edm.String
	Notes *string `json:"Notes,omitempty"`

	// OrderID: Edm.Guid
	OrderID *types.GUID `json:"OrderID,omitempty"`

	// OrderNumber: Edm.Int32
	OrderNumber *int `json:"OrderNumber,omitempty"`

	// OrderStatus: Edm.Int16
	OrderStatus *int `json:"OrderStatus,omitempty"`

	// Pricelist: Edm.Guid
	Pricelist *types.GUID `json:"Pricelist,omitempty"`

	// PricelistDescription: Edm.String
	PricelistDescription *string `json:"PricelistDescription,omitempty"`

	// Project: Edm.Guid
	Project *types.GUID `json:"Project,omitempty"`

	// ProjectDescription: Edm.String
	ProjectDescription *string `json:"ProjectDescription,omitempty"`

	// PurchaseOrder: Edm.Guid
	PurchaseOrder *types.GUID `json:"PurchaseOrder,omitempty"`

	// PurchaseOrderLine: Edm.Guid
	PurchaseOrderLine *types.GUID `json:"PurchaseOrderLine,omitempty"`

	// PurchaseOrderLineNumber: Edm.Int32
	PurchaseOrderLineNumber *int `json:"PurchaseOrderLineNumber,omitempty"`

	// PurchaseOrderNumber: Edm.Int32
	PurchaseOrderNumber *int `json:"PurchaseOrderNumber,omitempty"`

	// Quantity: Edm.Double
	Quantity *float64 `json:"Quantity,omitempty"`

	// QuantityDelivered: Edm.Double
	QuantityDelivered *float64 `json:"QuantityDelivered,omitempty"`

	// QuantityInvoiced: Edm.Double
	QuantityInvoiced *float64 `json:"QuantityInvoiced,omitempty"`

	// ShopOrder: Edm.Guid
	ShopOrder *types.GUID `json:"ShopOrder,omitempty"`

	// TaxSchedule: Edm.Guid
	TaxSchedule *types.GUID `json:"TaxSchedule,omitempty"`

	// TaxScheduleCode: Edm.String
	TaxScheduleCode *string `json:"TaxScheduleCode,omitempty"`

	// TaxScheduleDescription: Edm.String
	TaxScheduleDescription *string `json:"TaxScheduleDescription,omitempty"`

	// UnitCode: Edm.String
	UnitCode *string `json:"UnitCode,omitempty"`

	// UnitDescription: Edm.String
	UnitDescription *string `json:"UnitDescription,omitempty"`

	// UnitPrice: Edm.Double
	UnitPrice *float64 `json:"UnitPrice,omitempty"`

	// UseDropShipment: Edm.Byte
	UseDropShipment *byte `json:"UseDropShipment,omitempty"`

	// VATAmount: Edm.Double
	VATAmount *float64 `json:"VATAmount,omitempty"`

	// VATCode: Edm.String
	VATCode *string `json:"VATCode,omitempty"`

	// VATCodeDescription: Edm.String
	VATCodeDescription *string `json:"VATCodeDescription,omitempty"`

	// VATPercentage: Edm.Double
	VATPercentage *float64 `json:"VATPercentage,omitempty"`
}

func (e *SalesOrderLines) GetPrimary() *types.GUID {
	return e.ID
}

func (s *SalesOrderLinesEndpoint) UserHasRights(ctx context.Context, division int, method string) (bool, error) {
	return s.client.UserHasRights(ctx, division, "salesorder/SalesOrderLines", method)
}

// List the SalesOrderLines entities in the provided division.
// If all is true, all the paginated results are fetched; if false, list the first page.
func (s *SalesOrderLinesEndpoint) List(ctx context.Context, division int, all bool, o *api.ListOptions) ([]*SalesOrderLines, error) {
	var entities []*SalesOrderLines
	u, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/salesorder/SalesOrderLines", division) // #nosec
	api.AddListOptionsToURL(u, o)

	if all {
		err := s.client.ListRequestAndDoAll(ctx, u.String(), &entities)
		return entities, err
	}
	_, _, err := s.client.NewRequestAndDo(ctx, "GET", u.String(), nil, &entities)
	return entities, err
}

// Get the SalesOrderLines entitiy in the provided division.
func (s *SalesOrderLinesEndpoint) Get(ctx context.Context, division int, id *types.GUID) (*SalesOrderLines, error) {
	b, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/salesorder/SalesOrderLines", division) // #nosec
	u, err := api.AddOdataKeyToURL(b, id)
	if err != nil {
		return nil, err
	}

	e := &SalesOrderLines{}
	_, _, requestError := s.client.NewRequestAndDo(ctx, "GET", u.String(), nil, e)
	return e, requestError
}

// New returns an empty SalesOrderLines entity
func (s *SalesOrderLinesEndpoint) New() *SalesOrderLines {
	return &SalesOrderLines{}
}

// Create the SalesOrderLines entity in the provided division.
func (s *SalesOrderLinesEndpoint) Create(ctx context.Context, division int, entity *SalesOrderLines) (*SalesOrderLines, error) {
	u, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/salesorder/SalesOrderLines", division) // #nosec
	e := &SalesOrderLines{}
	_, _, err := s.client.NewRequestAndDo(ctx, "POST", u.String(), entity, e)
	if err != nil {
		return nil, err
	}
	return e, nil
}

// Update the SalesOrderLines entity in the provided division.
func (s *SalesOrderLinesEndpoint) Update(ctx context.Context, division int, entity *SalesOrderLines) (*SalesOrderLines, error) {
	b, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/salesorder/SalesOrderLines", division) // #nosec
	u, err := api.AddOdataKeyToURL(b, entity.GetPrimary())
	if err != nil {
		return nil, err
	}

	e := &SalesOrderLines{}
	_, _, requestError := s.client.NewRequestAndDo(ctx, "PUT", u.String(), entity, e)
	return e, requestError
}

// Delete the SalesOrderLines entity in the provided division.
func (s *SalesOrderLinesEndpoint) Delete(ctx context.Context, division int, id *types.GUID) error {
	b, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/salesorder/SalesOrderLines", division) // #nosec
	u, err := api.AddOdataKeyToURL(b, id)
	if err != nil {
		return err
	}

	_, r, requestError := s.client.NewRequestAndDo(ctx, "DELETE", u.String(), nil, nil)
	if requestError != nil {
		return requestError
	}

	if r.StatusCode != http.StatusNoContent {
		body, _ := ioutil.ReadAll(r.Body) // #nosec
		return fmt.Errorf("Failed with status %v and body %v", r.StatusCode, body)
	}

	return nil
}
