// Copyright 2024 The go-exactonline AUTHORS. All rights reserved.
//
// Use of this source code is governed by a MIT
// license that can be found in the LICENSE file.
// Code generated by gen-services.go; DO NOT EDIT.
package salesorder

import (
	"context"
	"fmt"
	"io/ioutil"
	"net/http"

	"github.com/mcnijman/go-exactonline/api"
	"github.com/mcnijman/go-exactonline/types"
)

// SalesOrderOrderChargeLinesEndpoint is responsible for communicating with
// the SalesOrderOrderChargeLines endpoint of the SalesOrder service.
type SalesOrderOrderChargeLinesEndpoint service

// SalesOrderOrderChargeLines:
// Service: SalesOrder
// Entity: SalesOrderOrderChargeLines
// URL: /api/v1/{division}/salesorder/SalesOrderOrderChargeLines
// HasWebhook: false
// IsInBeta: false
// Methods: GET POST PUT DELETE
// Endpoint docs: https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=SalesOrderSalesOrderOrderChargeLines
type SalesOrderOrderChargeLines struct {
	MetaData *api.MetaData `json:"__metadata,omitempty"`
	// ID: Edm.Guid
	ID *types.GUID `json:"ID,omitempty"`

	// AmountDC: Edm.Double
	AmountDC *float64 `json:"AmountDC,omitempty"`

	// AmountFCExclVAT: Edm.Double
	AmountFCExclVAT *float64 `json:"AmountFCExclVAT,omitempty"`

	// AmountFCInclVAT: Edm.Double
	AmountFCInclVAT *float64 `json:"AmountFCInclVAT,omitempty"`

	// AmountVATFC: Edm.Double
	AmountVATFC *float64 `json:"AmountVATFC,omitempty"`

	// Division: Edm.Int32
	Division *int `json:"Division,omitempty"`

	// IsShippingCost: Edm.Boolean
	IsShippingCost *bool `json:"IsShippingCost,omitempty"`

	// LineNumber: Edm.Int32
	LineNumber *int `json:"LineNumber,omitempty"`

	// OrderCharge: Edm.Guid
	OrderCharge *types.GUID `json:"OrderCharge,omitempty"`

	// OrderChargeCode: Edm.String
	OrderChargeCode *string `json:"OrderChargeCode,omitempty"`

	// OrderChargeDescription: Edm.String
	OrderChargeDescription *string `json:"OrderChargeDescription,omitempty"`

	// OrderChargesLineDescription: Edm.String
	OrderChargesLineDescription *string `json:"OrderChargesLineDescription,omitempty"`

	// OrderID: Edm.Guid
	OrderID *types.GUID `json:"OrderID,omitempty"`

	// VATCode: Edm.String
	VATCode *string `json:"VATCode,omitempty"`

	// VATDescription: Edm.String
	VATDescription *string `json:"VATDescription,omitempty"`

	// VATPercentage: Edm.Double
	VATPercentage *float64 `json:"VATPercentage,omitempty"`
}

func (e *SalesOrderOrderChargeLines) GetPrimary() *types.GUID {
	return e.ID
}

func (s *SalesOrderOrderChargeLinesEndpoint) UserHasRights(ctx context.Context, division int, method string) (bool, error) {
	return s.client.UserHasRights(ctx, division, "salesorder/SalesOrderOrderChargeLines", method)
}

// List the SalesOrderOrderChargeLines entities in the provided division.
// If all is true, all the paginated results are fetched; if false, list the first page.
func (s *SalesOrderOrderChargeLinesEndpoint) List(ctx context.Context, division int, all bool, o *api.ListOptions) ([]*SalesOrderOrderChargeLines, error) {
	var entities []*SalesOrderOrderChargeLines
	u, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/salesorder/SalesOrderOrderChargeLines", division) // #nosec
	api.AddListOptionsToURL(u, o)

	if all {
		err := s.client.ListRequestAndDoAll(ctx, u.String(), &entities)
		return entities, err
	}
	_, _, err := s.client.NewRequestAndDo(ctx, "GET", u.String(), nil, &entities)
	return entities, err
}

// Get the SalesOrderOrderChargeLines entitiy in the provided division.
func (s *SalesOrderOrderChargeLinesEndpoint) Get(ctx context.Context, division int, id *types.GUID) (*SalesOrderOrderChargeLines, error) {
	b, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/salesorder/SalesOrderOrderChargeLines", division) // #nosec
	u, err := api.AddOdataKeyToURL(b, id)
	if err != nil {
		return nil, err
	}

	e := &SalesOrderOrderChargeLines{}
	_, _, requestError := s.client.NewRequestAndDo(ctx, "GET", u.String(), nil, e)
	return e, requestError
}

// New returns an empty SalesOrderOrderChargeLines entity
func (s *SalesOrderOrderChargeLinesEndpoint) New() *SalesOrderOrderChargeLines {
	return &SalesOrderOrderChargeLines{}
}

// Create the SalesOrderOrderChargeLines entity in the provided division.
func (s *SalesOrderOrderChargeLinesEndpoint) Create(ctx context.Context, division int, entity *SalesOrderOrderChargeLines) (*SalesOrderOrderChargeLines, error) {
	u, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/salesorder/SalesOrderOrderChargeLines", division) // #nosec
	e := &SalesOrderOrderChargeLines{}
	_, _, err := s.client.NewRequestAndDo(ctx, "POST", u.String(), entity, e)
	if err != nil {
		return nil, err
	}
	return e, nil
}

// Update the SalesOrderOrderChargeLines entity in the provided division.
func (s *SalesOrderOrderChargeLinesEndpoint) Update(ctx context.Context, division int, entity *SalesOrderOrderChargeLines) (*SalesOrderOrderChargeLines, error) {
	b, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/salesorder/SalesOrderOrderChargeLines", division) // #nosec
	u, err := api.AddOdataKeyToURL(b, entity.GetPrimary())
	if err != nil {
		return nil, err
	}

	e := &SalesOrderOrderChargeLines{}
	_, _, requestError := s.client.NewRequestAndDo(ctx, "PUT", u.String(), entity, e)
	return e, requestError
}

// Delete the SalesOrderOrderChargeLines entity in the provided division.
func (s *SalesOrderOrderChargeLinesEndpoint) Delete(ctx context.Context, division int, id *types.GUID) error {
	b, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/salesorder/SalesOrderOrderChargeLines", division) // #nosec
	u, err := api.AddOdataKeyToURL(b, id)
	if err != nil {
		return err
	}

	_, r, requestError := s.client.NewRequestAndDo(ctx, "DELETE", u.String(), nil, nil)
	if requestError != nil {
		return requestError
	}

	if r.StatusCode != http.StatusNoContent {
		body, _ := ioutil.ReadAll(r.Body) // #nosec
		return fmt.Errorf("Failed with status %v and body %v", r.StatusCode, body)
	}

	return nil
}
