// Copyright 2024 The go-exactonline AUTHORS. All rights reserved.
//
// Use of this source code is governed by a MIT
// license that can be found in the LICENSE file.
// Code generated by gen-services.go; DO NOT EDIT.
package budget

import (
	"context"

	"github.com/mcnijman/go-exactonline/api"
	"github.com/mcnijman/go-exactonline/types"
)

// BudgetScenariosEndpoint is responsible for communicating with
// the BudgetScenarios endpoint of the Budget service.
type BudgetScenariosEndpoint service

// BudgetScenarios:
// Service: Budget
// Entity: BudgetScenarios
// URL: /api/v1/beta/{division}/budget/BudgetScenarios
// HasWebhook: false
// IsInBeta: true
// Methods: GET
// Endpoint docs: https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=BudgetBudgetScenarios
type BudgetScenarios struct {
	MetaData *api.MetaData `json:"__metadata,omitempty"`
	// ID: Edm.Guid
	ID *types.GUID `json:"ID,omitempty"`

	// Code: Edm.String
	Code *string `json:"Code,omitempty"`

	// Created: Edm.DateTime
	Created *types.Date `json:"Created,omitempty"`

	// Creator: Edm.Guid
	Creator *types.GUID `json:"Creator,omitempty"`

	// CreatorFullName: Edm.String
	CreatorFullName *string `json:"CreatorFullName,omitempty"`

	// Description: Edm.String
	Description *string `json:"Description,omitempty"`

	// Division: Edm.Int32
	Division *int `json:"Division,omitempty"`

	// FromYear: Edm.Int16
	FromYear *int `json:"FromYear,omitempty"`

	// Modified: Edm.DateTime
	Modified *types.Date `json:"Modified,omitempty"`

	// Modifier: Edm.Guid
	Modifier *types.GUID `json:"Modifier,omitempty"`

	// ModifierFullName: Edm.String
	ModifierFullName *string `json:"ModifierFullName,omitempty"`

	// ToYear: Edm.Int16
	ToYear *int `json:"ToYear,omitempty"`
}

func (e *BudgetScenarios) GetPrimary() *types.GUID {
	return e.ID
}

func (s *BudgetScenariosEndpoint) UserHasRights(ctx context.Context, division int, method string) (bool, error) {
	return s.client.UserHasRights(ctx, division, "budget/BudgetScenarios", method)
}

// List the BudgetScenarios entities in the provided division.
// If all is true, all the paginated results are fetched; if false, list the first page.
func (s *BudgetScenariosEndpoint) List(ctx context.Context, division int, all bool, o *api.ListOptions) ([]*BudgetScenarios, error) {
	var entities []*BudgetScenarios
	u, _ := s.client.ResolvePathWithDivision("/api/v1/beta/{division}/budget/BudgetScenarios", division) // #nosec
	api.AddListOptionsToURL(u, o)

	if all {
		err := s.client.ListRequestAndDoAll(ctx, u.String(), &entities)
		return entities, err
	}
	_, _, err := s.client.NewRequestAndDo(ctx, "GET", u.String(), nil, &entities)
	return entities, err
}

// Get the BudgetScenarios entitiy in the provided division.
func (s *BudgetScenariosEndpoint) Get(ctx context.Context, division int, id *types.GUID) (*BudgetScenarios, error) {
	b, _ := s.client.ResolvePathWithDivision("/api/v1/beta/{division}/budget/BudgetScenarios", division) // #nosec
	u, err := api.AddOdataKeyToURL(b, id)
	if err != nil {
		return nil, err
	}

	e := &BudgetScenarios{}
	_, _, requestError := s.client.NewRequestAndDo(ctx, "GET", u.String(), nil, e)
	return e, requestError
}
