// Copyright 2024 The go-exactonline AUTHORS. All rights reserved.
//
// Use of this source code is governed by a MIT
// license that can be found in the LICENSE file.
// Code generated by gen-services.go; DO NOT EDIT.
package crm

import (
	"context"
	"fmt"
	"io/ioutil"
	"net/http"

	"github.com/mcnijman/go-exactonline/api"
	"github.com/mcnijman/go-exactonline/types"
)

// AddressesEndpoint is responsible for communicating with
// the Addresses endpoint of the CRM service.
type AddressesEndpoint service

// Addresses:
// Service: CRM
// Entity: Addresses
// URL: /api/v1/{division}/crm/Addresses
// HasWebhook: false
// IsInBeta: false
// Methods: GET POST PUT DELETE
// Endpoint docs: https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=CRMAddresses
type Addresses struct {
	MetaData *api.MetaData `json:"__metadata,omitempty"`
	// ID: Edm.Guid
	ID *types.GUID `json:"ID,omitempty"`

	// Account: Edm.Guid
	Account *types.GUID `json:"Account,omitempty"`

	// AccountIsSupplier: Edm.Boolean
	AccountIsSupplier *bool `json:"AccountIsSupplier,omitempty"`

	// AccountName: Edm.String
	AccountName *string `json:"AccountName,omitempty"`

	// AddressLine1: Edm.String
	AddressLine1 *string `json:"AddressLine1,omitempty"`

	// AddressLine2: Edm.String
	AddressLine2 *string `json:"AddressLine2,omitempty"`

	// AddressLine3: Edm.String
	AddressLine3 *string `json:"AddressLine3,omitempty"`

	// City: Edm.String
	City *string `json:"City,omitempty"`

	// Contact: Edm.Guid
	Contact *types.GUID `json:"Contact,omitempty"`

	// ContactName: Edm.String
	ContactName *string `json:"ContactName,omitempty"`

	// Country: Edm.String
	Country *string `json:"Country,omitempty"`

	// CountryName: Edm.String
	CountryName *string `json:"CountryName,omitempty"`

	// Created: Edm.DateTime
	Created *types.Date `json:"Created,omitempty"`

	// Creator: Edm.Guid
	Creator *types.GUID `json:"Creator,omitempty"`

	// CreatorFullName: Edm.String
	CreatorFullName *string `json:"CreatorFullName,omitempty"`

	// CustomField: Edm.String
	CustomField *string `json:"CustomField,omitempty"`

	// Division: Edm.Int32
	Division *int `json:"Division,omitempty"`

	// Fax: Edm.String
	Fax *string `json:"Fax,omitempty"`

	// FreeBoolField_01: Edm.Boolean
	FreeBoolField_01 *bool `json:"FreeBoolField_01,omitempty"`

	// FreeBoolField_02: Edm.Boolean
	FreeBoolField_02 *bool `json:"FreeBoolField_02,omitempty"`

	// FreeBoolField_03: Edm.Boolean
	FreeBoolField_03 *bool `json:"FreeBoolField_03,omitempty"`

	// FreeBoolField_04: Edm.Boolean
	FreeBoolField_04 *bool `json:"FreeBoolField_04,omitempty"`

	// FreeBoolField_05: Edm.Boolean
	FreeBoolField_05 *bool `json:"FreeBoolField_05,omitempty"`

	// FreeDateField_01: Edm.DateTime
	FreeDateField_01 *types.Date `json:"FreeDateField_01,omitempty"`

	// FreeDateField_02: Edm.DateTime
	FreeDateField_02 *types.Date `json:"FreeDateField_02,omitempty"`

	// FreeDateField_03: Edm.DateTime
	FreeDateField_03 *types.Date `json:"FreeDateField_03,omitempty"`

	// FreeDateField_04: Edm.DateTime
	FreeDateField_04 *types.Date `json:"FreeDateField_04,omitempty"`

	// FreeDateField_05: Edm.DateTime
	FreeDateField_05 *types.Date `json:"FreeDateField_05,omitempty"`

	// FreeNumberField_01: Edm.Double
	FreeNumberField_01 *float64 `json:"FreeNumberField_01,omitempty"`

	// FreeNumberField_02: Edm.Double
	FreeNumberField_02 *float64 `json:"FreeNumberField_02,omitempty"`

	// FreeNumberField_03: Edm.Double
	FreeNumberField_03 *float64 `json:"FreeNumberField_03,omitempty"`

	// FreeNumberField_04: Edm.Double
	FreeNumberField_04 *float64 `json:"FreeNumberField_04,omitempty"`

	// FreeNumberField_05: Edm.Double
	FreeNumberField_05 *float64 `json:"FreeNumberField_05,omitempty"`

	// FreeTextField_01: Edm.String
	FreeTextField_01 *string `json:"FreeTextField_01,omitempty"`

	// FreeTextField_02: Edm.String
	FreeTextField_02 *string `json:"FreeTextField_02,omitempty"`

	// FreeTextField_03: Edm.String
	FreeTextField_03 *string `json:"FreeTextField_03,omitempty"`

	// FreeTextField_04: Edm.String
	FreeTextField_04 *string `json:"FreeTextField_04,omitempty"`

	// FreeTextField_05: Edm.String
	FreeTextField_05 *string `json:"FreeTextField_05,omitempty"`

	// Mailbox: Edm.String
	Mailbox *string `json:"Mailbox,omitempty"`

	// Main: Edm.Boolean
	Main *bool `json:"Main,omitempty"`

	// Modified: Edm.DateTime
	Modified *types.Date `json:"Modified,omitempty"`

	// Modifier: Edm.Guid
	Modifier *types.GUID `json:"Modifier,omitempty"`

	// ModifierFullName: Edm.String
	ModifierFullName *string `json:"ModifierFullName,omitempty"`

	// NicNumber: Edm.String
	NicNumber *string `json:"NicNumber,omitempty"`

	// Notes: Edm.String
	Notes *string `json:"Notes,omitempty"`

	// Phone: Edm.String
	Phone *string `json:"Phone,omitempty"`

	// PhoneExtension: Edm.String
	PhoneExtension *string `json:"PhoneExtension,omitempty"`

	// Postcode: Edm.String
	Postcode *string `json:"Postcode,omitempty"`

	// Source: Edm.Byte
	Source *byte `json:"Source,omitempty"`

	// State: Edm.String
	State *string `json:"State,omitempty"`

	// StateDescription: Edm.String
	StateDescription *string `json:"StateDescription,omitempty"`

	// Type: Edm.Int16
	Type *int `json:"Type,omitempty"`

	// Warehouse: Edm.Guid
	Warehouse *types.GUID `json:"Warehouse,omitempty"`

	// WarehouseCode: Edm.String
	WarehouseCode *string `json:"WarehouseCode,omitempty"`

	// WarehouseDescription: Edm.String
	WarehouseDescription *string `json:"WarehouseDescription,omitempty"`
}

func (e *Addresses) GetPrimary() *types.GUID {
	return e.ID
}

func (s *AddressesEndpoint) UserHasRights(ctx context.Context, division int, method string) (bool, error) {
	return s.client.UserHasRights(ctx, division, "crm/Addresses", method)
}

// List the Addresses entities in the provided division.
// If all is true, all the paginated results are fetched; if false, list the first page.
func (s *AddressesEndpoint) List(ctx context.Context, division int, all bool, o *api.ListOptions) ([]*Addresses, error) {
	var entities []*Addresses
	u, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/crm/Addresses", division) // #nosec
	api.AddListOptionsToURL(u, o)

	if all {
		err := s.client.ListRequestAndDoAll(ctx, u.String(), &entities)
		return entities, err
	}
	_, _, err := s.client.NewRequestAndDo(ctx, "GET", u.String(), nil, &entities)
	return entities, err
}

// Get the Addresses entitiy in the provided division.
func (s *AddressesEndpoint) Get(ctx context.Context, division int, id *types.GUID) (*Addresses, error) {
	b, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/crm/Addresses", division) // #nosec
	u, err := api.AddOdataKeyToURL(b, id)
	if err != nil {
		return nil, err
	}

	e := &Addresses{}
	_, _, requestError := s.client.NewRequestAndDo(ctx, "GET", u.String(), nil, e)
	return e, requestError
}

// New returns an empty Addresses entity
func (s *AddressesEndpoint) New() *Addresses {
	return &Addresses{}
}

// Create the Addresses entity in the provided division.
func (s *AddressesEndpoint) Create(ctx context.Context, division int, entity *Addresses) (*Addresses, error) {
	u, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/crm/Addresses", division) // #nosec
	e := &Addresses{}
	_, _, err := s.client.NewRequestAndDo(ctx, "POST", u.String(), entity, e)
	if err != nil {
		return nil, err
	}
	return e, nil
}

// Update the Addresses entity in the provided division.
func (s *AddressesEndpoint) Update(ctx context.Context, division int, entity *Addresses) (*Addresses, error) {
	b, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/crm/Addresses", division) // #nosec
	u, err := api.AddOdataKeyToURL(b, entity.GetPrimary())
	if err != nil {
		return nil, err
	}

	e := &Addresses{}
	_, _, requestError := s.client.NewRequestAndDo(ctx, "PUT", u.String(), entity, e)
	return e, requestError
}

// Delete the Addresses entity in the provided division.
func (s *AddressesEndpoint) Delete(ctx context.Context, division int, id *types.GUID) error {
	b, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/crm/Addresses", division) // #nosec
	u, err := api.AddOdataKeyToURL(b, id)
	if err != nil {
		return err
	}

	_, r, requestError := s.client.NewRequestAndDo(ctx, "DELETE", u.String(), nil, nil)
	if requestError != nil {
		return requestError
	}

	if r.StatusCode != http.StatusNoContent {
		body, _ := ioutil.ReadAll(r.Body) // #nosec
		return fmt.Errorf("Failed with status %v and body %v", r.StatusCode, body)
	}

	return nil
}
