// Copyright 2024 The go-exactonline AUTHORS. All rights reserved.
//
// Use of this source code is governed by a MIT
// license that can be found in the LICENSE file.
// Code generated by gen-services.go; DO NOT EDIT.
package crm

import (
	"context"
	"encoding/json"

	"github.com/mcnijman/go-exactonline/api"
	"github.com/mcnijman/go-exactonline/types"
)

// DocumentsEndpoint is responsible for communicating with
// the Documents endpoint of the CRM service.
type DocumentsEndpoint service

// Documents:
// Service: CRM
// Entity: Documents
// URL: /api/v1/{division}/read/crm/Documents
// HasWebhook: false
// IsInBeta: false
// Methods: GET
// Endpoint docs: https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=ReadCRMDocuments
type Documents struct {
	MetaData *api.MetaData `json:"__metadata,omitempty"`
	// ID: Edm.Guid
	ID *types.GUID `json:"ID,omitempty"`

	// Account: Edm.Guid
	Account *types.GUID `json:"Account,omitempty"`

	// Attachments: Attachments
	Attachments *json.RawMessage `json:"Attachments,omitempty"`

	// Contact: Edm.Guid
	Contact *types.GUID `json:"Contact,omitempty"`

	// Created: Edm.DateTime
	Created *types.Date `json:"Created,omitempty"`

	// Creator: Edm.Guid
	Creator *types.GUID `json:"Creator,omitempty"`

	// CreatorFullName: Edm.String
	CreatorFullName *string `json:"CreatorFullName,omitempty"`

	// Division: Edm.Int32
	Division *int `json:"Division,omitempty"`

	// DocumentDate: Edm.DateTime
	DocumentDate *types.Date `json:"DocumentDate,omitempty"`

	// DocumentFolder: Edm.Guid
	DocumentFolder *types.GUID `json:"DocumentFolder,omitempty"`

	// DocumentViewUrl: Edm.String
	DocumentViewUrl *string `json:"DocumentViewUrl,omitempty"`

	// HasEmptyBody: Edm.Boolean
	HasEmptyBody *bool `json:"HasEmptyBody,omitempty"`

	// HID: Edm.Int32
	HID *int `json:"HID,omitempty"`

	// Modified: Edm.DateTime
	Modified *types.Date `json:"Modified,omitempty"`

	// Modifier: Edm.Guid
	Modifier *types.GUID `json:"Modifier,omitempty"`

	// Opportunity: Edm.Guid
	Opportunity *types.GUID `json:"Opportunity,omitempty"`

	// PurchaseInvoiceNumber: Edm.Int32
	PurchaseInvoiceNumber *int `json:"PurchaseInvoiceNumber,omitempty"`

	// PurchaseOrderNumber: Edm.Int32
	PurchaseOrderNumber *int `json:"PurchaseOrderNumber,omitempty"`

	// SalesInvoiceNumber: Edm.Int32
	SalesInvoiceNumber *int `json:"SalesInvoiceNumber,omitempty"`

	// SalesOrderNumber: Edm.Int32
	SalesOrderNumber *int `json:"SalesOrderNumber,omitempty"`

	// SendMethod: Edm.Int32
	SendMethod *int `json:"SendMethod,omitempty"`

	// Share: Edm.Int32
	Share *int `json:"Share,omitempty"`

	// SharePointConnectionStatus: Edm.Int16
	SharePointConnectionStatus *int `json:"SharePointConnectionStatus,omitempty"`

	// SharePointID: Edm.String
	SharePointID *string `json:"SharePointID,omitempty"`

	// Source: Edm.Int32
	Source *int `json:"Source,omitempty"`

	// SourceDescription: Edm.String
	SourceDescription *string `json:"SourceDescription,omitempty"`

	// Subject: Edm.String
	Subject *string `json:"Subject,omitempty"`

	// Type: Edm.Int32
	Type *int `json:"Type,omitempty"`

	// TypeDescription: Edm.String
	TypeDescription *string `json:"TypeDescription,omitempty"`
}

func (e *Documents) GetPrimary() *types.GUID {
	return e.ID
}

func (s *DocumentsEndpoint) UserHasRights(ctx context.Context, division int, method string) (bool, error) {
	return s.client.UserHasRights(ctx, division, "crm/Documents", method)
}

// List the Documents entities in the provided division.
// If all is true, all the paginated results are fetched; if false, list the first page.
func (s *DocumentsEndpoint) List(ctx context.Context, division int, all bool, o *api.ListOptions) ([]*Documents, error) {
	var entities []*Documents
	u, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/read/crm/Documents", division) // #nosec
	api.AddListOptionsToURL(u, o)

	if all {
		err := s.client.ListRequestAndDoAll(ctx, u.String(), &entities)
		return entities, err
	}
	_, _, err := s.client.NewRequestAndDo(ctx, "GET", u.String(), nil, &entities)
	return entities, err
}

// Get the Documents entitiy in the provided division.
func (s *DocumentsEndpoint) Get(ctx context.Context, division int, id *types.GUID) (*Documents, error) {
	b, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/read/crm/Documents", division) // #nosec
	u, err := api.AddOdataKeyToURL(b, id)
	if err != nil {
		return nil, err
	}

	e := &Documents{}
	_, _, requestError := s.client.NewRequestAndDo(ctx, "GET", u.String(), nil, e)
	return e, requestError
}
