// Copyright 2024 The go-exactonline AUTHORS. All rights reserved.
//
// Use of this source code is governed by a MIT
// license that can be found in the LICENSE file.
// Code generated by gen-services.go; DO NOT EDIT.
package crm

import (
	"context"
	"fmt"
	"io/ioutil"
	"net/http"

	"github.com/mcnijman/go-exactonline/api"
	"github.com/mcnijman/go-exactonline/types"
)

// HostingOpportunitiesEndpoint is responsible for communicating with
// the HostingOpportunities endpoint of the CRM service.
type HostingOpportunitiesEndpoint service

// HostingOpportunities:
// Service: CRM
// Entity: HostingOpportunities
// URL: /api/v1/{division}/crm/HostingOpportunities
// HasWebhook: true
// IsInBeta: false
// Methods: GET POST PUT DELETE
// Endpoint docs: https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=CRMHostingOpportunities
type HostingOpportunities struct {
	MetaData *api.MetaData `json:"__metadata,omitempty"`
	// ID: Edm.Guid
	ID *types.GUID `json:"ID,omitempty"`

	// Account: Edm.Guid
	Account *types.GUID `json:"Account,omitempty"`

	// Accountant: Edm.Guid
	Accountant *types.GUID `json:"Accountant,omitempty"`

	// AccountantCode: Edm.String
	AccountantCode *string `json:"AccountantCode,omitempty"`

	// AccountantName: Edm.String
	AccountantName *string `json:"AccountantName,omitempty"`

	// AccountCode: Edm.String
	AccountCode *string `json:"AccountCode,omitempty"`

	// AccountName: Edm.String
	AccountName *string `json:"AccountName,omitempty"`

	// ActionDate: Edm.DateTime
	ActionDate *types.Date `json:"ActionDate,omitempty"`

	// AmountDC: Edm.Double
	AmountDC *float64 `json:"AmountDC,omitempty"`

	// AmountFC: Edm.Double
	AmountFC *float64 `json:"AmountFC,omitempty"`

	// BackToLeadDevelopment: Edm.DateTime
	BackToLeadDevelopment *types.Date `json:"BackToLeadDevelopment,omitempty"`

	// Campaign: Edm.Guid
	Campaign *types.GUID `json:"Campaign,omitempty"`

	// CampaignDescription: Edm.String
	CampaignDescription *string `json:"CampaignDescription,omitempty"`

	// Channel: Edm.Int16
	Channel *int `json:"Channel,omitempty"`

	// ChannelDescription: Edm.String
	ChannelDescription *string `json:"ChannelDescription,omitempty"`

	// CloseDate: Edm.DateTime
	CloseDate *types.Date `json:"CloseDate,omitempty"`

	// Created: Edm.DateTime
	Created *types.Date `json:"Created,omitempty"`

	// Creator: Edm.Guid
	Creator *types.GUID `json:"Creator,omitempty"`

	// CreatorFullName: Edm.String
	CreatorFullName *string `json:"CreatorFullName,omitempty"`

	// Currency: Edm.String
	Currency *string `json:"Currency,omitempty"`

	// CustomerDemandsDescription: Edm.String
	CustomerDemandsDescription *string `json:"CustomerDemandsDescription,omitempty"`

	// DecisionMakingUnitName: Edm.String
	DecisionMakingUnitName *string `json:"DecisionMakingUnitName,omitempty"`

	// DecisionMakingUnitRole: Edm.String
	DecisionMakingUnitRole *string `json:"DecisionMakingUnitRole,omitempty"`

	// DecisionTimeframe: Edm.String
	DecisionTimeframe *string `json:"DecisionTimeframe,omitempty"`

	// DispatchToSales: Edm.DateTime
	DispatchToSales *types.Date `json:"DispatchToSales,omitempty"`

	// Division: Edm.Int32
	Division *int `json:"Division,omitempty"`

	// IsAssociatedPrice: Edm.Byte
	IsAssociatedPrice *byte `json:"IsAssociatedPrice,omitempty"`

	// IsCustomerDemandsMeet: Edm.Byte
	IsCustomerDemandsMeet *byte `json:"IsCustomerDemandsMeet,omitempty"`

	// LeadDeveloper: Edm.Guid
	LeadDeveloper *types.GUID `json:"LeadDeveloper,omitempty"`

	// LeadSource: Edm.Guid
	LeadSource *types.GUID `json:"LeadSource,omitempty"`

	// LeadSourceDescription: Edm.String
	LeadSourceDescription *string `json:"LeadSourceDescription,omitempty"`

	// Modified: Edm.DateTime
	Modified *types.Date `json:"Modified,omitempty"`

	// Modifier: Edm.Guid
	Modifier *types.GUID `json:"Modifier,omitempty"`

	// ModifierFullName: Edm.String
	ModifierFullName *string `json:"ModifierFullName,omitempty"`

	// Name: Edm.String
	Name *string `json:"Name,omitempty"`

	// NextAction: Edm.String
	NextAction *string `json:"NextAction,omitempty"`

	// Notes: Edm.String
	Notes *string `json:"Notes,omitempty"`

	// Number: Edm.Int32
	Number *int `json:"Number,omitempty"`

	// OpportunityDepartmentCode: Edm.Int16
	OpportunityDepartmentCode *int `json:"OpportunityDepartmentCode,omitempty"`

	// OpportunityDepartmentDescription: Edm.String
	OpportunityDepartmentDescription *string `json:"OpportunityDepartmentDescription,omitempty"`

	// OpportunityStage: Edm.Guid
	OpportunityStage *types.GUID `json:"OpportunityStage,omitempty"`

	// OpportunityStageDescription: Edm.String
	OpportunityStageDescription *string `json:"OpportunityStageDescription,omitempty"`

	// OpportunityStatus: Edm.Int32
	OpportunityStatus *int `json:"OpportunityStatus,omitempty"`

	// OpportunityType: Edm.Int16
	OpportunityType *int `json:"OpportunityType,omitempty"`

	// OpportunityTypeDescription: Edm.String
	OpportunityTypeDescription *string `json:"OpportunityTypeDescription,omitempty"`

	// Owner: Edm.Guid
	Owner *types.GUID `json:"Owner,omitempty"`

	// OwnerFullName: Edm.String
	OwnerFullName *string `json:"OwnerFullName,omitempty"`

	// Probability: Edm.Double
	Probability *float64 `json:"Probability,omitempty"`

	// Project: Edm.Guid
	Project *types.GUID `json:"Project,omitempty"`

	// ProjectCode: Edm.String
	ProjectCode *string `json:"ProjectCode,omitempty"`

	// ProjectDescription: Edm.String
	ProjectDescription *string `json:"ProjectDescription,omitempty"`

	// RateFC: Edm.Double
	RateFC *float64 `json:"RateFC,omitempty"`

	// ReasonBack: Edm.String
	ReasonBack *string `json:"ReasonBack,omitempty"`

	// ReasonCode: Edm.Guid
	ReasonCode *types.GUID `json:"ReasonCode,omitempty"`

	// ReasonCodeDescription: Edm.String
	ReasonCodeDescription *string `json:"ReasonCodeDescription,omitempty"`

	// Reseller: Edm.Guid
	Reseller *types.GUID `json:"Reseller,omitempty"`

	// ResellerCode: Edm.String
	ResellerCode *string `json:"ResellerCode,omitempty"`

	// ResellerName: Edm.String
	ResellerName *string `json:"ResellerName,omitempty"`

	// SalesType: Edm.Guid
	SalesType *types.GUID `json:"SalesType,omitempty"`

	// SalesTypeDescription: Edm.String
	SalesTypeDescription *string `json:"SalesTypeDescription,omitempty"`
}

func (e *HostingOpportunities) GetPrimary() *types.GUID {
	return e.ID
}

func (s *HostingOpportunitiesEndpoint) UserHasRights(ctx context.Context, division int, method string) (bool, error) {
	return s.client.UserHasRights(ctx, division, "crm/HostingOpportunities", method)
}

// List the HostingOpportunities entities in the provided division.
// If all is true, all the paginated results are fetched; if false, list the first page.
func (s *HostingOpportunitiesEndpoint) List(ctx context.Context, division int, all bool, o *api.ListOptions) ([]*HostingOpportunities, error) {
	var entities []*HostingOpportunities
	u, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/crm/HostingOpportunities", division) // #nosec
	api.AddListOptionsToURL(u, o)

	if all {
		err := s.client.ListRequestAndDoAll(ctx, u.String(), &entities)
		return entities, err
	}
	_, _, err := s.client.NewRequestAndDo(ctx, "GET", u.String(), nil, &entities)
	return entities, err
}

// Get the HostingOpportunities entitiy in the provided division.
func (s *HostingOpportunitiesEndpoint) Get(ctx context.Context, division int, id *types.GUID) (*HostingOpportunities, error) {
	b, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/crm/HostingOpportunities", division) // #nosec
	u, err := api.AddOdataKeyToURL(b, id)
	if err != nil {
		return nil, err
	}

	e := &HostingOpportunities{}
	_, _, requestError := s.client.NewRequestAndDo(ctx, "GET", u.String(), nil, e)
	return e, requestError
}

// New returns an empty HostingOpportunities entity
func (s *HostingOpportunitiesEndpoint) New() *HostingOpportunities {
	return &HostingOpportunities{}
}

// Create the HostingOpportunities entity in the provided division.
func (s *HostingOpportunitiesEndpoint) Create(ctx context.Context, division int, entity *HostingOpportunities) (*HostingOpportunities, error) {
	u, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/crm/HostingOpportunities", division) // #nosec
	e := &HostingOpportunities{}
	_, _, err := s.client.NewRequestAndDo(ctx, "POST", u.String(), entity, e)
	if err != nil {
		return nil, err
	}
	return e, nil
}

// Update the HostingOpportunities entity in the provided division.
func (s *HostingOpportunitiesEndpoint) Update(ctx context.Context, division int, entity *HostingOpportunities) (*HostingOpportunities, error) {
	b, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/crm/HostingOpportunities", division) // #nosec
	u, err := api.AddOdataKeyToURL(b, entity.GetPrimary())
	if err != nil {
		return nil, err
	}

	e := &HostingOpportunities{}
	_, _, requestError := s.client.NewRequestAndDo(ctx, "PUT", u.String(), entity, e)
	return e, requestError
}

// Delete the HostingOpportunities entity in the provided division.
func (s *HostingOpportunitiesEndpoint) Delete(ctx context.Context, division int, id *types.GUID) error {
	b, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/crm/HostingOpportunities", division) // #nosec
	u, err := api.AddOdataKeyToURL(b, id)
	if err != nil {
		return err
	}

	_, r, requestError := s.client.NewRequestAndDo(ctx, "DELETE", u.String(), nil, nil)
	if requestError != nil {
		return requestError
	}

	if r.StatusCode != http.StatusNoContent {
		body, _ := ioutil.ReadAll(r.Body) // #nosec
		return fmt.Errorf("Failed with status %v and body %v", r.StatusCode, body)
	}

	return nil
}
