// Copyright 2024 The go-exactonline AUTHORS. All rights reserved.
//
// Use of this source code is governed by a MIT
// license that can be found in the LICENSE file.
// Code generated by gen-services.go; DO NOT EDIT.
package project

import (
	"context"
	"fmt"
	"io/ioutil"
	"net/http"

	"github.com/mcnijman/go-exactonline/api"
	"github.com/mcnijman/go-exactonline/types"
)

// ProjectRestrictionEmployeesEndpoint is responsible for communicating with
// the ProjectRestrictionEmployees endpoint of the Project service.
type ProjectRestrictionEmployeesEndpoint service

// ProjectRestrictionEmployees:
// Service: Project
// Entity: ProjectRestrictionEmployees
// URL: /api/v1/{division}/project/ProjectRestrictionEmployees
// HasWebhook: false
// IsInBeta: false
// Methods: GET POST PUT DELETE
// Endpoint docs: https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=ProjectProjectRestrictionEmployees
type ProjectRestrictionEmployees struct {
	MetaData *api.MetaData `json:"__metadata,omitempty"`
	// ID: Edm.Guid
	ID *types.GUID `json:"ID,omitempty"`

	// Created: Edm.DateTime
	Created *types.Date `json:"Created,omitempty"`

	// Creator: Edm.Guid
	Creator *types.GUID `json:"Creator,omitempty"`

	// CreatorFullName: Edm.String
	CreatorFullName *string `json:"CreatorFullName,omitempty"`

	// Division: Edm.Int32
	Division *int `json:"Division,omitempty"`

	// Employee: Edm.Guid
	Employee *types.GUID `json:"Employee,omitempty"`

	// EmployeeFullName: Edm.String
	EmployeeFullName *string `json:"EmployeeFullName,omitempty"`

	// EmployeeHID: Edm.Int32
	EmployeeHID *int `json:"EmployeeHID,omitempty"`

	// Modified: Edm.DateTime
	Modified *types.Date `json:"Modified,omitempty"`

	// Modifier: Edm.Guid
	Modifier *types.GUID `json:"Modifier,omitempty"`

	// ModifierFullName: Edm.String
	ModifierFullName *string `json:"ModifierFullName,omitempty"`

	// Project: Edm.Guid
	Project *types.GUID `json:"Project,omitempty"`

	// ProjectCode: Edm.String
	ProjectCode *string `json:"ProjectCode,omitempty"`

	// ProjectDescription: Edm.String
	ProjectDescription *string `json:"ProjectDescription,omitempty"`
}

func (e *ProjectRestrictionEmployees) GetPrimary() *types.GUID {
	return e.ID
}

func (s *ProjectRestrictionEmployeesEndpoint) UserHasRights(ctx context.Context, division int, method string) (bool, error) {
	return s.client.UserHasRights(ctx, division, "project/ProjectRestrictionEmployees", method)
}

// List the ProjectRestrictionEmployees entities in the provided division.
// If all is true, all the paginated results are fetched; if false, list the first page.
func (s *ProjectRestrictionEmployeesEndpoint) List(ctx context.Context, division int, all bool, o *api.ListOptions) ([]*ProjectRestrictionEmployees, error) {
	var entities []*ProjectRestrictionEmployees
	u, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/project/ProjectRestrictionEmployees", division) // #nosec
	api.AddListOptionsToURL(u, o)

	if all {
		err := s.client.ListRequestAndDoAll(ctx, u.String(), &entities)
		return entities, err
	}
	_, _, err := s.client.NewRequestAndDo(ctx, "GET", u.String(), nil, &entities)
	return entities, err
}

// Get the ProjectRestrictionEmployees entitiy in the provided division.
func (s *ProjectRestrictionEmployeesEndpoint) Get(ctx context.Context, division int, id *types.GUID) (*ProjectRestrictionEmployees, error) {
	b, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/project/ProjectRestrictionEmployees", division) // #nosec
	u, err := api.AddOdataKeyToURL(b, id)
	if err != nil {
		return nil, err
	}

	e := &ProjectRestrictionEmployees{}
	_, _, requestError := s.client.NewRequestAndDo(ctx, "GET", u.String(), nil, e)
	return e, requestError
}

// New returns an empty ProjectRestrictionEmployees entity
func (s *ProjectRestrictionEmployeesEndpoint) New() *ProjectRestrictionEmployees {
	return &ProjectRestrictionEmployees{}
}

// Create the ProjectRestrictionEmployees entity in the provided division.
func (s *ProjectRestrictionEmployeesEndpoint) Create(ctx context.Context, division int, entity *ProjectRestrictionEmployees) (*ProjectRestrictionEmployees, error) {
	u, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/project/ProjectRestrictionEmployees", division) // #nosec
	e := &ProjectRestrictionEmployees{}
	_, _, err := s.client.NewRequestAndDo(ctx, "POST", u.String(), entity, e)
	if err != nil {
		return nil, err
	}
	return e, nil
}

// Update the ProjectRestrictionEmployees entity in the provided division.
func (s *ProjectRestrictionEmployeesEndpoint) Update(ctx context.Context, division int, entity *ProjectRestrictionEmployees) (*ProjectRestrictionEmployees, error) {
	b, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/project/ProjectRestrictionEmployees", division) // #nosec
	u, err := api.AddOdataKeyToURL(b, entity.GetPrimary())
	if err != nil {
		return nil, err
	}

	e := &ProjectRestrictionEmployees{}
	_, _, requestError := s.client.NewRequestAndDo(ctx, "PUT", u.String(), entity, e)
	return e, requestError
}

// Delete the ProjectRestrictionEmployees entity in the provided division.
func (s *ProjectRestrictionEmployeesEndpoint) Delete(ctx context.Context, division int, id *types.GUID) error {
	b, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/project/ProjectRestrictionEmployees", division) // #nosec
	u, err := api.AddOdataKeyToURL(b, id)
	if err != nil {
		return err
	}

	_, r, requestError := s.client.NewRequestAndDo(ctx, "DELETE", u.String(), nil, nil)
	if requestError != nil {
		return requestError
	}

	if r.StatusCode != http.StatusNoContent {
		body, _ := ioutil.ReadAll(r.Body) // #nosec
		return fmt.Errorf("Failed with status %v and body %v", r.StatusCode, body)
	}

	return nil
}
