// Copyright 2024 The go-exactonline AUTHORS. All rights reserved.
//
// Use of this source code is governed by a MIT
// license that can be found in the LICENSE file.
// Code generated by gen-services.go; DO NOT EDIT.
package project

import (
	"context"
	"fmt"
	"io/ioutil"
	"net/http"

	"github.com/mcnijman/go-exactonline/api"
	"github.com/mcnijman/go-exactonline/types"
)

// ProjectAccountMutationsEndpoint is responsible for communicating with
// the ProjectAccountMutations endpoint of the Project service.
type ProjectAccountMutationsEndpoint service

// ProjectAccountMutations:
// Service: Project
// Entity: ProjectAccountMutations
// URL: /api/v1/{division}/project/ProjectAccountMutations
// HasWebhook: false
// IsInBeta: false
// Methods: GET POST PUT DELETE
// Endpoint docs: https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=ProjectProjectAccountMutations
type ProjectAccountMutations struct {
	MetaData *api.MetaData `json:"__metadata,omitempty"`
	// ID: Edm.Guid
	ID *types.GUID `json:"ID,omitempty"`

	// Account: Edm.Guid
	Account *types.GUID `json:"Account,omitempty"`

	// AccountCode: Edm.String
	AccountCode *string `json:"AccountCode,omitempty"`

	// AccountName: Edm.String
	AccountName *string `json:"AccountName,omitempty"`

	// Created: Edm.DateTime
	Created *types.Date `json:"Created,omitempty"`

	// Creator: Edm.Guid
	Creator *types.GUID `json:"Creator,omitempty"`

	// CreatorFullName: Edm.String
	CreatorFullName *string `json:"CreatorFullName,omitempty"`

	// Division: Edm.Int32
	Division *int `json:"Division,omitempty"`

	// DivisionName: Edm.String
	DivisionName *string `json:"DivisionName,omitempty"`

	// EndDate: Edm.DateTime
	EndDate *types.Date `json:"EndDate,omitempty"`

	// Modified: Edm.DateTime
	Modified *types.Date `json:"Modified,omitempty"`

	// Modifier: Edm.Guid
	Modifier *types.GUID `json:"Modifier,omitempty"`

	// ModifierFullName: Edm.String
	ModifierFullName *string `json:"ModifierFullName,omitempty"`

	// Notes: Edm.String
	Notes *string `json:"Notes,omitempty"`

	// Project: Edm.Guid
	Project *types.GUID `json:"Project,omitempty"`

	// ProjectCode: Edm.String
	ProjectCode *string `json:"ProjectCode,omitempty"`

	// ProjectDescription: Edm.String
	ProjectDescription *string `json:"ProjectDescription,omitempty"`

	// StartDate: Edm.DateTime
	StartDate *types.Date `json:"StartDate,omitempty"`
}

func (e *ProjectAccountMutations) GetPrimary() *types.GUID {
	return e.ID
}

func (s *ProjectAccountMutationsEndpoint) UserHasRights(ctx context.Context, division int, method string) (bool, error) {
	return s.client.UserHasRights(ctx, division, "project/ProjectAccountMutations", method)
}

// List the ProjectAccountMutations entities in the provided division.
// If all is true, all the paginated results are fetched; if false, list the first page.
func (s *ProjectAccountMutationsEndpoint) List(ctx context.Context, division int, all bool, o *api.ListOptions) ([]*ProjectAccountMutations, error) {
	var entities []*ProjectAccountMutations
	u, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/project/ProjectAccountMutations", division) // #nosec
	api.AddListOptionsToURL(u, o)

	if all {
		err := s.client.ListRequestAndDoAll(ctx, u.String(), &entities)
		return entities, err
	}
	_, _, err := s.client.NewRequestAndDo(ctx, "GET", u.String(), nil, &entities)
	return entities, err
}

// Get the ProjectAccountMutations entitiy in the provided division.
func (s *ProjectAccountMutationsEndpoint) Get(ctx context.Context, division int, id *types.GUID) (*ProjectAccountMutations, error) {
	b, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/project/ProjectAccountMutations", division) // #nosec
	u, err := api.AddOdataKeyToURL(b, id)
	if err != nil {
		return nil, err
	}

	e := &ProjectAccountMutations{}
	_, _, requestError := s.client.NewRequestAndDo(ctx, "GET", u.String(), nil, e)
	return e, requestError
}

// New returns an empty ProjectAccountMutations entity
func (s *ProjectAccountMutationsEndpoint) New() *ProjectAccountMutations {
	return &ProjectAccountMutations{}
}

// Create the ProjectAccountMutations entity in the provided division.
func (s *ProjectAccountMutationsEndpoint) Create(ctx context.Context, division int, entity *ProjectAccountMutations) (*ProjectAccountMutations, error) {
	u, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/project/ProjectAccountMutations", division) // #nosec
	e := &ProjectAccountMutations{}
	_, _, err := s.client.NewRequestAndDo(ctx, "POST", u.String(), entity, e)
	if err != nil {
		return nil, err
	}
	return e, nil
}

// Update the ProjectAccountMutations entity in the provided division.
func (s *ProjectAccountMutationsEndpoint) Update(ctx context.Context, division int, entity *ProjectAccountMutations) (*ProjectAccountMutations, error) {
	b, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/project/ProjectAccountMutations", division) // #nosec
	u, err := api.AddOdataKeyToURL(b, entity.GetPrimary())
	if err != nil {
		return nil, err
	}

	e := &ProjectAccountMutations{}
	_, _, requestError := s.client.NewRequestAndDo(ctx, "PUT", u.String(), entity, e)
	return e, requestError
}

// Delete the ProjectAccountMutations entity in the provided division.
func (s *ProjectAccountMutationsEndpoint) Delete(ctx context.Context, division int, id *types.GUID) error {
	b, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/project/ProjectAccountMutations", division) // #nosec
	u, err := api.AddOdataKeyToURL(b, id)
	if err != nil {
		return err
	}

	_, r, requestError := s.client.NewRequestAndDo(ctx, "DELETE", u.String(), nil, nil)
	if requestError != nil {
		return requestError
	}

	if r.StatusCode != http.StatusNoContent {
		body, _ := ioutil.ReadAll(r.Body) // #nosec
		return fmt.Errorf("Failed with status %v and body %v", r.StatusCode, body)
	}

	return nil
}
