// Copyright 2024 The go-exactonline AUTHORS. All rights reserved.
//
// Use of this source code is governed by a MIT
// license that can be found in the LICENSE file.
// Code generated by gen-services.go; DO NOT EDIT.
package project

import (
	"context"

	"github.com/mcnijman/go-exactonline/api"
	"github.com/mcnijman/go-exactonline/types"
)

// RecentCostsEndpoint is responsible for communicating with
// the RecentCosts endpoint of the Project service.
type RecentCostsEndpoint service

// RecentCosts:
// Service: Project
// Entity: RecentCosts
// URL: /api/v1/{division}/read/project/RecentCosts
// HasWebhook: false
// IsInBeta: false
// Methods: GET
// Endpoint docs: https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=ReadProjectRecentCosts
type RecentCosts struct {
	MetaData *api.MetaData `json:"__metadata,omitempty"`
	// Id: Edm.Int32
	Id *int `json:"Id,omitempty"`

	// AccountCode: Edm.String
	AccountCode *string `json:"AccountCode,omitempty"`

	// AccountId: Edm.Guid
	AccountId *types.GUID `json:"AccountId,omitempty"`

	// AccountName: Edm.String
	AccountName *string `json:"AccountName,omitempty"`

	// AmountApproved: Edm.Double
	AmountApproved *float64 `json:"AmountApproved,omitempty"`

	// AmountDraft: Edm.Double
	AmountDraft *float64 `json:"AmountDraft,omitempty"`

	// AmountRejected: Edm.Double
	AmountRejected *float64 `json:"AmountRejected,omitempty"`

	// AmountSubmitted: Edm.Double
	AmountSubmitted *float64 `json:"AmountSubmitted,omitempty"`

	// CurrencyCode: Edm.String
	CurrencyCode *string `json:"CurrencyCode,omitempty"`

	// Date: Edm.DateTime
	Date *types.Date `json:"Date,omitempty"`

	// EntryId: Edm.Guid
	EntryId *types.GUID `json:"EntryId,omitempty"`

	// Expense: Edm.Guid
	Expense *types.GUID `json:"Expense,omitempty"`

	// ExpenseDescription: Edm.String
	ExpenseDescription *string `json:"ExpenseDescription,omitempty"`

	// ItemCode: Edm.String
	ItemCode *string `json:"ItemCode,omitempty"`

	// ItemDescription: Edm.String
	ItemDescription *string `json:"ItemDescription,omitempty"`

	// ItemId: Edm.Guid
	ItemId *types.GUID `json:"ItemId,omitempty"`

	// Notes: Edm.String
	Notes *string `json:"Notes,omitempty"`

	// ProjectCode: Edm.String
	ProjectCode *string `json:"ProjectCode,omitempty"`

	// ProjectDescription: Edm.String
	ProjectDescription *string `json:"ProjectDescription,omitempty"`

	// ProjectId: Edm.Guid
	ProjectId *types.GUID `json:"ProjectId,omitempty"`

	// QuantityApproved: Edm.Double
	QuantityApproved *float64 `json:"QuantityApproved,omitempty"`

	// QuantityDraft: Edm.Double
	QuantityDraft *float64 `json:"QuantityDraft,omitempty"`

	// QuantityRejected: Edm.Double
	QuantityRejected *float64 `json:"QuantityRejected,omitempty"`

	// QuantitySubmitted: Edm.Double
	QuantitySubmitted *float64 `json:"QuantitySubmitted,omitempty"`

	// WeekNumber: Edm.Int32
	WeekNumber *int `json:"WeekNumber,omitempty"`
}

func (e *RecentCosts) GetPrimary() *int {
	return e.Id
}

func (s *RecentCostsEndpoint) UserHasRights(ctx context.Context, division int, method string) (bool, error) {
	return s.client.UserHasRights(ctx, division, "project/RecentCosts", method)
}

// List the RecentCosts entities in the provided division.
// If all is true, all the paginated results are fetched; if false, list the first page.
func (s *RecentCostsEndpoint) List(ctx context.Context, division int, all bool, o *api.ListOptions) ([]*RecentCosts, error) {
	var entities []*RecentCosts
	u, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/read/project/RecentCosts", division) // #nosec
	api.AddListOptionsToURL(u, o)

	if all {
		err := s.client.ListRequestAndDoAll(ctx, u.String(), &entities)
		return entities, err
	}
	_, _, err := s.client.NewRequestAndDo(ctx, "GET", u.String(), nil, &entities)
	return entities, err
}

// Get the RecentCosts entitiy in the provided division.
func (s *RecentCostsEndpoint) Get(ctx context.Context, division int, id *int) (*RecentCosts, error) {
	b, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/read/project/RecentCosts", division) // #nosec
	u, err := api.AddOdataKeyToURL(b, id)
	if err != nil {
		return nil, err
	}

	e := &RecentCosts{}
	_, _, requestError := s.client.NewRequestAndDo(ctx, "GET", u.String(), nil, e)
	return e, requestError
}
