// Copyright 2024 The go-exactonline AUTHORS. All rights reserved.
//
// Use of this source code is governed by a MIT
// license that can be found in the LICENSE file.
// Code generated by gen-services.go; DO NOT EDIT.
package sales

import (
	"context"

	"github.com/mcnijman/go-exactonline/api"
	"github.com/mcnijman/go-exactonline/types"
)

// SalesPriceListLinkedAccountsEndpoint is responsible for communicating with
// the SalesPriceListLinkedAccounts endpoint of the Sales service.
type SalesPriceListLinkedAccountsEndpoint service

// SalesPriceListLinkedAccounts:
// Service: Sales
// Entity: SalesPriceListLinkedAccounts
// URL: /api/v1/{division}/sales/SalesPriceListLinkedAccounts
// HasWebhook: false
// IsInBeta: false
// Methods: GET
// Endpoint docs: https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=SalesSalesPriceListLinkedAccounts
type SalesPriceListLinkedAccounts struct {
	MetaData *api.MetaData `json:"__metadata,omitempty"`
	// ID: Edm.Guid
	ID *types.GUID `json:"ID,omitempty"`

	// Code: Edm.String
	Code *string `json:"Code,omitempty"`

	// Created: Edm.DateTime
	Created *types.Date `json:"Created,omitempty"`

	// Creator: Edm.Guid
	Creator *types.GUID `json:"Creator,omitempty"`

	// CreatorFullName: Edm.String
	CreatorFullName *string `json:"CreatorFullName,omitempty"`

	// Division: Edm.Int32
	Division *int `json:"Division,omitempty"`

	// Modified: Edm.DateTime
	Modified *types.Date `json:"Modified,omitempty"`

	// Modifier: Edm.Guid
	Modifier *types.GUID `json:"Modifier,omitempty"`

	// ModifierFullName: Edm.String
	ModifierFullName *string `json:"ModifierFullName,omitempty"`

	// Name: Edm.String
	Name *string `json:"Name,omitempty"`

	// PriceList: Edm.Guid
	PriceList *types.GUID `json:"PriceList,omitempty"`
}

func (e *SalesPriceListLinkedAccounts) GetPrimary() *types.GUID {
	return e.ID
}

func (s *SalesPriceListLinkedAccountsEndpoint) UserHasRights(ctx context.Context, division int, method string) (bool, error) {
	return s.client.UserHasRights(ctx, division, "sales/SalesPriceListLinkedAccounts", method)
}

// List the SalesPriceListLinkedAccounts entities in the provided division.
// If all is true, all the paginated results are fetched; if false, list the first page.
func (s *SalesPriceListLinkedAccountsEndpoint) List(ctx context.Context, division int, all bool, o *api.ListOptions) ([]*SalesPriceListLinkedAccounts, error) {
	var entities []*SalesPriceListLinkedAccounts
	u, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/sales/SalesPriceListLinkedAccounts", division) // #nosec
	api.AddListOptionsToURL(u, o)

	if all {
		err := s.client.ListRequestAndDoAll(ctx, u.String(), &entities)
		return entities, err
	}
	_, _, err := s.client.NewRequestAndDo(ctx, "GET", u.String(), nil, &entities)
	return entities, err
}

// Get the SalesPriceListLinkedAccounts entitiy in the provided division.
func (s *SalesPriceListLinkedAccountsEndpoint) Get(ctx context.Context, division int, id *types.GUID) (*SalesPriceListLinkedAccounts, error) {
	b, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/sales/SalesPriceListLinkedAccounts", division) // #nosec
	u, err := api.AddOdataKeyToURL(b, id)
	if err != nil {
		return nil, err
	}

	e := &SalesPriceListLinkedAccounts{}
	_, _, requestError := s.client.NewRequestAndDo(ctx, "GET", u.String(), nil, e)
	return e, requestError
}
