// Copyright 2024 The go-exactonline AUTHORS. All rights reserved.
//
// Use of this source code is governed by a MIT
// license that can be found in the LICENSE file.
// Code generated by gen-services.go; DO NOT EDIT.
package sales

import (
	"context"

	"github.com/mcnijman/go-exactonline/api"
	"github.com/mcnijman/go-exactonline/types"
)

// ShippingMethodsEndpoint is responsible for communicating with
// the ShippingMethods endpoint of the Sales service.
type ShippingMethodsEndpoint service

// ShippingMethods:
// Service: Sales
// Entity: ShippingMethods
// URL: /api/v1/{division}/sales/ShippingMethods
// HasWebhook: false
// IsInBeta: false
// Methods: GET
// Endpoint docs: https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=SalesShippingMethods
type ShippingMethods struct {
	MetaData *api.MetaData `json:"__metadata,omitempty"`
	// ID: Edm.Guid
	ID *types.GUID `json:"ID,omitempty"`

	// Active: Edm.Boolean
	Active *bool `json:"Active,omitempty"`

	// Amount: Edm.Double
	Amount *float64 `json:"Amount,omitempty"`

	// Code: Edm.String
	Code *string `json:"Code,omitempty"`

	// Created: Edm.DateTime
	Created *types.Date `json:"Created,omitempty"`

	// Creator: Edm.Guid
	Creator *types.GUID `json:"Creator,omitempty"`

	// CreatorFullName: Edm.String
	CreatorFullName *string `json:"CreatorFullName,omitempty"`

	// Description: Edm.String
	Description *string `json:"Description,omitempty"`

	// Division: Edm.Int32
	Division *int `json:"Division,omitempty"`

	// Modified: Edm.DateTime
	Modified *types.Date `json:"Modified,omitempty"`

	// Modifier: Edm.Guid
	Modifier *types.GUID `json:"Modifier,omitempty"`

	// ModifierFullName: Edm.String
	ModifierFullName *string `json:"ModifierFullName,omitempty"`

	// Notes: Edm.String
	Notes *string `json:"Notes,omitempty"`

	// ShippingRatesURL: Edm.String
	ShippingRatesURL *string `json:"ShippingRatesURL,omitempty"`

	// TrackingURL: Edm.String
	TrackingURL *string `json:"TrackingURL,omitempty"`

	// VATCode: Edm.String
	VATCode *string `json:"VATCode,omitempty"`

	// VATCodeDescription: Edm.String
	VATCodeDescription *string `json:"VATCodeDescription,omitempty"`

	// VATPercentage: Edm.Double
	VATPercentage *float64 `json:"VATPercentage,omitempty"`
}

func (e *ShippingMethods) GetPrimary() *types.GUID {
	return e.ID
}

func (s *ShippingMethodsEndpoint) UserHasRights(ctx context.Context, division int, method string) (bool, error) {
	return s.client.UserHasRights(ctx, division, "sales/ShippingMethods", method)
}

// List the ShippingMethods entities in the provided division.
// If all is true, all the paginated results are fetched; if false, list the first page.
func (s *ShippingMethodsEndpoint) List(ctx context.Context, division int, all bool, o *api.ListOptions) ([]*ShippingMethods, error) {
	var entities []*ShippingMethods
	u, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/sales/ShippingMethods", division) // #nosec
	api.AddListOptionsToURL(u, o)

	if all {
		err := s.client.ListRequestAndDoAll(ctx, u.String(), &entities)
		return entities, err
	}
	_, _, err := s.client.NewRequestAndDo(ctx, "GET", u.String(), nil, &entities)
	return entities, err
}

// Get the ShippingMethods entitiy in the provided division.
func (s *ShippingMethodsEndpoint) Get(ctx context.Context, division int, id *types.GUID) (*ShippingMethods, error) {
	b, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/sales/ShippingMethods", division) // #nosec
	u, err := api.AddOdataKeyToURL(b, id)
	if err != nil {
		return nil, err
	}

	e := &ShippingMethods{}
	_, _, requestError := s.client.NewRequestAndDo(ctx, "GET", u.String(), nil, e)
	return e, requestError
}
