// Copyright 2024 The go-exactonline AUTHORS. All rights reserved.
//
// Use of this source code is governed by a MIT
// license that can be found in the LICENSE file.
// Code generated by gen-services.go; DO NOT EDIT.
package documents

import (
	"context"

	"github.com/mcnijman/go-exactonline/api"
	"github.com/mcnijman/go-exactonline/types"
)

// DocumentTypesEndpoint is responsible for communicating with
// the DocumentTypes endpoint of the Documents service.
type DocumentTypesEndpoint service

// DocumentTypes:
// Service: Documents
// Entity: DocumentTypes
// URL: /api/v1/{division}/documents/DocumentTypes
// HasWebhook: false
// IsInBeta: false
// Methods: GET
// Endpoint docs: https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=DocumentsDocumentTypes
type DocumentTypes struct {
	MetaData *api.MetaData `json:"__metadata,omitempty"`
	// ID: Edm.Int32
	ID *int `json:"ID,omitempty"`

	// Created: Edm.DateTime
	Created *types.Date `json:"Created,omitempty"`

	// Description: Edm.String
	Description *string `json:"Description,omitempty"`

	// DocumentIsCreatable: Edm.Boolean
	DocumentIsCreatable *bool `json:"DocumentIsCreatable,omitempty"`

	// DocumentIsDeletable: Edm.Boolean
	DocumentIsDeletable *bool `json:"DocumentIsDeletable,omitempty"`

	// DocumentIsUpdatable: Edm.Boolean
	DocumentIsUpdatable *bool `json:"DocumentIsUpdatable,omitempty"`

	// DocumentIsViewable: Edm.Boolean
	DocumentIsViewable *bool `json:"DocumentIsViewable,omitempty"`

	// Modified: Edm.DateTime
	Modified *types.Date `json:"Modified,omitempty"`

	// TypeCategory: Edm.Int32
	TypeCategory *int `json:"TypeCategory,omitempty"`
}

func (e *DocumentTypes) GetPrimary() *int {
	return e.ID
}

func (s *DocumentTypesEndpoint) UserHasRights(ctx context.Context, division int, method string) (bool, error) {
	return s.client.UserHasRights(ctx, division, "documents/DocumentTypes", method)
}

// List the DocumentTypes entities in the provided division.
// If all is true, all the paginated results are fetched; if false, list the first page.
func (s *DocumentTypesEndpoint) List(ctx context.Context, division int, all bool, o *api.ListOptions) ([]*DocumentTypes, error) {
	var entities []*DocumentTypes
	u, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/documents/DocumentTypes", division) // #nosec
	api.AddListOptionsToURL(u, o)

	if all {
		err := s.client.ListRequestAndDoAll(ctx, u.String(), &entities)
		return entities, err
	}
	_, _, err := s.client.NewRequestAndDo(ctx, "GET", u.String(), nil, &entities)
	return entities, err
}

// Get the DocumentTypes entitiy in the provided division.
func (s *DocumentTypesEndpoint) Get(ctx context.Context, division int, id *int) (*DocumentTypes, error) {
	b, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/documents/DocumentTypes", division) // #nosec
	u, err := api.AddOdataKeyToURL(b, id)
	if err != nil {
		return nil, err
	}

	e := &DocumentTypes{}
	_, _, requestError := s.client.NewRequestAndDo(ctx, "GET", u.String(), nil, e)
	return e, requestError
}
